This notebook will preprocess the input raw datasets of a year named reference and its previous year to produce in the intermediary folder profit_shiftings_outward_{YEAR_A}.xlsx and profit_shiftings_outward_{YEAR_B}.xlsx dataset, respectively.

### Imports

In [1]:
import pandas as pd
import tjn_tools
from config import YEAR_A, YEAR_B, PATH_PSO_A, PATH_PSO_A_CLEAN, PATH_PSO_B, PATH_PSO_B_CLEAN

### Profit Shiftings Outward Reference Year

In [2]:
pso_a = pd.read_excel(PATH_PSO_A)
pso_a.head()

,Name,MNCs,CIT,ETR,Profit loss (M),Min. Profit loss (M),Max. Profit loss (M),Revenue loss using CIT (M),Min. Revenue loss using CIT (M),Max. Revenue loss using CIT (M),...,Robust,3+reporters,N_reporters,gdp,pop,Profit loss per gdp (%),Profit loss per health (%),Profit loss per educ (%),Profit loss per tax_revenue (%),Profit loss per pop ($ per capita)
0,Africa,0,27.94,30.39,32528,5638,50993,9417.0,1992.9,14533.0,...,123,56,750,7043171964790,3564297929,0.5,31.4,5.9,2.2,9
1,Algeria,Domestic,26.00,51.11,657,-2648,1975,170.8,-688.5,513.4,...,0,0,0,176426536015,40983116,0.4,8.4,0.0,2.6,16
2,Algeria,Foreign (in),26.00,51.11,0,0,0,0.0,0.0,0.0,...,1,1,14,176426536015,40983116,0.0,0.0,0.0,0.0,0
3,Algeria,Foreign (out),26.00,51.11,70,40,179,18.2,10.4,46.4,...,2,1,14,176426536015,40983116,0.0,0.9,0.0,0.3,1
4,Angola,Domestic,30.00,28.84,0,0,0,0.0,0.0,0.0,...,0,0,0,109367590033,29375318,0.0,0.0,0.0,0.0,0

In [3]:
# Keep only columns of interest
pso_a = pso_a.loc[:,['Name', 'Profit loss (M)']]
# Add iso3 column
pso_a.insert(0, "iso3", pso_a["Name"].apply(tjn_tools.name_to_iso3, print_failure=True))
# Drop regions rows
pso_a = pso_a.loc[pso_a['iso3'].notnull()]
# Convert negative Profit loss (M) numbers to 0 - To only consider outward profit shiftings
# and keep track of all initial countries available
pso_a.loc[pso_a['Profit loss (M)'] <=0,'Profit loss (M)'] = 0
# Group profit shiftings by country
pso_a = pso_a.groupby(by=['iso3', 'Name']).sum().reset_index()
# Convert units to USD
pso_a['shifted_profits_outward'] = pso_a['Profit loss (M)'] * 1000000
# Rename columns and change units
pso_a.drop(columns=['Profit loss (M)'], inplace=True)
pso_a.rename(columns={'Name':'country'}, inplace=True)
pso_a

"Africa" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Asia" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Caribbean/American isl." is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Europe" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Latin America" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Northern America" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Oceania" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json

    iso3       country  shifted_profits_outward
0    ABW         Aruba                 18000000
1    AFG   Afghanistan                        0
2    AGO        Angola                503000000
3    AIA      Anguilla                        0
4    ALB       Albania                321000000
..   ...           ...                      ...
208  XKX        Kosovo                 14000000
209  YEM         Yemen                  2000000
210  ZAF  South Africa              10855000000
211  ZMB        Zambia               2759000000
212  ZWE      Zimbabwe                 47000000

[213 rows x 3 columns]

In [4]:
# Check total profit shifting is equal to 1.58 trillion
print(f'Total profit shifting for {YEAR_A} is:', f"{pso_a['shifted_profits_outward'].sum():,.0f}", 'USD')

Total profit shifting for 2018 is: 1,576,993,000,000 USD

In [5]:
# Save dataset in intermediate folder
pso_a.to_excel(PATH_PSO_A_CLEAN, index=False)

### Profit Shiftings Outward Previous Year to Reference

In [6]:
pso_b = pd.read_excel(PATH_PSO_B)
pso_b.head()

,Name,MNCs,CIT,ETR,Profit loss (M),Min. Profit loss (M),Max. Profit loss (M),Revenue loss using CIT (M),Min. Revenue loss using CIT (M),Max. Revenue loss using CIT (M),...,Robust,3+reporters,N_reporters,gdp,pop,Profit loss per gdp (%),Profit loss per health (%),Profit loss per educ (%),Profit loss per tax_revenue (%),Profit loss per pop ($ per capita)
0,Africa,NaN,27.32,28.95,34397,21787,47949,11332.5,8132.7,14847.1,...,133,61,683,6984814143368,3398176003,0.5,48.0,10.0,0.6,10
1,Algeria,Domestic,25.00,14.91,778,153,1480,194.5,38.3,370.1,...,1,0,0,180052364452,40583203,0.4,9.7,NaN,3.0,19
2,Algeria,Foreign (in),25.00,14.91,-3784,-4201,-3370,-945.9,-1050.2,-842.5,...,2,1,11,180052364452,40583203,-2.1,-47.4,NaN,-14.7,-93
3,Algeria,Foreign (out),25.00,14.91,840,748,946,209.9,186.9,236.5,...,2,1,11,180052364452,40583203,0.5,10.5,NaN,3.3,20
4,Angola,Domestic,30.00,54.32,0,0,0,0.0,0.0,0.0,...,0,0,0,111443730434,28901163,0.0,0.0,NaN,0.0,0

In [7]:
# Keep only columns of interest
pso_b = pso_b.loc[:,['Name', 'Profit loss (M)']]
# Add iso3 column
pso_b.insert(0, "iso3", pso_b["Name"].apply(tjn_tools.name_to_iso3, print_failure=True))
# Drop regions rows
pso_b = pso_b.loc[pso_b['iso3'].notnull()]
# Convert negative Profit loss (M) numbers to 0 - To only consider outward profit shiftings
# and keep track of all initial countries available
pso_b.loc[pso_b['Profit loss (M)'] <=0,'Profit loss (M)'] = 0
# Group profit shiftings by country
pso_b = pso_b.groupby(by=['iso3', 'Name']).sum().reset_index()
# Convert units to USD
pso_b['shifted_profits_outward'] = pso_b['Profit loss (M)'] * 1000000
# Rename columns and change units
pso_b.drop(columns=['Profit loss (M)'], inplace=True)
pso_b.rename(columns={'Name':'country'}, inplace=True)
pso_b

"Africa" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Asia" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Caribbean/American isl." is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Europe" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Latin America" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Northern America" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Oceania" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json

    iso3       country  shifted_profits_outward
0    ABW         Aruba                 23000000
1    AFG   Afghanistan                244000000
2    AGO        Angola                603000000
3    AIA      Anguilla                  3000000
4    ALB       Albania                294000000
..   ...           ...                      ...
209  XKX        Kosovo                  8000000
210  YEM         Yemen                 66000000
211  ZAF  South Africa              10363000000
212  ZMB        Zambia               1738000000
213  ZWE      Zimbabwe                262000000

[214 rows x 3 columns]

In [8]:
# Check total profit shifting is equal to 1.19 trillion for 2017
print(f'Total profit shifting for {YEAR_B} is:', f"{pso_b['shifted_profits_outward'].sum():,.0f}", 'USD')

Total profit shifting for 2017 is: 1,191,786,000,000 USD

In [9]:
# Save dataset in intermediate folder
pso_b.to_excel(PATH_PSO_B_CLEAN, index=False)