This notebook will check whether the increase in profit shiftings stem from the inflation.

In [1]:
import pandas as pd
import tjn_tools
from config import YEAR_A, YEAR_B, PATH_PSO_A_CLEAN, PATH_PSO_B_CLEAN, PATH_INFLATION_WB

In [2]:
# Retrieve profits shiftings outwards for Year A and B
pso_b = pd.read_excel(PATH_PSO_B_CLEAN)
pso_a = pd.read_excel(PATH_PSO_A_CLEAN)
pso_b

    iso3       country  shifted_profits_outward
0    ABW         Aruba                 35000000
1    AFG   Afghanistan                  5000000
2    AGO        Angola               3418000000
3    ALB       Albania                257000000
4    AND       Andorra                119000000
..   ...           ...                      ...
183  WSM         Samoa                        0
184  YEM         Yemen                259000000
185  ZAF  South Africa              17114000000
186  ZMB        Zambia                426000000
187  ZWE      Zimbabwe                200000000

[188 rows x 3 columns]

In [3]:
# Retrieve inflation data
inflation = pd.read_csv(PATH_INFLATION_WB)
# Retrieve inflation of USA for Year A
inflation_usa_year_a = inflation.loc[(inflation['iso3']=='USA') & (inflation['year']==YEAR_A),'inflation'].values[0]
print(f'Inflation usa {YEAR_A}:', f"{inflation_usa_year_a:,.3f}", '%')

Inflation usa 2017: 2.130 %

In [4]:
# Calculate adjusted Year A data
pso_a_adjusted = pso_a.copy()
pso_a_adjusted.insert(3, 'adjusted_shifted_profits_outward', pso_a_adjusted['shifted_profits_outward'] * (1-((inflation_usa_year_a/100))))
pso_a_adjusted

,iso3,country,shifted_profits_outward,adjusted_shifted_profits_outward
0,ABW,Aruba,23000000,2.251007e+07
1,AFG,Afghanistan,244000000,2.388025e+08
2,AGO,Angola,603000000,5.901554e+08
3,AIA,Anguilla,3000000,2.936097e+06
4,ALB,Albania,294000000,2.877375e+08
...,...,...,...,...
209,XKX,Kosovo,8000000,7.829591e+06
210,YEM,Yemen,66000000,6.459413e+07
211,ZAF,South Africa,10363000000,1.014226e+10
212,ZMB,Zambia,1738000000,1.700979e+09
213,ZWE,Zimbabwe,262000000,2.564191e+08

In [5]:
# Compare profit shifting between Year A data and adjusted Year A data
profits_shifting_a = pso_a_adjusted['shifted_profits_outward'].sum()
profits_shifting_a_adjusted = int(pso_a_adjusted['adjusted_shifted_profits_outward'].sum())

print(f'Profits shifted in {YEAR_A}:', f"{profits_shifting_a:,.0f}" , 'USD')
print(f'Profits shifted in {YEAR_A} with inflation adjustment:',  f"{profits_shifting_a_adjusted:,.0f}" , 'USD')
print(f'Increase in shifted in {YEAR_A} explained by inflation:',f"{profits_shifting_a - profits_shifting_a_adjusted:,.0f}", 'USD')

Profits shifted in 2017: 1,191,786,000,000 USD
Profits shifted in 2017 with inflation adjustment: 1,166,399,647,191 USD
Increase in shifted in 2017 explained by inflation: 25,386,352,809 USD