This notebook aims to determine whether the rise in absolute profit shiftings is due to an increase in company profits, an increase in the percentage of profits shifted, or both.

In [4]:
import pandas as pd
from config import YEAR_A, YEAR_B, PATH_PSO_A_CLEAN, PATH_PSO_B_CLEAN, PATH_MNC_PROFITS_B, PATH_MNC_PROFITS_A

In [5]:
# Retrieve profits shiftings outwards for years A and B
pso_b = pd.read_excel(PATH_PSO_B_CLEAN)
pso_a = pd.read_excel(PATH_PSO_A_CLEAN)
pso_b

    iso3       country  shifted_profits_outward
0    ABW         Aruba                 35000000
1    AFG   Afghanistan                  5000000
2    AGO        Angola               3418000000
3    ALB       Albania                257000000
4    AND       Andorra                119000000
..   ...           ...                      ...
183  WSM         Samoa                        0
184  YEM         Yemen                259000000
185  ZAF  South Africa              17114000000
186  ZMB        Zambia                426000000
187  ZWE      Zimbabwe                200000000

[188 rows x 3 columns]

In [6]:
# TODO Check Replicates values 2017 - Should sum up 4.7 trillion
companies_profit_b = pd.read_csv(PATH_MNC_PROFITS_B, delimiter='\s+') 

# Keep only columns of interest
companies_profit_b = companies_profit_b.loc[:,['iso3_d','iso3_o','profits']]
companies_profit_b

FileNotFoundError: [Errno 2] No such file or directory: '/Users/danielcoll/Library/CloudStorage/OneDrive-SharedLibraries-TaxJusticeNetworkLtd/TJN - Shared Documents/Workstreams/Scale of Tax Injustice/State of Tax Justice report/Analysis/Corporate tax abuse/data/2016_replicates.csv'

In [ ]:
# TODO Check Replicates values 2017 - Should sum up 4.7 trillion
companies_profit_a = pd.read_csv(PATH_MNC_PROFITS_A, delimiter='\s+') 

# Keep only columns of interest
companies_profit_a = companies_profit_a.loc[:,['iso3_d','iso3_o','profits']]
companies_profit_a

        iso3_d iso3_o       profits
0          ARG    ARG  1.130656e+10
1          ARG    AUS  3.021018e+07
2          ARG    BMU  1.039692e+08
3          ARG    BRA  6.732973e+08
4          ARG    CHE  1.264322e+08
...        ...    ...           ...
2522995    SSD    SSD  0.000000e+00
2522996    TJK    ROU  2.461490e+06
2522997    TJK    TJK  0.000000e+00
2522998    TKM    SAU  0.000000e+00
2522999    TKM    TKM  0.000000e+00

[2523000 rows x 3 columns]

In [ ]:
# TODO Identify cause of wrong units for total profits - 1000 is a temporary fix
# Calculate total profits for years B and A
total_companies_profit_b = companies_profit_b['profits'].sum() / 1000 # TODO Delete / 1000 once we have the right data
total_companies_profit_a = companies_profit_a['profits'].sum() / 1000 # TODO Delete / 1000 once we have the right data
print(f'The total companies profit for {YEAR_B} is: ',f"{total_companies_profit_b:,.0f}", 'USD')
print(f'The total companies profit for {YEAR_A} is: ',f"{total_companies_profit_a:,.0f}", 'USD')
print(f'The increase in benefits between {YEAR_B} and {YEAR_A} is: ',f"{(total_companies_profit_a*100)/total_companies_profit_b - 100:,.2f}", '%')

The total companies profit for 2017 is:  4,727,410,014,218 USD
The total companies profit for 2018 is:  6,038,665,035,824 USD
The increase in benefits between 2017 and 2018 is:  27.74 %

In [ ]:
# Calculate profits shifted for years B and A
total_pso_b = pso_b['shifted_profits_outward'].sum()
total_pso_a = pso_a['shifted_profits_outward'].sum()
print(f'The total profits shifted outward for {YEAR_B} is:', f"{total_pso_b:,.0f}", 'USD')
print(f'The total profits shifted outward for {YEAR_A} is:', f"{total_pso_a:,.0f}", 'USD')

The total profits shifted outward for 2017 is: 1,191,786,000,000 USD
The total profits shifted outward for 2018 is: 1,576,993,000,000 USD

In [ ]:
# Calculate the proportion of profit that was shifted in year B in comparison to the total profits
share_profit_shifted_b = (total_pso_b*100)/total_companies_profit_b
print(f'The proportion of profit that was shifted in {YEAR_B} in comparison to the total profits is: ', f"{share_profit_shifted_b:,.2f}", '%')

# Calculate the proportion of profit that was shifted in year A in comparison to the total profits
share_profit_shifted_a = (total_pso_a*100)/total_companies_profit_a
print(f'The proportion of profit that was shifted in {YEAR_A} in comparison to the total profits is: ', f"{share_profit_shifted_a:,.2f}" , '%')
print(f'If the share of profit shifted in {YEAR_A} is higher than the share of profit shifted in {YEAR_B}, then corporations have shifted a higher proportion of their profits in {YEAR_A} than in {YEAR_B} \n')

# Calculate the proportional change in profits shifted between year B and A in comparison to the total profits
proportional_change_profit_shifted_a_b = ((share_profit_shifted_a - share_profit_shifted_b) / share_profit_shifted_b ) * 100
print(f'The proportional change in profits shifted between {YEAR_B} and {YEAR_A} in comparison to the total profits is: ', f"{proportional_change_profit_shifted_a_b:,.2f}", '%')

The proportion of profit that was shifted in 2017 in comparison to the total profits is:  25.21 %
The proportion of profit that was shifted in 2018 in comparison to the total profits is:  26.11 %
If the share of profit shifted in 2018 is higher than the share of profit shifted in 2017, then corporations have shifted a higher proportion of their profits in 2018 than in 2017

The proportional change in profits shifted between 2017 and 2018 in comparison to the total profits is:  3.59 %