This notebook will preprocess the input raw datasets `2018_tax_avoidance_sotj_table.xlsx` and `sotj_table_3_english_2021.xlsx` to produce in the intermediary folder profit_shiftings_outward_2022.xlsx and profit_shiftings_outward_2021.xlsx dataset, respectively.

In [85]:
import pandas as pd
import tjn_tools

### Profit Shiftings Outward 2022

In [86]:
pso_2022 = pd.read_excel('../data/raw/2018_tax_avoidance_sotj_table.xlsx')
pso_2022.head()

,Name,MNCs,CIT,ETR,Profit loss (M),Min. Profit loss (M),Max. Profit loss (M),Revenue loss using CIT (M),Min. Revenue loss using CIT (M),Max. Revenue loss using CIT (M),...,Robust,3+reporters,N_reporters,gdp,pop,Profit loss per gdp (%),Profit loss per health (%),Profit loss per educ (%),Profit loss per tax_revenue (%),Profit loss per pop ($ per capita)
0,Africa,0,27.94,30.39,32528,5638,50993,9417.0,1992.9,14533.0,...,123,56,750,7043170000000,3564297929,0.5,31.4,5.9,2.2,9
1,Algeria,Domestic,26.00,51.11,657,-2648,1975,170.8,-688.5,513.4,...,0,0,0,176427000000,40983116,0.4,8.4,0.0,2.6,16
2,Algeria,Foreign (in),26.00,51.11,0,0,0,0.0,0.0,0.0,...,1,1,14,176427000000,40983116,0.0,0.0,0.0,0.0,0
3,Algeria,Foreign (out),26.00,51.11,70,40,179,18.2,10.4,46.4,...,2,1,14,176427000000,40983116,0.0,0.9,0.0,0.3,1
4,Angola,Domestic,30.00,28.84,0,0,0,0.0,0.0,0.0,...,0,0,0,109368000000,29375318,0.0,0.0,0.0,0.0,0

In [87]:
# Keep only columns of interest
pso_2022 = pso_2022.loc[:,['Name', 'Profit loss (M)']]
# Add iso3 column
pso_2022.insert(0, "iso3", pso_2022["Name"].apply(tjn_tools.name_to_iso3, print_failure=True))
# Drop regions rows
pso_2022 = pso_2022.loc[pso_2022['iso3'].notnull()]
# Convert negative Profit loss (M) numbers to 0 - To only consider outward profit shiftings
# and keep track of all initial countries available
pso_2022.loc[pso_2022['Profit loss (M)'] <=0,'Profit loss (M)'] = 0
# Group profit shiftings by country
pso_2022 = pso_2022.groupby(by=['iso3', 'Name']).sum().reset_index()
# Rename columns
pso_2022.rename(columns={'Name':'Country','Profit loss (M)':'Shifted profits outward (USD million)'}, inplace=True)
pso_2022

"Africa" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Asia" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Caribbean/American isl." is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Europe" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Latin America" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Northern America" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Oceania" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json

    iso3       Country  Shifted profits outward (USD million)
0    ABW         Aruba                                     18
1    AFG   Afghanistan                                      0
2    AGO        Angola                                    503
3    AIA      Anguilla                                      0
4    ALB       Albania                                    321
..   ...           ...                                    ...
208  XKX        Kosovo                                     14
209  YEM         Yemen                                      2
210  ZAF  South Africa                                  10855
211  ZMB        Zambia                                   2759
212  ZWE      Zimbabwe                                     47

[213 rows x 3 columns]

In [88]:
# Check total profit shifting is equal to 1.58 trillion
pso_2022['Shifted profits outward (USD million)'].sum()

1576993

In [89]:
# Save dataset in intermediate folder
pso_2022.to_excel('../data/intermediate/profits_shifting_outward_2022.xlsx', index=False)

### Profit Shiftings Outward 2021

In [90]:
pso_2021 = pd.read_excel('../data/raw/sotj_table_3_english_2021.xlsx')
pso_2021.head()

,Country,Shifted profits inward (USD million),Shifted profits outward (USD million),Annual tax loss: Corporate tax abuse (USD million),Annual tax loss: Corporate tax abuse (% of GDP),Tax loss inflicted on others: Corporate tax abuse (USD million),Share of global tax loss inflicted: Corporate tax abuse
0,Africa,17076,51624,"14,796.8",0.6%,"4,534.2",1.5%
1,Algeria,3806,1655,413.8,0.2%,"1,010.6",0.3%
2,Angola,0,601,180.3,0.2%,0.0,0.0%
3,Benin,0,211,40.9,0.3%,0.0,0.0%
4,Botswana,209,23,5.1,0.0%,55.5,0.0%

In [91]:
# Keep only columns of interest
pso_2021 = pso_2021.loc[:,['Country', 'Shifted profits outward (USD million)']]
# Add iso3 column
pso_2021.insert(0, "iso3", pso_2021["Country"].apply(tjn_tools.name_to_iso3, print_failure=True))
# Drop regions rows
pso_2021 = pso_2021.loc[pso_2021['iso3'].notnull()]
pso_2021

"Africa" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Asia" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Caribbean and American islands" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Europe" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Latin America" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Northern America" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json
"Oceania" is not a valid country name. If appropriated, include it to harmonizing/name2iso3.json

    iso3           Country  Shifted profits outward (USD million)
1    DZA           Algeria                                   1655
2    AGO            Angola                                    601
3    BEN             Benin                                    211
4    BWA          Botswana                                     23
5    BFA      Burkina Faso                                      0
..   ...               ...                                    ...
194  PLW             Palau                                    107
195  PNG  Papua New Guinea                                    213
196  WSM             Samoa                                    249
197  SLB   Solomon Islands                                      1
198  VUT           Vanuatu                                     18

[192 rows x 3 columns]

In [92]:
# Check total profit shifting is equal to 1.19 trillion
pso_2021['Shifted profits outward (USD million)'].sum()

1186227

In [93]:
# Save dataset in intermediate folder
pso_2021.to_excel('../data/intermediate/profits_shifting_outward_2021.xlsx', index=False)