This notebook will check whether the increase in profit shiftings stem from the increase in company profits

In [59]:
import pandas as pd
import tjn_tools

In [60]:
# Retrieve profits shiftings outwards 2021 (2017 data) and 2022 (2018 data)
pso_2021 = pd.read_excel('../data/intermediate/profits_shifting_outward_2021.xlsx')
pso_2022 = pd.read_excel('../data/intermediate/profits_shifting_outward_2022.xlsx')
pso_2021

    iso3           Country  Shifted profits outward (USD million)
0    DZA           Algeria                                   1655
1    AGO            Angola                                    601
2    BEN             Benin                                    211
3    BWA          Botswana                                     23
4    BFA      Burkina Faso                                      0
..   ...               ...                                    ...
187  PLW             Palau                                    107
188  PNG  Papua New Guinea                                    213
189  WSM             Samoa                                    249
190  SLB   Solomon Islands                                      1
191  VUT           Vanuatu                                     18

[192 rows x 3 columns]

In [61]:
# Check Replicates values 2017 - Should sum up 4.7 billion
companies_profit_2017 = pd.read_csv('../data/raw/2017_replicates.csv', delimiter='\s+') 

# Keep only columns of interest
companies_profit_2017 = companies_profit_2017.loc[:,['iso3_d','iso3_o','profits']]
companies_profit_2017

        iso3_d iso3_o       profits
0          ARG    ARG  2.881636e+09
1          ARG    AUS  6.202941e+07
2          ARG    BMU  4.344638e+07
3          ARG    BRA  6.320611e+08
4          ARG    CHE  2.300156e+08
...        ...    ...           ...
2198995    GLP    GLP  0.000000e+00
2198996    GUF    MEX -2.022800e+05
2198997    GUF    GUF  0.000000e+00
2198998    HTI    MEX -1.846160e+06
2198999    HTI    HTI  0.000000e+00

[2199000 rows x 3 columns]

In [62]:
# Check Replicates values 2017 - Should sum up 4.7 billion
companies_profit_2018 = pd.read_csv('../data/raw/2018_replicates.csv', delimiter='\s+') 

# Keep only columns of interest
companies_profit_2018 = companies_profit_2018.loc[:,['iso3_d','iso3_o','profits']]
companies_profit_2018

        iso3_d iso3_o       profits
0          ARG    ARG  1.130656e+10
1          ARG    AUS  3.021018e+07
2          ARG    BMU  1.039692e+08
3          ARG    BRA  6.732973e+08
4          ARG    CHE  1.264322e+08
...        ...    ...           ...
2522995    SSD    SSD  0.000000e+00
2522996    TJK    ROU  2.461490e+06
2522997    TJK    TJK  0.000000e+00
2522998    TKM    SAU  0.000000e+00
2522999    TKM    TKM  0.000000e+00

[2523000 rows x 3 columns]

In [63]:
total_companies_profit_2017 = companies_profit_2017['profits'].sum()
total_companies_profit_2018 = companies_profit_2018['profits'].sum()
print('The total companies profit for 2017 is: ', total_companies_profit_2017)
print('The total companies profit for 2018 is: ', total_companies_profit_2018)
print(' The increase in benefits between 2017 and 2018 is: ',(total_companies_profit_2018*100)/total_companies_profit_2017 - 100 )

The total companies profit for 2017 is:  4727410014217711.0
The total companies profit for 2018 is:  6038665035823852.0
 The increase in benefits between 2017 and 2018 is:  27.737281464111092