## The State of Tax Justice: Estimate misalignment for 2019

- Author: Mario Cuenda García, based on Alison Schultz, based on Javier Garcia Bernado's work
- Created: 4 November 2024
- Last updated:

**Description**
- This notebook is the third out of three notebooks to estimate the tax losses caused by profit shifting by multinational enterprises (MNEs). The analysis used the misalignment method based on the country-by-country reports (CbCR) published by the OECD.
    - Details on the misalignment method and its background can be found here: https://www.sciencedirect.com/science/article/pii/S0305750X23003455. 
    - The working paper version is here: https://www.econstor.eu/bitstream/10419/286362/1/wp-2023-33.pdf 

- This notebook estimates profit misalignment based on different formulas. It uses the dataset **"data/final/cbcr_main.csv"** (for the estimation with imputed values) or the dataset **"data/final/cbcr_main_noimputation_allsubgroupsonly.csv"** (for the estimation without imputed values). 

**Outline**
1. Define misalignment
2. Calculate misalignment for sample with full information.
3. Calculate misalignment for samples with imputed data and aggregate results. 

**To dos before running this notebook**
- Run the notebooks 1_clean and 2_impute_missings. Note the requirements and instructions given in these notebooks.

**To dos in this notebook**

Change the formula to any required formula in each section and adapt the output name of the csvs. The formulas I have used are like follows, where sales refer to unrelated party revenues and assets to tangible assets excluding cash.

The order of the formula is as follow:

- formula_vars=['n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll", 'stated_capital' 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip']

    - SOTJ: 50% employees, 50% payroll

        - weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0]

    - Canadian formula: 50% employees, 50% sales

        - weights=[1/2, 1/2, 0, 0, 0, 0, 0, 0]

    - CCCTB: 1/6 employees, 1/6 payroll, 1/3 sales, 1/3 assets

        - weights=[1/6, 1/3, 1/3, 1/6, 0, 0, 0, 0]
        
    - Double-weighted sales: 1/4 employees, 1/2 sales, 1/4 assets

        - weights=[1/4, 1/2, 1/4, 0, 0, 0, 0, 0]

    - Three-factor: 1/3 employees, 1/3 sales, 1/3 assets

        - weights=[1/3, 1/3, 1/3, 0, 0, 0, 0, 0]

- Adjust the input path in 5.1 to the bootstrapped sample you use

## 0. Load packages

In [15]:
# Packages
import pandas as pd
import numpy as np
import tjn_tools
from config import *

# Show columns and select data format
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.0f}'.format

## Step 1. Generate the template datasets

### Step 1.1. Generate the dataset with Unique ISO parents

In [16]:
# Open the original dataset
iso_parents = pd.read_csv(f'{data_final}/cbcr_main_no_imputation_allsubgroupsonly.csv')

# Keep just the following columns: iso_parent and year
iso_parents = iso_parents[['iso_parent', 'year']]

# Keep every unique combination of iso_parent and year
iso_parents = iso_parents.drop_duplicates(subset=['iso_parent', 'year'])

# Sort by year, then iso_parent
iso_parents = iso_parents.sort_values(by=['year', 'iso_parent'])

# Filter by year
iso_parents_2016= iso_parents[iso_parents['year'] == 2016]
iso_parents_2017= iso_parents[iso_parents['year'] == 2017]
iso_parents_2018= iso_parents[iso_parents['year'] == 2018]
iso_parents_2019= iso_parents[iso_parents['year'] == 2019]
iso_parents_2020= iso_parents[iso_parents['year'] == 2020]
iso_parents_2021= iso_parents[iso_parents['year'] == 2021]

# OPTIONAL: Print the count of how many unique iso_partner values there are
print(iso_parents_2016['iso_parent'].nunique())
print(iso_parents_2017['iso_parent'].nunique())
print(iso_parents_2018['iso_parent'].nunique())
print(iso_parents_2019['iso_parent'].nunique())
print(iso_parents_2020['iso_parent'].nunique())
print(iso_parents_2021['iso_parent'].nunique())

iso_parents_2019

26
38
46
50
52
52

      iso_parent  year
153          ARG  2019
267          AUS  2019
763          AUT  2019
837          BEL  2019
1062         BMU  2019
1647         BRA  2019
1896         CAN  2019
1984         CHE  2019
2725         CHL  2019
2813         CHN  2019
3576         CYM  2019
4139         CZE  2019
4147         DEU  2019
4965         DNK  2019
5619         ESP  2019
6199         FIN  2019
6222         FRA  2019
6777         GBR  2019
6808         GRC  2019
7040         HKG  2019
7580         HUN  2019
7587         IDN  2019
7938         IMN  2019
7966         IND  2019
8500         IRL  2019
8512         ITA  2019
9165         JPN  2019
9955         KOR  2019
9980         LTU  2019
10011        LUX  2019
10587        LVA  2019
10661        MAC  2019
10675        MEX  2019
11214        MUS  2019
11234        MYS  2019
11396        NLD  2019
11426        NOR  2019
11699        NZL  2019
11707        PAN  2019
11868        PER  2019
12064        POL  2019
12085        PRT  2019
12230        ROU  2019
12826        SAU  2019
13200        SGP  2019
13379        SVN  2019
13409        SWE  2019
13455        TUR  2019
13600        USA  2019
14480        ZAF  2019

### Step 1.2. Generate the dataset with unique iso_partners

In [17]:
## Download the relevant dataset
iso_partners = pd.read_csv(f'{data_final}/cbcr_main_no_imputation_allsubgroupsonly.csv')

# Exclude country groups
iso_partners = iso_partners[~iso_partners['iso_partner'].isin(non_countries)]

# Keep just the following columns: iso_partner and year
iso_partners = iso_partners[['iso_partner', 'year']]

# Sort by year, then iso_partner
iso_partners = iso_partners.sort_values(by=['year', 'iso_partner'])

# Keep every unique combination of iso_partner and year
iso_partners = iso_partners.drop_duplicates(subset=['iso_partner', 'year'])

# Filter by year
iso_partners_2016= iso_partners[iso_partners['year'] == 2016]
iso_partners_2017= iso_partners[iso_partners['year'] == 2017]
iso_partners_2018= iso_partners[iso_partners['year'] == 2018]
iso_partners_2019= iso_partners[iso_partners['year'] == 2019]
iso_partners_2020= iso_partners[iso_partners['year'] == 2020]
iso_partners_2021= iso_partners[iso_partners['year'] == 2021]


# Optional: Print the count of how many unique iso_partner values there are 
print(iso_partners_2016['iso_partner'].nunique())
print(iso_partners_2017['iso_partner'].nunique())
print(iso_partners_2018['iso_partner'].nunique())
print(iso_partners_2019['iso_partner'].nunique())
print(iso_partners_2020['iso_partner'].nunique())
print(iso_partners_2021['iso_partner'].nunique())

183
215
213
210
212
211

### Step 1.3. Generate the template dataset

In [18]:
# Perform a cross join to merge all values of iso_partners_ with each value of iso_parents
iso_combinations_2016 = iso_parents_2016.assign(key=1).merge(iso_partners_2016.assign(key=1), on='key').drop('key', axis=1)
iso_combinations_2017 = iso_parents_2017.assign(key=1).merge(iso_partners_2017.assign(key=1), on='key').drop('key', axis=1)
iso_combinations_2018 = iso_parents_2018.assign(key=1).merge(iso_partners_2018.assign(key=1), on='key').drop('key', axis=1)
iso_combinations_2019 = iso_parents_2019.assign(key=1).merge(iso_partners_2019.assign(key=1), on='key').drop('key', axis=1)
iso_combinations_2020 = iso_parents_2020.assign(key=1).merge(iso_partners_2020.assign(key=1), on='key').drop('key', axis=1)
iso_combinations_2021 = iso_parents_2021.assign(key=1).merge(iso_partners_2021.assign(key=1), on='key').drop('key', axis=1)

# Concatenate all the years
template_dataset = pd.concat([iso_combinations_2016, iso_combinations_2017, iso_combinations_2018, iso_combinations_2019, iso_combinations_2020, iso_combinations_2021])

# Drop year_y
template_dataset = template_dataset.drop(columns=['year_y'])
# Rename year_x to year
template_dataset = template_dataset.rename(columns={'year_x': 'year'})
# Order columns by iso_parent then iso_partner then year
template_dataset = template_dataset[['iso_parent', 'iso_partner', 'year']]
# Generate new column called cbcr_estimates
template_dataset['cbcr_estimates'] = np.nan

template_dataset

      iso_parent iso_partner  year  cbcr_estimates
0            AUS         ABW  2016             NaN
1            AUS         AFG  2016             NaN
2            AUS         AGO  2016             NaN
3            AUS         ALB  2016             NaN
4            AUS         AND  2016             NaN
...          ...         ...   ...             ...
10967        ZAF         XKV  2021             NaN
10968        ZAF         YEM  2021             NaN
10969        ZAF         ZAF  2021             NaN
10970        ZAF         ZMB  2021             NaN
10971        ZAF         ZWE  2021             NaN

[55222 rows x 4 columns]

## Step 2. Define the misalignment formula

In [19]:
def calculate_misalignment(cbcr_data,
                           formula_vars=['n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",
                                         'stated_capital', 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip'],
                           weights=[.5, 0, 0, .5, 0, 0, 0, 0],
                           profit_var='profit_loss_before_income_tax_corrected',
                           etr_max=0.15): 

    # Create variable with positive profits only for calculating shares
    cbcr_data['profit_var_pos'] = cbcr_data[profit_var]
    cbcr_data.loc[cbcr_data[profit_var] < 0, 'profit_var_pos'] = 0
    cbcr_data['share_profit'] = cbcr_data['profit_var_pos'] / cbcr_data.groupby('iso_parent')['profit_var_pos'].transform('sum')

    # Calculate weighted shares of economic activity
    actual_weights = []
    actual_variables = []
    for i, var in enumerate(formula_vars):
        if var is not None and weights[i] > 0:
            actual_variables.append(f"share_{var}")
            actual_weights.append(weights[i])
            cbcr_data.loc[cbcr_data[var] < 0, var] = 0  # Set economic activity measure to zero if negative
            cbcr_data[f"share_{var}"] = cbcr_data[var] / cbcr_data.groupby('iso_parent')[var].transform('sum')

    # Calculate the share of economic activity
    cbcr_data["share_economy_partner_of_parent"] = (cbcr_data.loc[:, actual_variables] * actual_weights).sum(1, min_count=len(actual_weights))
    # Set economic activity to 1% for those jurisdictions without economic activity but with reported profits
    cbcr_data.loc[(cbcr_data["share_economy_partner_of_parent"] == 0) & (cbcr_data[profit_var] > 0), "share_economy_partner_of_parent"] = 0.01

    # Normalize the economic activity shares to sum to 1
    cbcr_data["share_economy_partner_of_parent"] = cbcr_data["share_economy_partner_of_parent"] / cbcr_data.groupby('iso_parent')["share_economy_partner_of_parent"].transform('sum')

    # Calculate theoretical profit and misaligned profit
    cbcr_data["theoretical_profit"] = cbcr_data["share_economy_partner_of_parent"] * cbcr_data.groupby('iso_parent')[profit_var].transform('sum')
    cbcr_data["misaligned_profit"] = cbcr_data[profit_var] - cbcr_data["theoretical_profit"]

    # Set positive misaligned profits to 0 if ETR exceeds the threshold (etr_max)
    cbcr_data.loc[((cbcr_data["misaligned_profit"] > 0) & (cbcr_data["etr_average_corrected"] > etr_max)), "misaligned_profit"] = 0

    # Adjust misalignment per 'iso_parent'
    def adjust_misalignment(group):
        total_negative_misalignment = group.loc[group["misaligned_profit"] < 0, "misaligned_profit"].sum()
        total_positive_misalignment = group.loc[group["misaligned_profit"] > 0, "misaligned_profit"].sum()
        
        # Adjust negative misalignments to balance positive misalignments within each 'iso_parent'
        if total_negative_misalignment != 0:
            factor = - total_positive_misalignment / total_negative_misalignment
            group.loc[group["misaligned_profit"] < 0, "misaligned_profit"] *= factor
        
        return group

    # Apply the adjustment by grouping by 'iso_parent'
    cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

    return cbcr_data

## Step 3. Calculate misalignment for sample with full information

### Step 3.1 Import data
- Import data without imputed values. This is only the data from the sample of reporting countries that actually is reported on a country basis, i.e. excluding aggregated country groups and data from reporting countries that do not report on a country by country basis, but just by continents.

In [20]:
cbcr_sample = pd.read_csv(f'{data_final}/cbcr_main_no_imputation_allsubgroupsonly.csv')

# Exclude country groups
cbcr_sample = cbcr_sample[~cbcr_sample['iso_partner'].isin(non_countries)]

### Step 3.2 Exclude countries that do not report truly country-by-country


- In the 2024 data, the following reporting countries do not report country-by-country. We exclude those from the "clean" analysis where we only use values that are actually in the data.
    - Austria: Only continents in all years
    - Czechia: Only Czechia versus rest of the world from 2019 to 2021
    - Finland: Only Finland and rest of the world between 2016 and 2018 and Finland and continents between 2019 and 2021
    - Greece: Only Greece and continents between 2017 and 2019
    - Hungary: Only Hungary versus rest of the world between 2018 and 2021
    - Isle of Man: Only continents between 2017 and 2020
    - Ireland: Only Ireland versus rest of the world in all years
    - Korea: Only Korea and rest of the world betweem 2016 and 2018 and Korea and continents between 2019 and 2021
    - Macau: Only Macau versus rest of the world between 2019 and 2021
    - Mauritius: Only Mauritius and continents between 2019 and 2021
    - Morocco: Only Morocco and continents in 2021
    - Netherlands: Only Netherlands versus rest of the world between 2016 and 2017
    - Norway: Only Norway and continents 2016 and 2017
    - New Zealand: Only New Zealand versus rest of the world between 2018 and 2021
    - Poland: Only Poland and continents 2019 to 2021
    - Sweden: Only Sweden and continents in all years
    - United Kingdom: Only UK and continents between 2017 and 2021

In [21]:
# Define the conditions for exclusion
exclusion_conditions = [
    ('AUT', 2016, 2021),                # Austria: all years
    ('CZE', 2019, 2021),                # Czechia: from 2019 to 2021
    ('FIN', 2016, 2021),                # Finland: all years
    ('GRC', 2017, 2019),                # Greece: between 2017 and 2019
    ('HUN', 2018, 2021),                # Hungary: between 2018 and 2021
    ('IMN', 2017, 2020),                # Isle of Man: between 2017 and 2020
    ('IRL', 2016, 2021),                # Ireland: all years
    ('KOR', 2016, 2021),                # Korea: all years
    ('MAC', 2019, 2021),                # Macau: between 2019 and 2021
    ('MUS', 2019, 2021),                # Mauritius: between 2019 and 2021
    ('MAR', 2021, 2021),                # Morocco: 2021
    ('NLD', 2016, 2017),                # Netherlands: between 2016 and 2017
    ('NOR', 2016, 2017),                # Norway: 2016 and 2017
    ('NZL', 2018, 2021),                # New Zealand: between 2018 and 2021
    ('POL', 2019, 2021),                # Poland: 2019 to 2021
    ('SWE', 2016, 2021),                # Sweden: all years
    ('GBR', 2017, 2021)                 # United Kingdom: between 2017 and 2021
]

# Iterate through the exclusion conditions
for iso_parent, start_year, end_year in exclusion_conditions:
    cbcr_sample = cbcr_sample[~((cbcr_sample['iso_parent'] == iso_parent) & 
                                     (cbcr_sample['year'].between(start_year, end_year)))]

### Step 3.3 Calculate misalignment for sample countries with full information

The order of the formula is as follow:

- formula_vars=['n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll", 'stated_capital' 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip']

    - SOTJ: 50% employees, 50% payroll

        - weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0]

    - Canadian formula: 50% employees, 50% sales

        - weights=[1/2, 1/2, 0, 0, 0, 0, 0, 0]

    - CCCTB: 1/6 employees, 1/6 payroll, 1/3 sales, 1/3 assets

        - weights=[1/6, 1/3, 1/3, 1/6, 0, 0, 0, 0]
        
    - Double-weighted sales: 1/4 employees, 1/2 sales, 1/4 assets

        - weights=[1/4, 1/2, 1/4, 0, 0, 0, 0, 0]

    - Three-factor: 1/3 employees, 1/3 sales, 1/3 assets

        - weights=[1/3, 1/3, 1/3, 0, 0, 0, 0, 0]


The end of this cell shows, among other things, the misaligned profits and the theoretical profits, as well as the CBCR variables.

**More importantly, if for whatever reason we wanted to just run this cell without the "bad reporters", we could just modify the cell to run like the cell from Step 5.2. in order to obtain a dataset of profit shifting without the "bad reporters". In a way, this cell is not really necessary for the rest of the notebook. It just shows an intermediary steps if we want to calculate the misalignment for the "good reporters" only.**

In [22]:
misalignment_2019 = cbcr_sample[cbcr_sample['year'] == 2019].copy()
misalignment_2019 = calculate_misalignment(misalignment_2019, etr_max=0.15, weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0])

# Keep only the first occurrence of these unique variables for each 'iso_partner'
unique_columns = misalignment_2019.drop_duplicates(subset=['iso_partner'])[['iso_partner', 'partner_jurisdiction', 
                                                                               'etr_average_corrected', 'cit',
                                                                               'tax_revenue_current_usd', 
                                                                               'gvt_health_expenditure', 'region_tjn', 
                                                                               'ukt', 'oecd', 'oecd_oct', 'nld_oct']]

# Keep iso_parent, iso_partner, year, misaligned_profit, theoretical_profit, profit_loss_before_income_tax_corrected, 'n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",'stated_capital', 'total_revenues', 'related_party_revenues', and 'holding_or_managing_ip'
misalignment_2019 = misalignment_2019[['iso_parent', 'iso_partner', 'year', 'misaligned_profit', 'theoretical_profit', 'profit_loss_before_income_tax_corrected', 'n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",'stated_capital', 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip']]

# Show if iso_partner = USA
misalignment_2019[misalignment_2019['iso_partner'] == 'USA']

/var/folders/pm/bp4z4lln39xcwn73chrtp3n00000gn/T/ipykernel_6423/421381151.py:51: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

,iso_parent,iso_partner,year,misaligned_profit,theoretical_profit,profit_loss_before_income_tax_corrected,n_employees,unrelated_party_revenues,tangible_assets_except_cash,payroll,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip
15,ARG,USA,2019,0,"-5,802,608","181,774,425",172,"360,002,944","1,709,709,185","8,737,087","1,611,489,867","380,612,773","20,609,830",0
90,AUS,USA,2019,"-1,193,161,484","5,229,936,837","3,446,318,835","90,483","45,060,586,867","35,884,418,881","4,596,266,761","142,842,000,000","64,543,875,904","19,483,289,037",21
116,BEL,USA,2019,"-25,579,169,157","26,726,269,157","1,147,100,000","60,400","38,985,700,000","15,954,000,000","3,068,140,008","65,191,100,000","49,126,500,000","10,140,800,000",22
211,BMU,USA,2019,"-370,913,937","5,942,394,792","5,261,472,357","123,442","76,520,956,341","53,230,845,962","6,270,485,743","87,178,568,755","90,819,277,063","14,298,320,722",22
250,BRA,USA,2019,"-1,892,674,949","11,571,295,652","6,652,364,941","122,779","60,343,739,039","22,248,121,267","6,236,807,319","38,439,013,015","78,134,721,511","17,790,982,472",4
263,CAN,USA,2019,"-4,253,408,506","76,653,970,506","72,400,562,000","630,580","419,710,000,000","473,721,000,000","32,031,584,872","1,100,520,000,000","511,869,000,000","92,158,921,000",NaN
414,CHE,USA,2019,"-6,102,719,181","24,187,979,255","16,795,690,714","330,522","265,678,000,000","86,578,051,774","16,789,532,644","399,132,000,000","327,422,000,000","61,743,847,053",82
435,CHL,USA,2019,"-16,105,815","340,034,526","233,934,111","7,051","5,363,699,184","2,022,810,696","358,169,788","3,394,198,472","5,581,580,603","217,881,419",0
559,CHN,USA,2019,"-7,073,548,564","13,957,386,530","4,323,736,477","85,724","101,597,000,000","59,120,703,102","4,354,523,742","70,856,997,677","129,675,000,000","28,235,223,172",85
698,CYM,USA,2019,"-4,767,313,692","7,916,057,406","-203,317,143","57,366","23,448,117,036","8,255,585,218","2,914,021,849","21,412,055,469","30,214,374,199","6,766,257,163",35
854,DEU,USA,2019,"-9,688,860,770","23,880,100,237","11,533,415,000","653,669","465,631,000,000","258,503,000,000","33,204,437,266","418,340,000,000","599,660,000,000","132,124,000,000",229
957,DNK,USA,2019,"-2,807,159,142","4,295,491,738","1,460,057,520","70,600","34,434,475,483","18,039,885,539","3,586,269,612","19,593,760,883","46,139,504,565","11,705,029,082",19
1070,ESP,USA,2019,"-912,316,733","5,353,201,213","2,928,144,755","123,876","68,584,362,119","76,487,214,348","6,292,531,650","77,661,484,845","81,569,475,243","12,985,113,124",35
1157,FRA,USA,2019,"-2,276,903,866","18,898,875,624","15,115,840,379","568,998","281,826,000,000","79,899,284,248","28,903,402,786","217,693,000,000","355,067,000,000","73,243,918,786",249
1290,HKG,USA,2019,"-7,417,226,336","8,079,930,046","87,647,334","64,440","30,920,814,739","14,373,173,164","3,273,359,969","32,499,091,031","52,062,035,186","21,141,220,447",35
1362,IDN,USA,2019,"-994,011,761","1,126,054,497","117,635,828","3,411","1,132,425,345","343,342,152","173,268,635","2,541,754,161","1,548,061,161","415,635,816",14
1451,IND,USA,2019,"-317,332,138","5,857,079,975","155,987,874","105,083","36,465,390,278","7,945,693,374","5,337,903,253","21,718,480,249","41,516,823,970","5,051,433,692",43
1558,ITA,USA,2019,"-1,622,300,915","5,435,486,580","2,022,873,172","77,213","32,212,083,530","20,754,201,381","3,922,190,305","35,604,498,963","38,310,468,818","6,030,827,348",31
1689,JPN,USA,2019,"-6,738,290,818","66,060,517,186","32,723,046,652","1,199,212","781,710,000,000","324,389,000,000","60,916,395,948","515,709,000,000","1,095,330,000,000","313,625,000,000",350
1791,LUX,USA,2019,"-3,231,757,650","3,332,746,910","-388,323,742","126,731","147,468,000,000","29,209,474,931","6,437,557,142","76,013,094,082","178,176,000,000","30,708,180,618",63
1891,MEX,USA,2019,"-280,984,053","5,043,410,403","1,448,745,821","61,886","30,395,613,881","17,242,712,380","3,143,624,380","18,378,739,182","34,904,470,549","4,508,856,668",11
1917,MYS,USA,2019,"-22,016,798","285,088,786","-26,428,881","2,012","1,476,338,968","4,715,069,626","102,203,604","3,821,127,859","1,636,871,607","160,532,640",4
1981,NOR,USA,2019,"-284,678,901","1,931,539,901","-2,629,293,000","17,940","20,498,901,000","17,233,378,000","911,298,539","98,404,944,000","30,658,253,000","10,159,351,000",4
2032,PAN,USA,2019,0,"13,648,631","14,913,304",311,"1,169,220,337","221,011,043","15,797,873","12,901,462","1,170,739,499","1,519,162",NaN
2047,PER,USA,2019,"-2,651,719","3,335,787","570,581",27,"4,264,592","326,086","1,371,520","655,967","17,400,773","13,136,181",NaN
2081,PRT,USA,2019,"-245,458,210","313,968,136","68,073,504","1,901","1,770,878,807","8,820,564,814","96,565,135","19,513,746,680","1,984,679,979","213,801,174",14
2220,ROU,USA,2019,"-34,070,917","174,449,734","31,204,614",485,"139,693,194","93,819,342","24,636,555","13,063,984","605,595,161","465,901,967",0
2320,SAU,USA,2019,"-17,897,138","4,400,329,079","66,778,416","7,300","35,278,588,214","15,329,077,477","370,818,246","25,186,197,289","43,736,513,829","8,457,925,615",2
2347,SGP,USA,2019,"-1,466,660,368","2,077,201,465","427,032,012","22,887","26,593,262,791","14,878,271,001","1,162,591,397","16,007,852,429","38,699,174,813","12,105,912,024",9
2406,TUR,USA,2019,"-93,410,281","279,382,477","-313,063,884","4,778","1,304,724,201","696,397,385","242,708,162","3,180,813,472","1,778,962,760","474,238,559",1
2541,USA,USA,2019,"-216,458,172,073","570,239,716,522","336,856,000,000","23,958,116","11,679,700,000,000","5,871,940,000,000","1,217,000,897,614","15,339,900,000,000","15,176,400,000,000","3,496,630,000,000",NaN
2568,ZAF,USA,2019,0,"196,373,851","395,534,080","3,749","3,478,661,084","618,337,112","190,438,028","10,290,072,958","3,652,526,352","173,865,269",2

## Step 4. Generate the dataset for the "bad reporters"

For the "bad" reporters, we are going to assume that their MNEs behave like the "average" MNE in the countries that report correctly. To do that we need to:

1. First aggregate the variables reported by the CBCR by partner countries. For instance, we see that on aggregate, there are 80m employees reported.
2. Then we look at the share corresponding by partners. For instance, 18m employees are reported in the USA. how many does the USA have. In short, roughly 24% of all employees reported are in the USA.
3. We then assume that 24% of the toal employees reported by the "bad" reporters are assigned to the US. And we repeat with all of them



### Step 4.1. Generate the Total Sums of Variables, and the Total Sums by Partners.

- The first bloc of lines calculates the total of the variables, and generates a new variable (e.g. total_n_employees) in the dataset.
- The second bloc of lines groups by iso_partner and calculates the total sums by partners. (e.g. how many employees are reported by the CBCR countries, say, in the USA)
- The third bloc of lines merges the total sums by partners to the dataset

In [23]:
# Calculate the total sum of profit_loss_before_income_tax_corrected, 'n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",'stated_capital', 'total_revenues', 'related_party_revenues', and 'holding_or_managing_ip'
total_profit_loss_before_income_tax_corrected = misalignment_2019['profit_loss_before_income_tax_corrected'].sum()
total_n_employees = misalignment_2019['n_employees'].sum()
total_unrelated_party_revenues = misalignment_2019['unrelated_party_revenues'].sum()
total_tangible_assets_except_cash = misalignment_2019['tangible_assets_except_cash'].sum()
total_payroll = misalignment_2019['payroll'].sum()
total_stated_capital = misalignment_2019['stated_capital'].sum()
total_total_revenues = misalignment_2019['total_revenues'].sum()
total_related_party_revenues = misalignment_2019['related_party_revenues'].sum()
total_holding_or_managing_ip = misalignment_2019['holding_or_managing_ip'].sum()

misalignment_2019['total_profit_loss_before_income_tax_corrected'] = total_profit_loss_before_income_tax_corrected
misalignment_2019['total_n_employees'] = total_n_employees
misalignment_2019['total_unrelated_party_revenues'] = total_unrelated_party_revenues
misalignment_2019['total_tangible_assets_except_cash'] = total_tangible_assets_except_cash
misalignment_2019['total_payroll'] = total_payroll
misalignment_2019['total_stated_capital'] = total_stated_capital
misalignment_2019['total_total_revenues'] = total_total_revenues
misalignment_2019['total_related_party_revenues'] = total_related_party_revenues
misalignment_2019['total_holding_or_managing_ip'] = total_holding_or_managing_ip

# Group by iso_partner and calculate the total sum of profit_loss_before_income_tax_corrected, 'n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",'stated_capital', 'total_revenues', 'related_party_revenues', and 'holding_or_managing_ip'
total_profit_loss_by_partner = misalignment_2019.groupby('iso_partner')['profit_loss_before_income_tax_corrected'].sum().reset_index()
total_profit_loss_by_partner = total_profit_loss_by_partner.rename(columns={'profit_loss_before_income_tax_corrected': 'total_profit_loss_by_partner'})

total_n_employees_by_partner = misalignment_2019.groupby('iso_partner')['n_employees'].sum().reset_index()
total_n_employees_by_partner = total_n_employees_by_partner.rename(columns={'n_employees': 'total_n_employees_by_partner'})

total_unrelated_party_revenues_by_partner = misalignment_2019.groupby('iso_partner')['unrelated_party_revenues'].sum().reset_index()
total_unrelated_party_revenues_by_partner = total_unrelated_party_revenues_by_partner.rename(columns={'unrelated_party_revenues': 'total_unrelated_party_revenues_by_partner'})

total_tangible_assets_except_cash_by_partner = misalignment_2019.groupby('iso_partner')['tangible_assets_except_cash'].sum().reset_index()
total_tangible_assets_except_cash_by_partner = total_tangible_assets_except_cash_by_partner.rename(columns={'tangible_assets_except_cash': 'total_tangible_assets_except_cash_by_partner'})

total_payroll_by_partner = misalignment_2019.groupby('iso_partner')['payroll'].sum().reset_index()
total_payroll_by_partner = total_payroll_by_partner.rename(columns={'payroll': 'total_payroll_by_partner'})

total_stated_capital_by_partner = misalignment_2019.groupby('iso_partner')['stated_capital'].sum().reset_index()
total_stated_capital_by_partner = total_stated_capital_by_partner.rename(columns={'stated_capital': 'total_stated_capital_by_partner'})

total_total_revenues_by_partner = misalignment_2019.groupby('iso_partner')['total_revenues'].sum().reset_index()
total_total_revenues_by_partner = total_total_revenues_by_partner.rename(columns={'total_revenues': 'total_total_revenues_by_partner'})

total_related_party_revenues_by_partner = misalignment_2019.groupby('iso_partner')['related_party_revenues'].sum().reset_index()
total_related_party_revenues_by_partner = total_related_party_revenues_by_partner.rename(columns={'related_party_revenues': 'total_related_party_revenues_by_partner'})

total_holding_or_managing_ip_by_partner = misalignment_2019.groupby('iso_partner')['holding_or_managing_ip'].sum().reset_index()
total_holding_or_managing_ip_by_partner = total_holding_or_managing_ip_by_partner.rename(columns={'holding_or_managing_ip': 'total_holding_or_managing_ip_by_partner'})

# Merge the total profit loss by partner back into the misalignment_2019 dataframe
misalignment_2019 = misalignment_2019.merge(total_profit_loss_by_partner, on='iso_partner', how='left')
misalignment_2019 = misalignment_2019.merge(total_n_employees_by_partner, on='iso_partner', how='left')
misalignment_2019 = misalignment_2019.merge(total_unrelated_party_revenues_by_partner, on='iso_partner', how='left')
misalignment_2019 = misalignment_2019.merge(total_tangible_assets_except_cash_by_partner, on='iso_partner', how='left')
misalignment_2019 = misalignment_2019.merge(total_payroll_by_partner, on='iso_partner', how='left')
misalignment_2019 = misalignment_2019.merge(total_stated_capital_by_partner, on='iso_partner', how='left')
misalignment_2019 = misalignment_2019.merge(total_total_revenues_by_partner, on='iso_partner', how='left')
misalignment_2019 = misalignment_2019.merge(total_related_party_revenues_by_partner, on='iso_partner', how='left')
misalignment_2019 = misalignment_2019.merge(total_holding_or_managing_ip_by_partner, on='iso_partner', how='left')

misalignment_2019[misalignment_2019['iso_partner'] == 'USA']

,iso_parent,iso_partner,year,misaligned_profit,theoretical_profit,profit_loss_before_income_tax_corrected,n_employees,unrelated_party_revenues,tangible_assets_except_cash,payroll,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip,total_profit_loss_before_income_tax_corrected,total_n_employees,total_unrelated_party_revenues,total_tangible_assets_except_cash,total_payroll,total_stated_capital,total_total_revenues,total_related_party_revenues,total_holding_or_managing_ip,total_profit_loss_by_partner,total_n_employees_by_partner,total_unrelated_party_revenues_by_partner,total_tangible_assets_except_cash_by_partner,total_payroll_by_partner,total_stated_capital_by_partner,total_total_revenues_by_partner,total_related_party_revenues_by_partner,total_holding_or_managing_ip_by_partner
15,ARG,USA,2019,0,"-5,802,608","181,774,425",172,"360,002,944","1,709,709,185","8,737,087","1,611,489,867","380,612,773","20,609,830",0,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
90,AUS,USA,2019,"-1,193,161,484","5,229,936,837","3,446,318,835","90,483","45,060,586,867","35,884,418,881","4,596,266,761","142,842,000,000","64,543,875,904","19,483,289,037",21,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
116,BEL,USA,2019,"-25,579,169,157","26,726,269,157","1,147,100,000","60,400","38,985,700,000","15,954,000,000","3,068,140,008","65,191,100,000","49,126,500,000","10,140,800,000",22,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
211,BMU,USA,2019,"-370,913,937","5,942,394,792","5,261,472,357","123,442","76,520,956,341","53,230,845,962","6,270,485,743","87,178,568,755","90,819,277,063","14,298,320,722",22,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
250,BRA,USA,2019,"-1,892,674,949","11,571,295,652","6,652,364,941","122,779","60,343,739,039","22,248,121,267","6,236,807,319","38,439,013,015","78,134,721,511","17,790,982,472",4,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
263,CAN,USA,2019,"-4,253,408,506","76,653,970,506","72,400,562,000","630,580","419,710,000,000","473,721,000,000","32,031,584,872","1,100,520,000,000","511,869,000,000","92,158,921,000",NaN,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
414,CHE,USA,2019,"-6,102,719,181","24,187,979,255","16,795,690,714","330,522","265,678,000,000","86,578,051,774","16,789,532,644","399,132,000,000","327,422,000,000","61,743,847,053",82,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
435,CHL,USA,2019,"-16,105,815","340,034,526","233,934,111","7,051","5,363,699,184","2,022,810,696","358,169,788","3,394,198,472","5,581,580,603","217,881,419",0,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
559,CHN,USA,2019,"-7,073,548,564","13,957,386,530","4,323,736,477","85,724","101,597,000,000","59,120,703,102","4,354,523,742","70,856,997,677","129,675,000,000","28,235,223,172",85,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
698,CYM,USA,2019,"-4,767,313,692","7,916,057,406","-203,317,143","57,366","23,448,117,036","8,255,585,218","2,914,021,849","21,412,055,469","30,214,374,199","6,766,257,163",35,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
854,DEU,USA,2019,"-9,688,860,770","23,880,100,237","11,533,415,000","653,669","465,631,000,000","258,503,000,000","33,204,437,266","418,340,000,000","599,660,000,000","132,124,000,000",229,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
957,DNK,USA,2019,"-2,807,159,142","4,295,491,738","1,460,057,520","70,600","34,434,475,483","18,039,885,539","3,586,269,612","19,593,760,883","46,139,504,565","11,705,029,082",19,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
1070,ESP,USA,2019,"-912,316,733","5,353,201,213","2,928,144,755","123,876","68,584,362,119","76,487,214,348","6,292,531,650","77,661,484,845","81,569,475,243","12,985,113,124",35,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
1157,FRA,USA,2019,"-2,276,903,866","18,898,875,624","15,115,840,379","568,998","281,826,000,000","79,899,284,248","28,903,402,786","217,693,000,000","355,067,000,000","73,243,918,786",249,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
1290,HKG,USA,2019,"-7,417,226,336","8,079,930,046","87,647,334","64,440","30,920,814,739","14,373,173,164","3,273,359,969","32,499,091,031","52,062,035,186","21,141,220,447",35,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
1362,IDN,USA,2019,"-994,011,761","1,126,054,497","117,635,828","3,411","1,132,425,345","343,342,152","173,268,635","2,541,754,161","1,548,061,161","415,635,816",14,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
1451,IND,USA,2019,"-317,332,138","5,857,079,975","155,987,874","105,083","36,465,390,278","7,945,693,374","5,337,903,253","21,718,480,249","41,516,823,970","5,051,433,692",43,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
1558,ITA,USA,2019,"-1,622,300,915","5,435,486,580","2,022,873,172","77,213","32,212,083,530","20,754,201,381","3,922,190,305","35,604,498,963","38,310,468,818","6,030,827,348",31,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
1689,JPN,USA,2019,"-6,738,290,818","66,060,517,186","32,723,046,652","1,199,212","781,710,000,000","324,389,000,000","60,916,395,948","515,709,000,000","1,095,330,000,000","313,625,000,000",350,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
1791,LUX,USA,2019,"-3,231,757,650","3,332,746,910","-388,323,742","126,731","147,468,000,000","29,209,474,931","6,437,557,142","76,013,094,082","178,176,000,000","30,708,180,618",63,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
1891,MEX,USA,2019,"-280,984,053","5,043,410,403","1,448,745,821","61,886","30,395,613,881","17,242,712,380","3,143,624,380","18,378,739,182","34,904,470,549","4,508,856,668",11,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
1917,MYS,USA,2019,"-22,016,798","285,088,786","-26,428,881","2,012","1,476,338,968","4,715,069,626","102,203,604","3,821,127,859","1,636,871,607","160,532,640",4,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
1981,NOR,USA,2019,"-284,678,901","1,931,539,901","-2,629,293,000","17,940","20,498,901,000","17,233,378,000","911,298,539","98,404,944,000","30,658,253,000","10,159,351,000",4,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
2032,PAN,USA,2019,0,"13,648,631","14,913,304",311,"1,169,220,337","221,011,043","15,797,873","12,901,462","1,170,739,499","1,519,162",NaN,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
2047,PER,USA,2019,"-2,651,719","3,335,787","570,581",27,"4,264,592","326,086","1,371,520","655,967","17,400,773","13,136,181",NaN,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
2081,PRT,USA,2019,"-245,458,210","313,968,136","68,073,504","1,901","1,770,878,807","8,820,564,814","96,565,135","19,513,746,680","1,984,679,979","213,801,174",14,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
2220,ROU,USA,2019,"-34,070,917","174,449,734","31,204,614",485,"139,693,194","93,819,342","24,636,555","13,063,984","605,595,161","465,901,967",0,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
2320,SAU,USA,2019,"-17,897,138","4,400,329,079","66,778,416","7,300","35,278,588,214","15,329,077,477","370,818,246","25,186,197,289","43,736,513,829","8,457,925,615",2,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
2347,SGP,USA,2019,"-1,466,660,368","2,077,201,465","427,032,012","22,887","26,593,262,791","14,878,271,001","1,162,591,397","16,007,852,429","38,699,174,813","12,105,912,024",9,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
2406,TUR,USA,2019,"-93,410,281","279,382,477","-313,063,884","4,778","1,304,724,201","696,397,385","242,708,162","3,180,813,472","1,778,962,760","474,238,559",1,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
2541,USA,USA,2019,"-216,458,172,073","570,239,716,522","336,856,000,000","23,958,116","11,679,700,000,000","5,871,940,000,000","1,217,000,897,614","15,339,900,000,000","15,176,400,000,000","3,496,630,000,000",NaN,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"
2568,ZAF,USA,2019,0,"196,373,851","395,534,080","3,749","3,478,661,084","618,337,112","190,438,028","10,290,072,958","3,652,526,352","173,865,269",2,"5,252,345,950,571","138,818,542","51,656,500,864,631","34,559,985,418,529","3,580,814,046,076","59,293,915,820,799","72,742,547,231,696","21,064,699,384,324","17,102","512,336,028,057","28,583,144","14,719,262,499,974","7,540,458,479,488","1,451,938,537,431","18,882,661,702,751","19,112,391,499,318","4,391,251,531,039","1,386"

### Step 4.2. Calculate the shares for all the variables

In [24]:
# Final Misalignment
final_misalignment_2019 = misalignment_2019

# Calculate the shares for all variables
final_misalignment_2019['share_reported_total_profit_loss_by_partner'] = misalignment_2019['total_profit_loss_by_partner'] / misalignment_2019['total_profit_loss_before_income_tax_corrected']
final_misalignment_2019['share_reported_total_n_employees_by_partner'] = misalignment_2019['total_n_employees_by_partner'] / misalignment_2019['total_n_employees']
final_misalignment_2019['share_reported_total_unrelated_party_revenues_by_partner'] = misalignment_2019['total_unrelated_party_revenues_by_partner'] / misalignment_2019['total_unrelated_party_revenues']
final_misalignment_2019['share_reported_total_tangible_assets_except_cash_by_partner'] = misalignment_2019['total_tangible_assets_except_cash_by_partner'] / misalignment_2019['total_tangible_assets_except_cash']
final_misalignment_2019['share_reported_total_payroll_by_partner'] = misalignment_2019['total_payroll_by_partner'] / misalignment_2019['total_payroll']
final_misalignment_2019['share_reported_total_stated_capital_by_partner'] = misalignment_2019['total_stated_capital_by_partner'] / misalignment_2019['total_stated_capital']
final_misalignment_2019['share_reported_total_total_revenues_by_partner'] = misalignment_2019['total_total_revenues_by_partner'] / misalignment_2019['total_total_revenues']
final_misalignment_2019['share_reported_total_related_party_revenues_by_partner'] = misalignment_2019['total_related_party_revenues_by_partner'] / misalignment_2019['total_related_party_revenues']
final_misalignment_2019['share_reported_total_holding_or_managing_ip_by_partner'] = misalignment_2019['total_holding_or_managing_ip_by_partner'] / misalignment_2019['total_holding_or_managing_ip']

# Give me column 'share reported' with 2 decimals
pd.options.display.float_format = '{:,.2f}'.format

final_misalignment_2019[final_misalignment_2019['iso_partner'] == 'USA']

,iso_parent,iso_partner,year,misaligned_profit,theoretical_profit,profit_loss_before_income_tax_corrected,n_employees,unrelated_party_revenues,tangible_assets_except_cash,payroll,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip,total_profit_loss_before_income_tax_corrected,total_n_employees,total_unrelated_party_revenues,total_tangible_assets_except_cash,total_payroll,total_stated_capital,total_total_revenues,total_related_party_revenues,total_holding_or_managing_ip,total_profit_loss_by_partner,total_n_employees_by_partner,total_unrelated_party_revenues_by_partner,total_tangible_assets_except_cash_by_partner,total_payroll_by_partner,total_stated_capital_by_partner,total_total_revenues_by_partner,total_related_party_revenues_by_partner,total_holding_or_managing_ip_by_partner,share_reported_total_profit_loss_by_partner,share_reported_total_n_employees_by_partner,share_reported_total_unrelated_party_revenues_by_partner,share_reported_total_tangible_assets_except_cash_by_partner,share_reported_total_payroll_by_partner,share_reported_total_stated_capital_by_partner,share_reported_total_total_revenues_by_partner,share_reported_total_related_party_revenues_by_partner,share_reported_total_holding_or_managing_ip_by_partner
15,ARG,USA,2019,0.00,"-5,802,608.29","181,774,425.20",172.00,"360,002,943.70","1,709,709,185.00","8,737,087.44","1,611,489,867.00","380,612,773.30","20,609,829.55",0.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
90,AUS,USA,2019,"-1,193,161,483.53","5,229,936,837.11","3,446,318,835.00","90,483.00","45,060,586,867.00","35,884,418,881.00","4,596,266,760.66","142,842,000,000.00","64,543,875,904.00","19,483,289,037.00",21.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
116,BEL,USA,2019,"-25,579,169,156.77","26,726,269,156.77","1,147,100,000.00","60,400.00","38,985,700,000.00","15,954,000,000.00","3,068,140,008.00","65,191,100,000.00","49,126,500,000.00","10,140,800,000.00",22.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
211,BMU,USA,2019,"-370,913,936.94","5,942,394,792.47","5,261,472,357.00","123,442.00","76,520,956,341.00","53,230,845,962.00","6,270,485,742.84","87,178,568,755.00","90,819,277,063.00","14,298,320,722.00",22.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
250,BRA,USA,2019,"-1,892,674,949.09","11,571,295,651.74","6,652,364,941.00","122,779.00","60,343,739,039.00","22,248,121,267.00","6,236,807,318.58","38,439,013,015.00","78,134,721,511.00","17,790,982,472.00",4.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
263,CAN,USA,2019,"-4,253,408,506.19","76,653,970,506.19","72,400,562,000.00","630,580.00","419,710,000,000.00","473,721,000,000.00","32,031,584,871.60","1,100,520,000,000.00","511,869,000,000.00","92,158,921,000.00",NaN,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
414,CHE,USA,2019,"-6,102,719,181.12","24,187,979,254.77","16,795,690,714.00","330,522.00","265,678,000,000.00","86,578,051,774.00","16,789,532,644.44","399,132,000,000.00","327,422,000,000.00","61,743,847,053.00",82.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
435,CHL,USA,2019,"-16,105,814.95","340,034,526.08","233,934,111.00","7,051.00","5,363,699,184.00","2,022,810,696.00","358,169,788.02","3,394,198,472.00","5,581,580,603.00","217,881,419.00",0.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
559,CHN,USA,2019,"-7,073,548,564.08","13,957,386,529.93","4,323,736,477.00","85,724.00","101,597,000,000.00","59,120,703,102.00","4,354,523,742.48","70,856,997,677.00","129,675,000,000.00","28,235,223,172.00",85.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
698,CYM,USA,2019,"-4,767,313,691.85","7,916,057,405.78","-203,317,143.00","57,366.00","23,448,117,036.00","8,255,585,218.00","2,914,021,849.32","21,412,055,469.00","30,214,374,199.00","6,766,257,163.00",35.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
854,DEU,USA,2019,"-9,688,860,770.06","23,880,100,237.11","11,533,415,000.00","653,669.00","465,631,000,000.00","258,503,000,000.00","33,204,437,266.38","418,340,000,000.00","599,660,000,000.00","132,124,000,000.00",229.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
957,DNK,USA,2019,"-2,807,159,142.01","4,295,491,737.76","1,460,057,520.00","70,600.00","34,434,475,483.00","18,039,885,539.00","3,586,269,612.00","19,593,760,883.00","46,139,504,565.00","11,705,029,082.00",19.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
1070,ESP,USA,2019,"-912,316,732.99","5,353,201,213.37","2,928,144,755.00","123,876.00","68,584,362,119.00","76,487,214,348.00","6,292,531,649.52","77,661,484,845.00","81,569,475,243.00","12,985,113,124.00",35.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
1157,FRA,USA,2019,"-2,276,903,866.24","18,898,875,623.56","15,115,840,379.00","568,998.00","281,826,000,000.00","79,899,284,248.00","28,903,402,785.96","217,693,000,000.00","355,067,000,000.00","73,243,918,786.00",249.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
1290,HKG,USA,2019,"-7,417,226,336.28","8,079,930,045.71","87,647,334.00","64,440.00","30,920,814,739.00","14,373,173,164.00","3,273,359,968.80","32,499,091,031.00","52,062,035,186.00","21,141,220,447.00",35.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
1362,IDN,USA,2019,"-994,011,760.60","1,126,054,496.95","117,635,828.40","3,411.00","1,132,425,345.00","343,342,151.50","173,268,635.22","2,541,754,161.00","1,548,061,161.00","415,635,815.70",14.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
1451,IND,USA,2019,"-317,332,138.35","5,857,079,975.30","155,987,874.00","105,083.00","36,465,390,278.00","7,945,693,374.00","5,337,903,252.66","21,718,480,249.00","41,516,823,970.00","5,051,433,692.00",43.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
1558,ITA,USA,2019,"-1,622,300,914.94","5,435,486,579.58","2,022,873,172.00","77,213.00","32,212,083,530.00","20,754,201,381.00","3,922,190,305.26","35,604,498,963.00","38,310,468,818.00","6,030,827,348.00",31.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
1689,JPN,USA,2019,"-6,738,290,818.25","66,060,517,186.38","32,723,046,652.00","1,199,212.00","781,710,000,000.00","324,389,000,000.00","60,916,395,948.24","515,709,000,000.00","1,095,330,000,000.00","313,625,000,000.00",350.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
1791,LUX,USA,2019,"-3,231,757,650.35","3,332,746,910.29","-388,323,742.00","126,731.00","147,468,000,000.00","29,209,474,931.00","6,437,557,141.62","76,013,094,082.00","178,176,000,000.00","30,708,180,618.00",63.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
1891,MEX,USA,2019,"-280,984,053.18","5,043,410,403.42","1,448,745,821.00","61,886.00","30,395,613,881.00","17,242,712,380.00","3,143,624,379.72","18,378,739,182.00","34,904,470,549.00","4,508,856,668.00",11.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
1917,MYS,USA,2019,"-22,016,797.96","285,088,785.72","-26,428,881.00","2,012.00","1,476,338,968.00","4,715,069,626.00","102,203,604.24","3,821,127,859.00","1,636,871,607.00","160,532,640.00",4.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
1981,NOR,USA,2019,"-284,678,901.06","1,931,539,901.02","-2,629,293,000.00","17,940.00","20,498,901,000.00","17,233,378,000.00","911,298,538.80","98,404,944,000.00","30,658,253,000.00","10,159,351,000.00",4.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
2032,PAN,USA,2019,0.00,"13,648,631.42","14,913,304.00",311.00,"1,169,220,337.00","221,011,043.00","15,797,873.22","12,901,462.00","1,170,739,499.00","1,519,162.00",NaN,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
2047,PER,USA,2019,"-2,651,718.66","3,335,787.06","570,581.00",27.00,"4,264,592.00","326,086.00","1,371,519.54","655,967.00","17,400,773.00","13,136,181.00",NaN,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
2081,PRT,USA,2019,"-245,458,210.12","313,968,136.49","68,073,504.16","1,901.00","1,770,878,807.00","8,820,564,814.00","96,565,135.02","19,513,746,680.00","1,984,679,979.00","213,801,173.50",14.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
2220,ROU,USA,2019,"-34,070,917.05","174,449,733.76","31,204,614.00",485.00,"139,693,194.00","93,819,342.00","24,636,554.70","13,063,984.00","605,595,161.00","465,901,967.00",0.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
2320,SAU,USA,2019,"-17,897,137.76","4,400,329,078.84","66,778,416.00","7,300.00","35,278,588,214.00","15,329,077,477.00","370,818,246.00","25,186,197,289.00","43,736,513,829.00","8,457,925,615.00",2.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08
2347,SGP,USA,2019,"-1,466,660,367.51","2,077,201,465.03","427,032,012.00","22,887.00","26,593,262,791.00","14,878,271,001.00","1,162,591,396.74","16,007,852,429.00","38,699,174,813.00","12,105,912,024.00",9.00,"5,252,345,950,571.46","138,818,542.00","51,656,500,864,631.46","34,559,985,418,528.91","3,580,814,046,075.57","59,293,915,820,799.34","72,742,547,231,696.05","21,064,699,384,324.01","17,102.00","512,336,028,056.76","28,583,144.00","14,719,262,499,973.70","7,540,458,479,487.50","1,451,938,537,430.88","18,882,661,702,751.00","19,112,391,499,318.30","4,391,251,531,038.75","1,386.00",0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08

### Step 4.3. Keep only the shares for the partners, and drop duplicates (effectively only keep one value for each iso_partner)

In [25]:
# Keep iso_partner and share_reported_total_profit_loss_by_partner	share_reported_total_n_employees_by_partner	share_reported_total_unrelated_party_revenues_by_partner	share_reported_total_tangible_assets_except_cash_by_partner	share_reported_total_payroll_by_partner	share_reported_total_stated_capital_by_partner	share_reported_total_total_revenues_by_partner	share_reported_total_related_party_revenues_by_partner	share_reported_total_holding_or_managing_ip_by_partner
shares_reported_2019 = final_misalignment_2019[['iso_partner', 'share_reported_total_profit_loss_by_partner', 'share_reported_total_n_employees_by_partner', 'share_reported_total_unrelated_party_revenues_by_partner', 'share_reported_total_tangible_assets_except_cash_by_partner', 'share_reported_total_payroll_by_partner', 'share_reported_total_stated_capital_by_partner', 'share_reported_total_total_revenues_by_partner', 'share_reported_total_related_party_revenues_by_partner', 'share_reported_total_holding_or_managing_ip_by_partner']]

# Drop duplicates
shares_reported_2019 = shares_reported_2019.drop_duplicates()

shares_reported_2019[shares_reported_2019['iso_partner'] == 'USA']

,iso_partner,share_reported_total_profit_loss_by_partner,share_reported_total_n_employees_by_partner,share_reported_total_unrelated_party_revenues_by_partner,share_reported_total_tangible_assets_except_cash_by_partner,share_reported_total_payroll_by_partner,share_reported_total_stated_capital_by_partner,share_reported_total_total_revenues_by_partner,share_reported_total_related_party_revenues_by_partner,share_reported_total_holding_or_managing_ip_by_partner
15,USA,0.10,0.21,0.28,0.22,0.41,0.32,0.26,0.21,0.08

### Step 4.4. Bring back the excluded countries

- The key here is the third command, where we sum by iso_parent. We basically assume that all countries report for the rest of the world, without caring about continents. **This could be improved and changed**. 
- Once that sum is done, we combine all potential iso_combinations for 2016 (created in Step 1), and we keep all combinations for the "excluded countries".
- Note in the test view, that no matter who is the iso_partner, the number in the variables will be the same because we have aggregated them. The next cells will now create the right shares.

In [26]:
excluded_2019 = pd.read_csv(f'{data_final}/cbcr_main_no_imputation_allsubgroupsonly.csv')

# Keep if year == 2019 and iso_parent == 'AUT', 'FIN', 'IRL0', 'KOR', 'NLD', 'NOR' 'SWE'
excluded_2019 = excluded_2019[excluded_2019['year'] == 2019]
excluded_2019 = excluded_2019[excluded_2019['iso_parent'].isin(['AUT', 'CZE', 'FIN', 'GRC', 'HUN', 'IMN', 'IRL', 'KOR', 'MAC', 'MUS', 'NZL', 'POL', 'SWE', 'GBR'])]

# Sum by iso_parent: 'n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",'stated_capital', 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip' and 'profit_loss_before_income_tax_corrected'
excluded_2019 = excluded_2019.groupby('iso_parent').agg({'n_employees': 'sum', 'unrelated_party_revenues': 'sum', 'tangible_assets_except_cash': 'sum', 'payroll': 'sum', 'stated_capital': 'sum', 'total_revenues': 'sum', 'related_party_revenues': 'sum', 'holding_or_managing_ip': 'sum', 'profit_loss_before_income_tax_corrected': 'sum'}).reset_index()

# Merge iso_combinations_2019 with excluded_2019. 
excluded_jurisdictions_2019 = pd.merge(iso_combinations_2019, excluded_2019, on='iso_parent', how='left')

# Drop year_y
excluded_jurisdictions_2019 = excluded_jurisdictions_2019.drop(columns=['year_y'])
# Rename year_x to year
excluded_jurisdictions_2019 = excluded_jurisdictions_2019.rename(columns={'year_x': 'year'})

# Keep if iso_parent == 'AUT', 'FIN', 'IRL0', 'KOR', 'NLD', 'NOR' 'SWE'
excluded_jurisdictions_2019 = excluded_jurisdictions_2019[excluded_jurisdictions_2019['iso_parent'].isin(['AUT', 'CZE', 'FIN', 'GRC', 'HUN', 'IMN', 'IRL', 'KOR', 'MAC', 'MUS', 'NZL', 'POL', 'SWE', 'GBR'])]

excluded_jurisdictions_2019[excluded_jurisdictions_2019['iso_partner'] == 'USA']

,iso_parent,year,iso_partner,n_employees,unrelated_party_revenues,tangible_assets_except_cash,payroll,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip,profit_loss_before_income_tax_corrected
616,AUT,2019,USA,"2,008,493.00","626,699,874,863.00","376,167,584,865.00","14,217,046,223.71","234,583,578,395.00","793,870,310,447.00","167,156,841,265.00","1,196.00","36,984,207,173.65"
2506,CZE,2019,USA,"475,313.00","150,183,564,317.00","46,574,735,398.00","2,136,644,945.28","30,434,844,214.00","268,518,186,031.00","118,419,219,859.00",0.00,"5,221,484,424.00"
3346,FIN,2019,USA,"1,040,283.00","389,022,346,262.00","152,296,740,600.00","6,970,656,939.12","456,209,859,738.00","535,647,116,164.00","146,623,327,023.00",211.00,"38,129,397,314.00"
3766,GBR,2019,USA,"13,630,674.00","4,694,181,530,169.00","2,922,287,144,908.00","121,952,200,891.46","12,595,160,253,859.00","6,329,438,247,967.00","1,633,919,717,782.00","2,459.00","424,695,866,422.00"
3976,GRC,2019,USA,"224,505.00","81,347,343,203.66","53,804,213,410.14","2,587,691,619.01","123,919,093,719.92","97,592,559,665.80","16,245,216,458.04",176.00,"-913,518,434.12"
4396,HUN,2019,USA,"106,943.00","38,156,447,266.00","16,163,035,372.00","596,581,611.66","14,247,407,989.00","50,004,235,099.00","11,847,787,833.00",0.00,"4,244,515,221.00"
4816,IMN,2019,USA,"104,400.00","25,990,618,676.00","12,466,257,969.00","38,535,428.43","78,646,673,078.00","40,923,664,328.00","14,933,045,651.00",44.00,"8,159,443,951.00"
5236,IRL,2019,USA,"1,742,776.00","411,414,367,240.00","196,933,889,617.00","5,427,879,940.58","3,714,190,000,000.00","626,742,187,641.00","215,333,953,159.00",485.00,"-1,426,697,053.00"
5866,KOR,2019,USA,"5,344,161.00","2,526,385,408,263.00","1,741,605,391,577.00","69,502,551,975.53","838,731,311,848.00","3,617,231,834,032.00","1,092,030,052,295.00","1,009.00","131,240,234,946.00"
6706,MAC,2019,USA,"31,452.00","6,609,971,676.00","17,690,030,788.00","651,276,227.14","2,620,744,511.00","7,104,986,177.00","495,014,499.00",0.00,"1,126,361,990.00"
7126,MUS,2019,USA,"52,679.00","40,948,102,292.60","28,267,426,407.00","34,716.96","42,329,349,101.20","52,055,644,878.10","11,107,542,586.70",70.00,"-190,391,705.45"
7966,NZL,2019,USA,"152,443.00","63,725,085,900.00","53,439,243,698.00","3,671,808,042.53","53,022,467,887.00","93,148,803,064.00","29,420,043,329.00",72.00,"3,649,099,061.00"
8596,POL,2019,USA,"565,495.00","167,453,120,148.00","115,176,619,065.00","6,477,014,976.31","60,127,532,844.00","228,395,401,342.00","60,936,745,258.17",39.00,"5,375,916,524.20"
9856,SWE,2019,USA,"3,262,557.00","934,535,102,617.00","404,885,228,494.00","18,366,173,778.34","312,359,478,956.00","1,532,700,600,530.00","598,165,998,340.00","1,240.00","135,502,910,337.00"

### Step 4.5. Merge with the shares reported, and multiply the number

In [27]:
# Merge with share_reported_2019
excluded_jurisdictions_share_reported_2019 = pd.merge(excluded_jurisdictions_2019, shares_reported_2019, on='iso_partner', how='left')

# Multiply 'n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",'stated_capital', 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip' and 'profit_loss_before_income_tax_corrected' by share_reported
excluded_jurisdictions_share_reported_2019['n_employees'] = excluded_jurisdictions_share_reported_2019['n_employees'] * excluded_jurisdictions_share_reported_2019['share_reported_total_n_employees_by_partner']
excluded_jurisdictions_share_reported_2019['unrelated_party_revenues'] = excluded_jurisdictions_share_reported_2019['unrelated_party_revenues'] * excluded_jurisdictions_share_reported_2019['share_reported_total_unrelated_party_revenues_by_partner']
excluded_jurisdictions_share_reported_2019['tangible_assets_except_cash'] = excluded_jurisdictions_share_reported_2019['tangible_assets_except_cash'] * excluded_jurisdictions_share_reported_2019['share_reported_total_tangible_assets_except_cash_by_partner']
excluded_jurisdictions_share_reported_2019['payroll'] = excluded_jurisdictions_share_reported_2019['payroll'] * excluded_jurisdictions_share_reported_2019['share_reported_total_payroll_by_partner']
excluded_jurisdictions_share_reported_2019['stated_capital'] = excluded_jurisdictions_share_reported_2019['stated_capital'] * excluded_jurisdictions_share_reported_2019['share_reported_total_stated_capital_by_partner']
excluded_jurisdictions_share_reported_2019['total_revenues'] = excluded_jurisdictions_share_reported_2019['total_revenues'] * excluded_jurisdictions_share_reported_2019['share_reported_total_total_revenues_by_partner']
excluded_jurisdictions_share_reported_2019['related_party_revenues'] = excluded_jurisdictions_share_reported_2019['related_party_revenues'] * excluded_jurisdictions_share_reported_2019['share_reported_total_related_party_revenues_by_partner']
excluded_jurisdictions_share_reported_2019['holding_or_managing_ip'] = excluded_jurisdictions_share_reported_2019['holding_or_managing_ip'] * excluded_jurisdictions_share_reported_2019['share_reported_total_holding_or_managing_ip_by_partner']
excluded_jurisdictions_share_reported_2019['profit_loss_before_income_tax_corrected'] = excluded_jurisdictions_share_reported_2019['profit_loss_before_income_tax_corrected'] * excluded_jurisdictions_share_reported_2019['share_reported_total_profit_loss_by_partner']

# Drop share_reported columns
excluded_jurisdictions_dataset_2019 = excluded_jurisdictions_share_reported_2019.drop(columns=[
    'share_reported_total_profit_loss_by_partner',
    'share_reported_total_n_employees_by_partner',
    'share_reported_total_unrelated_party_revenues_by_partner',
    'share_reported_total_tangible_assets_except_cash_by_partner',
    'share_reported_total_payroll_by_partner',
    'share_reported_total_stated_capital_by_partner',
    'share_reported_total_total_revenues_by_partner',
    'share_reported_total_related_party_revenues_by_partner',
    'share_reported_total_holding_or_managing_ip_by_partner'
])

excluded_jurisdictions_dataset_2019[excluded_jurisdictions_dataset_2019['iso_partner'] == 'USA']

,iso_parent,year,iso_partner,n_employees,unrelated_party_revenues,tangible_assets_except_cash,payroll,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip,profit_loss_before_income_tax_corrected
196,AUT,2019,USA,"413,554.59","178,575,006,289.77","82,073,994,553.33","5,764,688,429.79","74,705,174,899.24","208,581,645,135.70","34,846,342,771.68",96.93,"3,607,595,916.66"
406,CZE,2019,USA,"97,868.34","42,794,058,237.83","10,161,892,553.16","866,360,860.11","9,692,240,077.48","70,550,522,237.90","24,686,256,899.41",0.00,"509,325,664.29"
616,FIN,2019,USA,"214,197.31","110,849,978,940.53","33,228,811,735.55","2,826,442,621.95","145,283,986,183.80","140,736,031,101.57","30,565,824,725.46",17.10,"3,719,302,604.19"
826,GBR,2019,USA,"2,806,595.66","1,337,583,634,364.87","637,598,211,181.68","49,448,839,822.58","4,011,038,010,785.72","1,662,997,879,089.86","340,614,994,375.10",199.29,"41,426,630,192.00"
1036,GRC,2019,USA,"46,226.24","23,179,520,065.21","11,739,253,715.75","1,049,250,013.06","39,463,110,048.20","25,641,488,767.40","3,386,558,257.58",14.26,"-89,108,449.92"
1246,HUN,2019,USA,"22,019.88","10,872,489,502.27","3,526,526,288.98","241,900,255.51","4,537,210,630.69","13,138,122,793.42","2,469,848,513.47",0.00,"414,027,958.14"
1456,IMN,2019,USA,"21,496.27","7,405,897,271.89","2,719,946,188.39","15,625,238.53","25,045,715,082.59","10,752,291,801.55","3,113,016,634.21",3.57,"795,906,656.63"
1666,IRL,2019,USA,"358,842.68","117,230,473,731.38","42,967,952,673.52","2,200,881,688.04","1,182,816,015,756.19","164,670,368,514.60","44,889,582,055.83",39.31,"-139,166,061.84"
1876,KOR,2019,USA,"1,100,378.39","719,880,932,271.73","379,991,570,708.16","28,181,701,804.28","267,101,259,916.70","950,392,220,052.66","227,649,991,656.15",81.77,"12,801,727,328.37"
2086,MAC,2019,USA,"6,476.06","1,883,478,489.40","3,859,693,256.30","264,077,676.34","834,598,817.19","1,866,765,498.05","103,193,173.42",0.00,"109,870,110.15"
2296,MUS,2019,USA,"10,846.76","11,667,957,690.36","6,167,518,665.38","14,076.94","13,480,148,310.52","13,677,110,611.63","2,315,533,324.26",5.67,"-18,571,611.82"
2506,NZL,2019,USA,"31,388.46","18,158,145,664.06","11,659,622,925.19","1,488,834,530.47","16,885,464,720.88","24,473,935,263.52","6,133,047,899.46",5.84,"355,948,548.80"
2716,POL,2019,USA,"116,437.08","47,714,932,111.97","25,129,770,841.91","2,626,282,049.45","19,148,134,273.10","60,008,653,713.88","12,703,175,631.86",3.16,"524,389,624.20"
2926,SWE,2019,USA,"671,770.03","266,291,120,393.67","88,339,743,707.76","7,447,065,150.77","99,473,584,922.26","402,702,064,243.99","124,696,645,705.78",100.49,"13,217,526,706.26"

## Step 5. Calculate Misalignment with all countries reporting in the CBCR

### Step 5.1. Concatenate the two samples

- Concatenate the cbcr_sample (without the "bad reporters") and the sample with the bad reporters.
- Ensure all required columns are included: 'iso_parent', 'year', 'iso_partner', 'n_employees', 'unrelated_party_revenues', 'tangible_assets_except_cash', 'payroll', 'stated_capital', 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip', 'profit_loss_before_income_tax_corrected'.

In [28]:
final_misalignment_2019 = cbcr_sample[cbcr_sample['year'] == 2019].copy()

# Concatenate excluded_jurisdictions_dataset_2016
final_misalignment_2019 = pd.concat([final_misalignment_2019, excluded_jurisdictions_dataset_2019])

# Save the final misalignment dataset
#final_misalignment_2019.to_csv(f'{output_tables}/Datasets_to_Perform_Analysis/misalignment_dataset_2019.csv', index=False) 

final_misalignment_2019[final_misalignment_2019['iso_partner'] == 'ZAF']

,iso_parent,parent_jurisdiction,iso_partner,partner_jurisdiction,year,unrelated_party_revenues,profit_loss_before_income_tax,adjusted_profit_loss_before_income_tax,income_tax_paid_on_cash_basis,income_tax_accrued_current_year,n_employees,tangible_assets_except_cash,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip,n_cbcr,n_cbcr_groups,n_entities,profit_loss_before_income_tax_corrected,ln_profit_loss_before_income_tax_corrected,ln_unrelated_party_revenues,ln_n_employees,ln_tangible_assets_except_cash,ln_stated_capital,ln_total_revenues,ln_related_party_revenues,ln_holding_or_managing_ip,etr_domestic,etr_domestic_corrected,etr_foreign,etr_foreign_corrected,etr_average,etr_average_corrected,cit,gdp_current_usd,population,gdp,wage_monthly,payroll,ln_wage_monthly,ln_gdp_current_usd,ln_population,gvt_health_expenditure,ln_gvt_health_expenditure,tax_revenue_pct_gdp,tax_revenue_current_usd,cthi_2021_share,cthi_2021_score,region_tjn,ukt,gbr_oct,nld_oct,oecd_oct,oecd,eu
262,ARG,Argentina,ZAF,South Africa,2019,"28,759.50","-1,380,866.27",NaN,"-1,828.06",457.28,1.00,0.00,"-1,367,475.58","28,759.50",0.00,0.00,2.00,2.00,2.00,"-1,380,866.27",0.00,10.27,0.69,0.00,0.00,10.27,0.00,0.00,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"3,156.05",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
749,AUS,Australia,ZAF,South Africa,2019,"2,674,200,220.00","-520,275,002.00",NaN,"78,157,684.00","25,102,543.00","13,554.00","1,740,767,202.00","4,017,181,536.00","3,957,608,330.00","1,283,408,110.00",5.00,23.00,23.00,129.00,"-520,275,002.00",0.00,21.71,9.51,21.28,22.11,22.10,20.97,1.79,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"42,777,074.59",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
1641,BMU,Bermuda,ZAF,South Africa,2019,"354,152,194.40","19,236,151.23",NaN,"1,274,595.18","1,856,154.40",984.00,"84,416,478.32","72,346,232.54","397,311,899.70","43,159,705.32",NaN,21.00,21.00,40.00,"19,236,151.23",16.77,19.69,6.89,18.25,18.10,19.80,17.58,NaN,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"3,105,551.23",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
1890,BRA,Brazil,ZAF,South Africa,2019,"394,081,253.00","-67,666,834.00",NaN,"10,567,377.00","10,354,735.00","1,614.00","186,364,247.00","58,314,195,898.00","490,925,512.00","96,844,258.00",0.00,11.00,11.00,29.00,"-67,666,834.00",0.00,19.79,7.39,19.04,24.79,20.01,18.39,0.00,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"5,093,861.47",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
2711,CHE,Switzerland,ZAF,South Africa,2019,"9,726,972,493.00","-288,453,660.00",NaN,"120,783,992.00","-4,941,754.00","3,452.00","7,341,447,985.00","3,298,539,497.00","11,832,818,812.00","2,105,847,317.00",3.00,57.00,57.00,253.00,"-288,453,660.00",0.00,23.00,8.15,22.72,21.92,23.19,21.47,1.39,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"10,894,677.70",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
3561,CHN,China (People’s Republic of),ZAF,South Africa,2019,"5,667,441,916.00","428,701,450.30",NaN,"105,542,873.80","126,153,812.70","11,319.00","4,362,137,075.00","1,843,420,497.00","7,799,073,233.00","2,137,949,950.00",7.00,83.00,83.00,139.00,"428,701,450.30",19.88,22.46,9.33,22.20,21.33,22.78,21.48,2.08,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"35,723,307.31",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
4131,CYM,Cayman Islands,ZAF,South Africa,2019,"93,624,369.00","-1,280,525.00",NaN,"2,067,613.00","121,720.00",546.00,"12,964,234.00","18,688,474.00","115,156,549.00","21,532,180.00",0.00,11.00,11.00,17.00,"-1,280,525.00",0.00,18.35,6.30,16.38,16.74,18.56,16.89,0.00,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"1,723,202.21",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
4951,DEU,Germany,ZAF,South Africa,2019,"15,073,638,000.00","769,258,000.00",NaN,"295,700,000.00","285,061,000.00","54,200.00","6,639,920,000.00","2,736,434,000.00","23,270,800,000.00","8,321,436,000.00",18.00,135.00,135.00,405.00,"769,258,000.00",20.46,23.44,10.90,22.62,21.73,23.87,22.84,2.94,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"171,057,801.60",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
5608,DNK,Denmark,ZAF,South Africa,2019,"1,397,707,078.00","34,955,892.00",NaN,"17,643,899.00","9,016,994.00","11,281.00","229,898,066.00","177,404,750.00","1,879,297,554.00","481,590,476.00",0.00,20.00,20.00,81.00,"34,955,892.00",17.37,21.06,9.33,19.25,18.99,21.35,19.99,0.00,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"35,603,377.49",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
6194,ESP,Spain,ZAF,South Africa,2019,"840,519,663.00","-83,788,554.00",NaN,"6,706,265.00","10,306,179.00","4,689.00","1,073,540,580.00","645,133,004.00","1,540,176,252.00","699,656,589.00",9.00,27.00,27.00,115.00,"-83,788,554.00",0.00,20.55,8.45,20.79,20.28,21.16,20.37,2.30,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"14,798,709.07",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
6772,FRA,France,ZAF,South Africa,2019,"8,278,103,938.00","323,952,730.00",NaN,"126,520,390.00","116,581,319.00","27,723.00","2,169,374,359.00","1,463,175,071.00","8,791,722,459.00","513,618,512.00",12.00,88.00,88.00,334.00,"323,952,730.00",19.60,22.84,10.23,21.50,21.10,22.90,20.06,2.56,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"87,495,118.70",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
7576,HKG,Hong Kong (China),ZAF,South Africa,2019,"139,884,255.00","6,496,096.00",NaN,"133,514.00","380,982.00",311.00,"8,727,520.00","10,548,318.00","154,708,443.00","14,824,187.00",0.00,11.00,11.00,16.00,"6,496,096.00",15.69,18.76,5.74,15.98,16.17,18.86,16.51,0.00,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"981,530.93",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
7934,IDN,Indonesia,ZAF,South Africa,2019,"4,171,576.70","46,245.46",NaN,"37,766.91","12,509.50",4.00,"708,733.86",0.00,"4,171,576.70",0.00,0.00,1.00,1.00,1.00,"46,245.46",10.74,15.24,1.61,13.47,0.00,15.24,0.00,0.00,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"12,624.19",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
8488,IND,India,ZAF,South Africa,2019,"1,642,475,997.00","91,167,208.00",NaN,"43,491,356.00","41,663,287.00","6,089.00","479,931,709.00","288,373,051.00","1,883,237,005.00","240,761,008.00",20.00,36.00,36.00,118.00,"91,167,208.00",18.33,21.22,8.71,19.99,19.48,21.36,19.30,3.04,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"19,217,176.27",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
9156,ITA,Italy,ZAF,South Africa,2019,"398,986,125.00","-16,553,954.00",NaN,"6,069,334.00","2,162,643.00","3,357.00","1,047,461,957.00","1,237,252,399.00","480,905,866.00","81,919,732.00",NaN,24.00,24.00,60.00,"-16,553,954.00",0.00,19.80,8.12,20.77,20.94,19.99,18.22,NaN,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"10,594,853.14",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
9946,JPN,Japan,ZAF,South Africa,2019,"11,603,840,854.00","277,422,110.30",NaN,"141,055,246.70","147,804,343.00","38,884.00","3,370,068,460.00","1,296,387,514.00","13,490,850,223.00","1,887,009,369.00",6.00,101.00,101.00,268.00,"277,422,110.30",19.44,23.17,10.57,21.94,20.98,23.33,21.36,1.95,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"122,719,770.43",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
10582,LUX,Luxembourg,ZAF,South Africa,2019,"5,231,180,046.00","-298,905,404.00",NaN,"2,377,023.00","15,418,336.00","17,262.00","1,809,109,441.00","949,341,664.00","5,457,280,029.00","226,099,983.00",3.00,39.00,39.00,122.00,"-298,905,404.00",0.00,22.38,9.76,21.32,20.67,22.42,19.24,1.39,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"54,479,700.58",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
11211,MEX,Mexico,ZAF,South Africa,2019,"50,539,582.00","1,190,765.00",NaN,"805,397.00","799,552.00",219.00,"17,573,072.00","14,994,968.00","51,524,967.00","985,386.00",0.00,2.00,2.00,11.00,"1,190,765.00",13.99,17.74,5.39,16.68,16.52,17.76,13.80,0.00,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"691,174.51",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
11695,NOR,Norway,ZAF,South Africa,2019,"247,278,000.00","-18,958,000.00",NaN,"430,000.00","1,271,000.00","1,170.00","50,748,000.00","130,553,000.00","262,011,000.00","14,733,000.00",NaN,13.00,13.00,18.00,"-18,958,000.00",0.00,19.33,7.07,17.74,18.69,19.38,16.51,NaN,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"3,692,576.16",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
12226,PRT,Portugal,ZAF,South Africa,2019,"76,441,403.72","-1,403,039.64",NaN,"1,074,523.13","939,841.39",223.00,"7,601,150.20","184,102.06","95,919,436.26","19,478,032.54",0.00,7.00,7.00,11.00,"-1,403,039.64",0.00,18.15,5.41,15.84,12.12,18.38,16.78,0.00,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"703,798.70",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
12815,ROU,Romania,ZAF,South Africa,2019,"1,136,684,299.00","37,587,059.00",NaN,"46,966,439.00","18,735,135.00","1,109.00","229,486,700.00","12,382,187.00","1,465,010,624.00","328,326,325.00",0.00,1.00,1.00,2.00,"37,587,059.00",17.44,20.85,7.01,19.25,16.33,21.11,19.61,0.00,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"3,500,057.23",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
13188,SAU,Saudi Arabia,ZAF,South Africa,2019,"196,121,815.00","-480,222.00",NaN,"45,680.00","243,458.00",39.00,"1,161,296.00","3,118,371.00","209,966,128.00","13,844,313.00",NaN,4.00,4.00,7.00,"-480,222.00",0.00,19.09,3.69,13.97,14.95,19.16,16.44,NaN,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"123,085.87",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
13375,SGP,Singapore,ZAF,South Africa,2019,"1,568,754,548.00","-23,176,743.00",NaN,"4,361,441.00","5,410,066.00","1,740.00","222,008,383.00","222,907,613.00","2,321,404,189.00","752,649,641.00",NaN,10.00,10.00,38.00,"-23,176,743.00",0.00,21.17,7.46,19.22,19.22,21.57,20.44,NaN,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"5,491,523.52",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
13595,TUR,Türkiye,ZAF,South Africa,2019,"306,053,350.00","7,526,456.00",NaN,"3,371,041.00","2,658,740.00","2,578.00","78,706,383.00","61,049,597.00","325,730,947.00","17,763,511.00",NaN,5.00,5.00,6.00,"7,526,456.00",15.83,19.54,7.86,18.18,17.93,19.60,16.69,NaN,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"8,136,291.74",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
14447,USA,United States,ZAF,South Africa,2019,"23,086,129,128.00","2,127,775,501.00",NaN,"431,092,049.00","454,134,075.00","121,113.00","8,065,765,542.00","24,528,780,160.00","34,511,112,541.00","11,424,983,413.00",NaN,443.00,443.00,"1,204.00","1,297,943,055.61",20.98,23.86,11.70,22.81,23.92,24.26,23.16,NaN,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"382,238,441.42",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
14869,ZAF,South Africa,ZAF,South Africa,2019,"130,966,000,000.00","13,937,889,426.00",NaN,"2,622,265,504.00","2,316,702,685.00","992,705.00","64,568,716,845.00","128,700,000,000.00","146,412,000,000.00","15,446,127,042.00",8.00,54.00,54.00,"2,893.00","9,059,628,126.90",22.93,25.60,13.81,24.89,25.58,25.71,23.46,2.20,0.10,0.13,0.19,0.20,0.12,0.15,0.28,"389,330,032,224.27","58,087,055.00",NaN,263.00,"3,133,024,629.84",5.58,26.69,17.88,"18,688,090,576.76",23.65,24.87,"96,816,043,586.61",0.00,49.42,Africa,0.00,0.00,0.00,0.00,0.00,0.00
207,AUT,NaN,ZAF,NaN,2019,"2,683,066,319.12",NaN,NaN,NaN,NaN,"19,042.92","1,129,794,189.43","910,107,655.08","2,916,075,285.79","366,413,565.01",6.36,NaN,NaN,NaN,"77,686,988.06",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"16,492,324.62",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
417,CZE,NaN,ZAF,NaN,2019,"642,975,177.22",NaN,NaN,NaN,NaN,"4,506.54","139,884,103.64","118,077,253.70","986,331,439.49","259,579,016.84",0.00,NaN,NaN,NaN,"10,967,962.52",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2,478,590.94",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
627,FIN,NaN,ZAF,NaN,2019,"1,665,506,563.04",NaN,NaN,NaN,NaN,"9,863.13","457,413,077.37","1,769,945,230.22","1,967,559,810.21","321,403,393.13",1.12,NaN,NaN,NaN,"80,092,511.38",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"8,086,232.21",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
837,GBR,NaN,ZAF,NaN,2019,"20,097,020,702.57",NaN,NaN,NaN,NaN,"129,235.11","8,776,894,046.69","48,865,107,448.62","23,249,538,627.36","3,581,608,411.57",13.08,NaN,NaN,NaN,"892,092,739.69",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"141,469,279.43",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1047,GRC,NaN,ZAF,NaN,2019,"348,269,284.00",NaN,NaN,NaN,NaN,"2,128.58","161,597,357.46","480,765,604.21","358,480,784.04","35,610,075.13",0.94,NaN,NaN,NaN,"-1,918,886.50",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3,001,822.57",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1257,HUN,NaN,ZAF,NaN,2019,"163,357,745.27",NaN,NaN,NaN,NaN,"1,013.95","48,544,596.03","55,275,288.94","183,677,500.26","25,970,759.82",0.00,NaN,NaN,NaN,"8,915,794.83",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"692,057.79",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1467,IMN,NaN,ZAF,NaN,2019,"111,272,646.41",NaN,NaN,NaN,NaN,989.84,"37,441,572.28","305,123,400.81","150,322,394.70","32,733,751.44",0.23,NaN,NaN,NaN,"17,139,278.44",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"44,702.59",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1677,IRL,NaN,ZAF,NaN,2019,"1,761,372,670.11",NaN,NaN,NaN,NaN,"16,523.60","591,477,769.86","14,409,843,922.31","2,302,173,768.05","472,019,456.98",2.58,NaN,NaN,NaN,"-2,996,841.23",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"6,296,551.09",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1887,KOR,NaN,ZAF,NaN,2019,"10,816,117,682.33",NaN,NaN,NaN,NaN,"50,669.05","5,230,795,344.55","3,254,003,509.91","13,286,956,591.52","2,393,767,563.01",5.37,NaN,NaN,NaN,"275,676,007.25",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"80,625,653.94",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2097,MAC,NaN,ZAF,NaN,2019,"28,299,020.13",NaN,NaN,NaN,NaN,298.20,"53,130,824.66","10,167,632.61","26,098,311.43","1,085,088.87",0.00,NaN,NaN,NaN,"2,365,973.94",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"755,505.66",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2307,MUS,NaN,ZAF,NaN,2019,"175,309,551.67",NaN,NaN,NaN,NaN,499.46,"84,899,325.17","164,224,047.20","191,212,818.41","24,348,116.70",0.37,NaN,NaN,NaN,"-399,926.33",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2517,NZL,NaN,ZAF,NaN,2019,"272,823,784.59",NaN,NaN,NaN,NaN,"1,445.34","160,501,195.34","205,709,855.08","342,157,804.55","64,489,750.33",0.38,NaN,NaN,NaN,"7,665,096.45",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4,259,439.63",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2727,POL,NaN,ZAF,NaN,2019,"716,910,669.24",NaN,NaN,NaN,NaN,"5,361.57","345,925,274.30","233,275,186.17","838,950,867.01","133,575,448.67",0.21,NaN,NaN,NaN,"11,292,354.08",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7,513,588.40",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2937,SWE,NaN,ZAF,NaN,2019,"4,000,989,562.05",NaN,NaN,NaN,NaN,"30,932.95","1,216,045,711.92","1,211,852,742.97","5,629,975,429.12","1,311,200,512.39",6.60,NaN,NaN,NaN,"284,629,948.34",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"21,305,473.38",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 5.2. Perform the misalignment estimates, and all the remaining calculations needed

In [29]:
# Initialize a list to store the aggregate results
results_sample = []

# Start the estimates
misalignment_final_estimates_2019 = final_misalignment_2019[final_misalignment_2019['year'] == 2019].copy()
misalignment_final_estimates_2019 = calculate_misalignment(misalignment_final_estimates_2019, etr_max=0.15, weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0])

# Perform the groupby operation on 'iso_partner'
country_results_2019 = misalignment_final_estimates_2019.groupby(['iso_partner']).agg(
    negative_misalignment=('misaligned_profit', lambda x: x[x < 0].sum()),
    positive_misalignment=('misaligned_profit', lambda x: x[x > 0].sum()),
    theoretical_profit=('theoretical_profit', 'sum'),
    reported_profit=('profit_loss_before_income_tax_corrected', 'sum')
).reset_index()

# Convert results to millions
country_results_2019['negative_misalignment'] = -country_results_2019['negative_misalignment'] / 1e6
country_results_2019['positive_misalignment'] = country_results_2019['positive_misalignment'] / 1e6
country_results_2019['theoretical_profit'] = country_results_2019['theoretical_profit'] / 1e6
country_results_2019['reported_profit'] = country_results_2019['reported_profit'] / 1e6

# Merge the unique columns back into the result
country_results_2019 = country_results_2019.merge(unique_columns, on='iso_partner', how='left')

# Calculate other relevant variables
country_results_2019['tax_revenue_loss'] = country_results_2019['negative_misalignment'] * country_results_2019['cit']
country_results_2019['tax_revenue_gain'] = country_results_2019['positive_misalignment'] * country_results_2019['etr_average_corrected']

country_results_2019['tax_revenue_loss_pct_of_gvt_health_expenditure'] = np.where(
    country_results_2019['gvt_health_expenditure'] == 0, 
    np.nan, 
    country_results_2019['tax_revenue_loss'] / (country_results_2019['gvt_health_expenditure'] / 1e6)
)
    
country_results_2019['tax_revenue_loss_pct_of_total_tax_revenues'] = np.where(
    country_results_2019['tax_revenue_current_usd'] == 0, 
    np.nan, 
    country_results_2019['tax_revenue_loss'] / (country_results_2019['tax_revenue_current_usd'] / 1e6)
)

# Calculate totals
total_positive_misalignment = country_results_2019['positive_misalignment'].sum()
total_negative_misalignment = country_results_2019['negative_misalignment'].sum()
total_profits = country_results_2019['reported_profit'].sum()
misaligned_of_total_profits = total_positive_misalignment / total_profits
total_tax_revenue_loss = country_results_2019['tax_revenue_loss'].sum()
total_tax_revenue_gain = country_results_2019['tax_revenue_gain'].sum()
average_tax_revenue_loss_pct_of_gvt_health_expenditure = country_results_2019['tax_revenue_loss_pct_of_gvt_health_expenditure'].mean()
average_tax_revenue_loss_pct_of_total_tax_revenues = country_results_2019['tax_revenue_loss_pct_of_total_tax_revenues'].mean()

print(f"Year {2019}: Positive Misalignment: {total_positive_misalignment}, Negative Misalignment: {total_negative_misalignment}, Shifted of total profits: {misaligned_of_total_profits}, "
        f"Total tax revenue loss: {total_tax_revenue_loss}, Total tax revenue gain: {total_tax_revenue_gain}")

# Calculate countries' fractions of totals
country_results_2019['tax_revenue_loss_caused_pct_of_total'] = country_results_2019['positive_misalignment'] / total_positive_misalignment
country_results_2019['tax_revenue_loss_caused_usd'] = country_results_2019['tax_revenue_loss_caused_pct_of_total'] * total_tax_revenue_loss
country_results_2019['tax_revenue_loss_suffered_pct_of_total'] = country_results_2019['tax_revenue_loss'] / total_tax_revenue_loss

country_results_2019 = country_results_2019.sort_values(by='iso_partner')
country_results_2019.to_csv(f'{output_tables}/Final_Full_CBCR_Datasets/SOTJ_sample_countries_2019.csv', index=False) # CHANGE FILE NAME HERE, DEPENDING ON FORMULA USE
    
# Append aggregate results to the list
results_sample.append({
    'year': 2019,
    'total_positive_misalignment': total_positive_misalignment,
    'total_negative_misalignment': total_negative_misalignment,
    'total_profits': total_profits,
    'misaligned_of_total_profits': misaligned_of_total_profits,
    'total_tax_revenue_loss': total_tax_revenue_loss,
    'total_tax_revenue_gain': total_tax_revenue_gain,
    'average_tax_revenue_loss_pct_of_gvt_health_expenditure': average_tax_revenue_loss_pct_of_gvt_health_expenditure,
    'average_tax_revenue_loss_pct_of_total_tax_revenues': average_tax_revenue_loss_pct_of_total_tax_revenues
})

# Convert aggregate results to a DataFrame
results_sample_df = pd.DataFrame(results_sample)

# Save the aggregated results to a CSV or Excel file
results_sample_df.to_csv(f'{output_tables}/Final_Full_CBCR_Datasets/SOTJ_sample_aggregate_results_2019.csv', index=False)  # CHANGE FILE NAME HERE, DEPENDING ON FORMULA USE

Year 2019: Positive Misalignment: 1162186.8677575332, Negative Misalignment: 1162186.8677575332, Shifted of total profits: 0.19228309544476496, Total tax revenue loss: 306039.3340631637, Total tax revenue gain: 107502.66922670024

/var/folders/pm/bp4z4lln39xcwn73chrtp3n00000gn/T/ipykernel_6423/421381151.py:51: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

## Step 6. Checking the datasets

### Step 6.1. Checking the countries

In [30]:
# Open the CSV file f'{output_tables}/Scaling_Mario/SOTJ_sample_2016.csv'
sotj_2019_countries = pd.read_csv(f'{output_tables}/Final_Full_CBCR_Datasets/SOTJ_sample_countries_2019.csv')
sotj_2019_countries

,iso_partner,negative_misalignment,positive_misalignment,theoretical_profit,reported_profit,partner_jurisdiction,etr_average_corrected,cit,tax_revenue_current_usd,gvt_health_expenditure,region_tjn,ukt,oecd,oecd_oct,nld_oct,tax_revenue_loss,tax_revenue_gain,tax_revenue_loss_pct_of_gvt_health_expenditure,tax_revenue_loss_pct_of_total_tax_revenues,tax_revenue_loss_caused_pct_of_total,tax_revenue_loss_caused_usd,tax_revenue_loss_suffered_pct_of_total
0,ABW,0.12,0.00,59.89,84.36,Aruba,0.20,0.25,NaN,NaN,Caribbean/American isl.,0.00,0.00,1.00,1.00,0.03,0.00,NaN,NaN,0.00,0.00,0.00
1,AFG,14.27,4.87,15.48,1.39,Afghanistan,0.07,0.20,NaN,"93,965,898.86",Asia,0.00,0.00,0.00,0.00,2.85,0.32,0.03,NaN,0.00,1.28,0.00
2,AGO,32.96,335.11,336.75,"2,878.77",Angola,0.36,0.30,"7,153,877,964.00","949,590,173.24",Africa,0.00,0.00,0.00,0.00,9.89,121.41,0.01,0.00,0.00,88.25,0.00
3,AIA,3.13,4.54,4.54,5.91,Anguilla,0.00,0.00,NaN,NaN,Caribbean/American isl.,1.00,0.00,1.00,0.00,0.00,0.00,NaN,NaN,0.00,1.19,0.00
4,ALB,55.61,25.98,176.55,121.28,Albania,0.08,0.15,"2,794,565,426.68","451,085,348.78",Europe,0.00,0.00,0.00,0.00,8.34,1.97,0.02,0.00,0.00,6.84,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,XKV,1.84,0.20,4.06,2.03,Kosovo,0.08,0.10,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.18,0.02,NaN,NaN,0.00,0.05,0.00
206,YEM,228.45,0.28,234.21,2.67,Yemen,0.45,0.20,NaN,NaN,Asia,0.00,0.00,0.00,0.00,45.69,0.12,NaN,NaN,0.00,0.07,0.00
207,ZAF,"4,619.19",616.20,"18,011.49","12,696.00",South Africa,0.15,0.28,"96,816,043,586.61","18,688,090,576.76",Africa,0.00,0.00,0.00,0.00,"1,293.37",89.95,0.07,0.01,0.00,162.27,0.00
208,ZMB,"1,377.65",0.62,"1,283.40",-357.01,Zambia,0.16,0.35,"3,887,331,659.63","526,383,743.13",Africa,0.00,0.00,0.00,0.00,482.18,0.10,0.92,0.12,0.00,0.16,0.00
209,ZWE,697.04,0.06,"1,184.45",503.08,Zimbabwe,0.19,0.26,NaN,"120,051,500.00",Africa,0.00,0.00,0.00,0.00,179.49,0.01,1.50,NaN,0.00,0.02,0.00

### Step 6.2. Checking the aggregate results

In [31]:
sotj_2019_aggregate = pd.read_csv(f'{output_tables}/Final_Full_CBCR_Datasets/SOTJ_sample_aggregate_results_2019.csv')
sotj_2019_aggregate

,year,total_positive_misalignment,total_negative_misalignment,total_profits,misaligned_of_total_profits,total_tax_revenue_loss,total_tax_revenue_gain,average_tax_revenue_loss_pct_of_gvt_health_expenditure,average_tax_revenue_loss_pct_of_total_tax_revenues
0,2019,"1,162,186.87","1,162,186.87","6,044,144.78",0.19,"306,039.33","107,502.67",0.40,0.03