## The State of Tax Justice: Estimate misalignment for 2021

- Author: Mario Cuenda García, based on Alison Schultz, based on Javier Garcia Bernado's work
- Created: 4 November 2024
- Last updated:

**Description**
- This notebook is the third out of three notebooks to estimate the tax losses caused by profit shifting by multinational enterprises (MNEs). The analysis used the misalignment method based on the country-by-country reports (CbCR) published by the OECD.
    - Details on the misalignment method and its background can be found here: https://www.sciencedirect.com/science/article/pii/S0305750X23003455. 
    - The working paper version is here: https://www.econstor.eu/bitstream/10419/286362/1/wp-2023-33.pdf 

- This notebook estimates profit misalignment based on different formulas. It uses the dataset **"data/final/cbcr_main.csv"** (for the estimation with imputed values) or the dataset **"data/final/cbcr_main_noimputation_allsubgroupsonly.csv"** (for the estimation without imputed values). 

**Outline**
1. Define misalignment
2. Calculate misalignment for sample with full information.
3. Calculate misalignment for samples with imputed data and aggregate results. 

**To dos before running this notebook**
- Run the notebooks 1_clean and 2_impute_missings. Note the requirements and instructions given in these notebooks.

**To dos in this notebook**

Change the formula to any required formula in each section and adapt the output name of the csvs. The formulas I have used are like follows, where sales refer to unrelated party revenues and assets to tangible assets excluding cash.

The order of the formula is as follow:

- formula_vars=['n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll", 'stated_capital' 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip']

    - SOTJ: 50% employees, 50% payroll

        - weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0]

    - Canadian formula: 50% employees, 50% sales

        - weights=[1/2, 1/2, 0, 0, 0, 0, 0, 0]

    - CCCTB: 1/6 employees, 1/6 payroll, 1/3 sales, 1/3 assets

        - weights=[1/6, 1/3, 1/3, 1/6, 0, 0, 0, 0]
        
    - Double-weighted sales: 1/4 employees, 1/2 sales, 1/4 assets

        - weights=[1/4, 1/2, 1/4, 0, 0, 0, 0, 0]

    - Three-factor: 1/3 employees, 1/3 sales, 1/3 assets

        - weights=[1/3, 1/3, 1/3, 0, 0, 0, 0, 0]

- Adjust the input path in 5.1 to the bootstrapped sample you use

## 0. Load packages

In [1]:
# Packages
import pandas as pd
import numpy as np
import tjn_tools
from config import *

# Show columns and select data format
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)
# Reset display.max_rows to default
pd.reset_option('display.max_rows')


pd.options.display.float_format = '{:,.8f}'.format

[TJN TOOLS: Data processing] Module loaded.
[TJN TOOLS: Other functions] Module loaded.
[TJN TOOLS: Paths] Module loaded. Sharepoint FOUND at /Users/mariocuendagarcia/Library/CloudStorage/OneDrive-SharedLibraries-TaxJusticeNetworkLtd

## Step 1. Generate the template datasets

### Step 1.1. Generate the dataset with Unique ISO parents

In [2]:
# Open the original dataset
iso_parents = pd.read_csv(f'{data_final}/cbcr_main_no_imputation_allsubgroupsonly.csv')

# Keep just the following columns: iso_parent and year
iso_parents = iso_parents[['iso_parent', 'year']]

# Keep every unique combination of iso_parent and year
iso_parents = iso_parents.drop_duplicates(subset=['iso_parent', 'year'])

# Sort by year, then iso_parent
iso_parents = iso_parents.sort_values(by=['year', 'iso_parent'])

# Filter by year
iso_parents_2016= iso_parents[iso_parents['year'] == 2016]
iso_parents_2017= iso_parents[iso_parents['year'] == 2017]
iso_parents_2018= iso_parents[iso_parents['year'] == 2018]
iso_parents_2019= iso_parents[iso_parents['year'] == 2019]
iso_parents_2020= iso_parents[iso_parents['year'] == 2020]
iso_parents_2021= iso_parents[iso_parents['year'] == 2021]

# OPTIONAL: Print the count of how many unique iso_partner values there are
print(iso_parents_2016['iso_parent'].nunique())
print(iso_parents_2017['iso_parent'].nunique())
print(iso_parents_2018['iso_parent'].nunique())
print(iso_parents_2019['iso_parent'].nunique())
print(iso_parents_2020['iso_parent'].nunique())
print(iso_parents_2021['iso_parent'].nunique())

iso_parents_2021

26
38
46
50
52
52

      iso_parent  year
0            ARE  2021
155          ARG  2021
269          AUS  2021
765          AUT  2021
797          AZE  2021
839          BEL  2021
1008         BGR  2021
1028         BHR  2021
1068         BMU  2021
1649         BRA  2021
1898         CAN  2021
1989         CHE  2021
2727         CHL  2021
2815         CHN  2021
3578         CYM  2021
4141         CZE  2021
4148         DEU  2021
4967         DNK  2021
5624         ESP  2021
6198         FIN  2021
6221         FRA  2021
6779         GBR  2021
6810         GRC  2021
7037         HKG  2021
7582         HUN  2021
7589         IDN  2021
7968         IND  2021
8502         IRL  2021
8514         ITA  2021
9160         JPN  2021
9957         KOR  2021
9982         LTU  2021
10013        LUX  2021
10592        LVA  2021
10665        MAR  2021
10677        MEX  2021
11216        MUS  2021
11236        MYS  2021
11394        NLD  2021
11424        NOR  2021
11701        NZL  2021
11709        PAN  2021
11870        PER  2021
12084        PRT  2021
12232        ROU  2021
12827        SAU  2021
13202        SGP  2021
13381        SVN  2021
13411        SWE  2021
13454        TUR  2021
13602        USA  2021
14468        ZAF  2021

### Step 1.2. Generate the dataset with unique iso_partners

In [3]:
## Download the relevant dataset
iso_partners = pd.read_csv(f'{data_final}/cbcr_main_no_imputation_allsubgroupsonly.csv')

# Exclude country groups
iso_partners = iso_partners[~iso_partners['iso_partner'].isin(non_countries)]

# Keep just the following columns: iso_partner and year
iso_partners = iso_partners[['iso_partner', 'year']]

# Sort by year, then iso_partner
iso_partners = iso_partners.sort_values(by=['year', 'iso_partner'])

# Keep every unique combination of iso_partner and year
iso_partners = iso_partners.drop_duplicates(subset=['iso_partner', 'year'])

# Filter by year
iso_partners_2016= iso_partners[iso_partners['year'] == 2016]
iso_partners_2017= iso_partners[iso_partners['year'] == 2017]
iso_partners_2018= iso_partners[iso_partners['year'] == 2018]
iso_partners_2019= iso_partners[iso_partners['year'] == 2019]
iso_partners_2020= iso_partners[iso_partners['year'] == 2020]
iso_partners_2021= iso_partners[iso_partners['year'] == 2021]


# Optional: Print the count of how many unique iso_partner values there are 
print(iso_partners_2016['iso_partner'].nunique())
print(iso_partners_2017['iso_partner'].nunique())
print(iso_partners_2018['iso_partner'].nunique())
print(iso_partners_2019['iso_partner'].nunique())
print(iso_partners_2020['iso_partner'].nunique())
print(iso_partners_2021['iso_partner'].nunique())

183
215
213
210
212
211

### Step 1.3. Generate the template dataset

In [4]:
# Perform a cross join to merge all values of iso_partners_ with each value of iso_parents
iso_combinations_2016 = iso_parents_2016.assign(key=1).merge(iso_partners_2016.assign(key=1), on='key').drop('key', axis=1)
iso_combinations_2017 = iso_parents_2017.assign(key=1).merge(iso_partners_2017.assign(key=1), on='key').drop('key', axis=1)
iso_combinations_2018 = iso_parents_2018.assign(key=1).merge(iso_partners_2018.assign(key=1), on='key').drop('key', axis=1)
iso_combinations_2019 = iso_parents_2019.assign(key=1).merge(iso_partners_2019.assign(key=1), on='key').drop('key', axis=1)
iso_combinations_2020 = iso_parents_2020.assign(key=1).merge(iso_partners_2020.assign(key=1), on='key').drop('key', axis=1)
iso_combinations_2021 = iso_parents_2021.assign(key=1).merge(iso_partners_2021.assign(key=1), on='key').drop('key', axis=1)

# Concatenate all the years
template_dataset = pd.concat([iso_combinations_2016, iso_combinations_2017, iso_combinations_2018, iso_combinations_2019, iso_combinations_2020, iso_combinations_2021])

# Drop year_y
template_dataset = template_dataset.drop(columns=['year_y'])
# Rename year_x to year
template_dataset = template_dataset.rename(columns={'year_x': 'year'})
# Order columns by iso_parent then iso_partner then year
template_dataset = template_dataset[['iso_parent', 'iso_partner', 'year']]
# Generate new column called cbcr_estimates
template_dataset['cbcr_estimates'] = np.nan

template_dataset

      iso_parent iso_partner  year  cbcr_estimates
0            AUS         ABW  2016             NaN
1            AUS         AFG  2016             NaN
2            AUS         AGO  2016             NaN
3            AUS         ALB  2016             NaN
4            AUS         AND  2016             NaN
...          ...         ...   ...             ...
10967        ZAF         XKV  2021             NaN
10968        ZAF         YEM  2021             NaN
10969        ZAF         ZAF  2021             NaN
10970        ZAF         ZMB  2021             NaN
10971        ZAF         ZWE  2021             NaN

[55222 rows x 4 columns]

## Step 2. Define the misalignment formula

In [5]:
def calculate_misalignment(cbcr_data,
                           formula_vars=['n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",
                                         'stated_capital', 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip'],
                           weights=[.5, 0, 0, .5, 0, 0, 0, 0],
                           profit_var='profit_loss_before_income_tax_corrected',
                           etr_max=0.15): 

    # Create variable with positive profits only for calculating shares
    cbcr_data['profit_var_pos'] = cbcr_data[profit_var]
    cbcr_data.loc[cbcr_data[profit_var] < 0, 'profit_var_pos'] = 0
    cbcr_data['share_profit'] = cbcr_data['profit_var_pos'] / cbcr_data.groupby('iso_parent')['profit_var_pos'].transform('sum')

    # Calculate weighted shares of economic activity
    actual_weights = []
    actual_variables = []
    for i, var in enumerate(formula_vars):
        if var is not None and weights[i] > 0:
            actual_variables.append(f"share_{var}")
            actual_weights.append(weights[i])
            cbcr_data.loc[cbcr_data[var] < 0, var] = 0  # Set economic activity measure to zero if negative
            cbcr_data[f"share_{var}"] = cbcr_data[var] / cbcr_data.groupby('iso_parent')[var].transform('sum')

    # Calculate the share of economic activity
    cbcr_data["share_economy_partner_of_parent"] = (cbcr_data.loc[:, actual_variables] * actual_weights).sum(1, min_count=len(actual_weights))
    # Set economic activity to 1% for those jurisdictions without economic activity but with reported profits
    cbcr_data.loc[(cbcr_data["share_economy_partner_of_parent"] == 0) & (cbcr_data[profit_var] > 0), "share_economy_partner_of_parent"] = 0.01

    # Normalize the economic activity shares to sum to 1
    cbcr_data["share_economy_partner_of_parent"] = cbcr_data["share_economy_partner_of_parent"] / cbcr_data.groupby('iso_parent')["share_economy_partner_of_parent"].transform('sum')

    # Calculate theoretical profit and misaligned profit
    cbcr_data["theoretical_profit"] = cbcr_data["share_economy_partner_of_parent"] * cbcr_data.groupby('iso_parent')[profit_var].transform('sum')
    cbcr_data["misaligned_profit"] = cbcr_data[profit_var] - cbcr_data["theoretical_profit"]

    # Set positive misaligned profits to 0 if ETR exceeds the threshold (etr_max)
    cbcr_data.loc[((cbcr_data["misaligned_profit"] > 0) & (cbcr_data["etr_average_corrected"] > etr_max)), "misaligned_profit"] = 0

    # Adjust misalignment per 'iso_parent'
    def adjust_misalignment(group):
        total_negative_misalignment = group.loc[group["misaligned_profit"] < 0, "misaligned_profit"].sum()
        total_positive_misalignment = group.loc[group["misaligned_profit"] > 0, "misaligned_profit"].sum()
        
        # Adjust negative misalignments to balance positive misalignments within each 'iso_parent'
        if total_negative_misalignment != 0:
            factor = - total_positive_misalignment / total_negative_misalignment
            group.loc[group["misaligned_profit"] < 0, "misaligned_profit"] *= factor
        
        return group

    # Apply the adjustment by grouping by 'iso_parent'
    cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

    return cbcr_data

## Step 3. Calculate misalignment for sample with full information

### Step 3.1 Import data
- Import data without imputed values. This is only the data from the sample of reporting countries that actually is reported on a country basis, i.e. excluding aggregated country groups and data from reporting countries that do not report on a country by country basis, but just by continents.

In [6]:
cbcr_sample = pd.read_csv(f'{data_final}/cbcr_main_no_imputation_allsubgroupsonly.csv')

# Exclude country groups
cbcr_sample = cbcr_sample[~cbcr_sample['iso_partner'].isin(non_countries)]

### Step 3.2 Exclude countries that do not report truly country-by-country


- In the 2024 data, the following reporting countries do not report country-by-country. We exclude those from the "clean" analysis where we only use values that are actually in the data.
    - Austria: Only continents in all years
    - Czechia: Only Czechia versus rest of the world from 2019 to 2021
    - Finland: Only Finland and rest of the world between 2016 and 2018 and Finland and continents between 2019 and 2021
    - Greece: Only Greece and continents between 2017 and 2019
    - Hungary: Only Hungary versus rest of the world between 2018 and 2021
    - Isle of Man: Only continents between 2017 and 2020
    - Ireland: Only Ireland versus rest of the world in all years
    - Korea: Only Korea and rest of the world betweem 2016 and 2018 and Korea and continents between 2019 and 2021
    - Macau: Only Macau versus rest of the world between 2019 and 2021
    - Mauritius: Only Mauritius and continents between 2019 and 2021
    - Morocco: Only Morocco and continents in 2021
    - Netherlands: Only Netherlands versus rest of the world between 2016 and 2017
    - Norway: Only Norway and continents 2016 and 2017
    - New Zealand: Only New Zealand versus rest of the world between 2018 and 2021
    - Poland: Only Poland and continents 2019 to 2021
    - Sweden: Only Sweden and continents in all years
    - United Kingdom: Only UK and continents between 2017 and 2021

In [7]:
# Define the conditions for exclusion
exclusion_conditions = [
    ('AUT', 2016, 2021),                # Austria: all years
    ('CZE', 2019, 2021),                # Czechia: from 2019 to 2021
    ('FIN', 2016, 2021),                # Finland: all years
    ('GRC', 2017, 2019),                # Greece: between 2017 and 2019
    ('HUN', 2018, 2021),                # Hungary: between 2018 and 2021
    ('IMN', 2017, 2020),                # Isle of Man: between 2017 and 2020
    ('IRL', 2016, 2021),                # Ireland: all years
    ('KOR', 2016, 2021),                # Korea: all years
    ('MAC', 2019, 2021),                # Macau: between 2019 and 2021
    ('MUS', 2019, 2021),                # Mauritius: between 2019 and 2021
    ('MAR', 2021, 2021),                # Morocco: 2021
    ('NLD', 2016, 2017),                # Netherlands: between 2016 and 2017
    ('NOR', 2016, 2017),                # Norway: 2016 and 2017
    ('NZL', 2018, 2021),                # New Zealand: between 2018 and 2021
    ('POL', 2019, 2021),                # Poland: 2019 to 2021
    ('SWE', 2016, 2021),                # Sweden: all years
    ('GBR', 2017, 2021)                 # United Kingdom: between 2017 and 2021
]

# Iterate through the exclusion conditions
for iso_parent, start_year, end_year in exclusion_conditions:
    cbcr_sample = cbcr_sample[~((cbcr_sample['iso_parent'] == iso_parent) & 
                                     (cbcr_sample['year'].between(start_year, end_year)))]

### Step 3.3 Calculate misalignment for sample countries with full information

The order of the formula is as follow:

- formula_vars=['n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll", 'stated_capital' 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip']

    - SOTJ: 50% employees, 50% payroll

        - weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0]

    - Canadian formula: 50% employees, 50% sales

        - weights=[1/2, 1/2, 0, 0, 0, 0, 0, 0]

    - CCCTB: 1/6 employees, 1/6 payroll, 1/3 sales, 1/3 assets

        - weights=[1/6, 1/3, 1/3, 1/6, 0, 0, 0, 0]
        
    - Double-weighted sales: 1/4 employees, 1/2 sales, 1/4 assets

        - weights=[1/4, 1/2, 1/4, 0, 0, 0, 0, 0]

    - Three-factor: 1/3 employees, 1/3 sales, 1/3 assets

        - weights=[1/3, 1/3, 1/3, 0, 0, 0, 0, 0]


The end of this cell shows, among other things, the misaligned profits and the theoretical profits, as well as the CBCR variables.

**More importantly, if for whatever reason we wanted to just run this cell without the "bad reporters", we could just modify the cell to run like the cell from Step 5.2. in order to obtain a dataset of profit shifting without the "bad reporters". In a way, this cell is not really necessary for the rest of the notebook. It just shows an intermediary steps if we want to calculate the misalignment for the "good reporters" only.**

In [8]:
misalignment_2021 = cbcr_sample[cbcr_sample['year'] == 2021].copy()

# Calculate the misalignment for 2021
misalignment_2021 = calculate_misalignment(misalignment_2021, etr_max=0.15, weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0])

# Keep only the first occurrence of these unique variables for each 'iso_partner'
unique_columns = misalignment_2021.drop_duplicates(subset=['iso_partner'])[['iso_partner', 'partner_jurisdiction', 
                                                                               'etr_average_corrected', 'cit',
                                                                               'tax_revenue_current_usd', 
                                                                               'gvt_health_expenditure', 'region_tjn', 
                                                                               'ukt', 'oecd', 'oecd_oct', 'nld_oct']]

# Keep iso_parent, iso_partner, year, misaligned_profit, theoretical_profit, profit_loss_before_income_tax_corrected, 'n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",'stated_capital', 'total_revenues', 'related_party_revenues', and 'holding_or_managing_ip'
misalignment_2021 = misalignment_2021[['iso_parent', 'iso_partner', 'year', 'misaligned_profit', 'theoretical_profit', 'profit_loss_before_income_tax_corrected', 'n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",'stated_capital', 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip']]

# Show if iso_partner = USA
misalignment_2021[misalignment_2021['iso_partner'] == 'USA']

/var/folders/pm/bp4z4lln39xcwn73chrtp3n00000gn/T/ipykernel_12769/421381151.py:51: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

,iso_parent,iso_partner,year,misaligned_profit,theoretical_profit,profit_loss_before_income_tax_corrected,n_employees,unrelated_party_revenues,tangible_assets_except_cash,payroll,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip
140,ARE,USA,2021,"-1,211,834,974.55800104","1,676,278,193.97889853","-566,015,448.00000000","28,384.00000000","22,510,101,353.00000000","11,019,650,222.00000000","1,566,840,057.21600008","33,844,332,143.00000000","25,838,686,878.00000000","3,328,585,524.00000000",19.00000000
165,ARG,USA,2021,0.00000000,"9,480,880.09163740","67,155,125.00000000",114.00000000,"113,406,031.00000000","103,940,740.00000000","6,292,973.73600000","1,762,118,722.00000000","132,596,801.00000000","19,190,770.00000000",2.00000000
245,AUS,USA,2021,0.00000000,"7,200,422,731.80306339","8,095,396,499.00000000","89,401.00000000","57,209,834,217.00000000","37,039,556,556.00000000","4,935,071,447.12400055","174,000,000,000.00000000","73,738,510,494.00000000","16,528,676,277.00000000",27.00000000
285,AZE,USA,2021,"-8,636,245.39224626","10,751,113.69069204","-5,934,134.00000000",21.00000000,"748,376,581.00000000","7,712,734.00000000","1,159,232.00400000","20,001,000.00000000","751,937,979.00000000","3,561,398.00000000",NaN
314,BEL,USA,2021,"-553,930,903.10677862","3,029,537,331.16806984","2,376,700,000.00000000","58,400.00000000","43,812,500,000.00000000","14,989,500,000.00000000","3,223,769,001.60000038","380,000,000,000.00000000","54,828,300,000.00000000","11,015,800,000.00000000",25.00000000
353,BHR,USA,2021,0.00000000,"5,748,649.02508260","28,628,903.00000000",46.00000000,"31,352,002.00000000","494,407.00000000","2,539,270.10400000","1,253,597.00000000","491,165,142.00000000","459,813,140.00000000",NaN
441,BMU,USA,2021,"-2,631,136,978.25879192","11,377,613,393.12938690","8,368,805,189.00000000","95,211.00000000","87,810,248,119.00000000","43,717,634,640.00000000","5,255,792,301.56400108","75,203,353,654.00000000","109,000,000,000.00000000","21,625,977,894.00000000",16.00000000
480,BRA,USA,2021,"-1,561,921,714.71748805","12,227,561,481.76749611","10,586,870,772.00000000","121,286.00000000","68,461,937,528.00000000","17,087,060,697.00000000","6,695,172,039.86400032","47,722,813,871.00000000","79,304,813,607.00000000","10,842,876,078.00000000",20.00000000
493,CAN,USA,2021,"-62,835,521,174.61859131","120,748,616,174.61856079","57,913,095,000.00000000","867,200.00000000","448,000,000,000.00000000","440,000,000,000.00000000","47,870,761,612.80000305","1,150,000,000,000.00000000","561,000,000,000.00000000","112,000,000,000.00000000",NaN
623,CHE,USA,2021,"-2,611,278,125.47509575","17,075,485,567.54924774","13,563,295,251.00000000","303,765.00000000","267,000,000,000.00000000","91,543,939,101.00000000","16,768,290,937.86000443","398,000,000,000.00000000","334,000,000,000.00000000","67,308,695,757.00000000",64.00000000
642,CHL,USA,2021,"-1,632,046,372.57953024","2,362,555,639.68666363","569,080,541.00000000","7,614.00000000","6,316,805,695.00000000","1,863,664,102.00000000","420,304,403.73600000","3,773,832,021.00000000","6,487,770,036.00000000","170,964,341.00000000",0.00000000
766,CHN,USA,2021,"-12,100,468,568.67882538","13,544,803,307.67666245","-54,418,982.00000000","84,266.00000000","114,000,000,000.00000000","63,306,614,237.00000000","4,651,611,621.38399982","75,432,933,414.00000000","175,000,000,000.00000000","61,042,227,499.00000000",97.00000000
898,CYM,USA,2021,"-6,323,062,008.73868561","7,798,228,428.64260578","1,392,788,410.00000000","62,243.00000000","38,176,084,571.00000000","9,343,614,768.00000000","3,435,908,458.33199978","19,813,279,525.00000000","47,309,937,896.00000000","9,133,853,328.00000000",39.00000000
1060,DEU,USA,2021,0.00000000,"22,193,446,156.30993271","24,047,033,000.00000000","719,133.00000000","553,000,000,000.00000000","293,000,000,000.00000000","39,697,237,558.69200134","595,000,000,000.00000000","704,000,000,000.00000000","152,000,000,000.00000000",273.00000000
1169,DNK,USA,2021,"-2,841,852,928.11992311","6,103,813,014.13747501","3,243,137,161.00000000","73,241.00000000","45,485,959,763.00000000","25,104,263,012.00000000","4,043,014,819.28399992","51,448,797,455.00000000","60,390,018,377.00000000","14,904,058,614.00000000",27.00000000
1274,ESP,USA,2021,0.00000000,"6,524,975,192.74174595","10,527,379,930.00000000","109,801.00000000","79,067,644,471.00000000","88,909,492,659.00000000","6,061,182,536.72400093","74,509,895,692.00000000","91,002,422,172.00000000","11,934,777,701.00000000",43.00000000
1366,FRA,USA,2021,0.00000000,"18,561,919,378.97323608","18,794,938,537.00000000","524,681.00000000","294,000,000,000.00000000","90,590,541,274.00000000","28,963,190,813.84400177","264,000,000,000.00000000","376,000,000,000.00000000","82,591,027,820.00000000",327.00000000
1436,GRC,USA,2021,"-83,522,653.98860347","-789,661.45939972","-120,699,170.00000000",21.00000000,"3,393,241.00000000","5,308,687.00000000","1,159,232.00400000","164,536,615.00000000","3,393,241.00000000",0.00000000,0.00000000
1575,HKG,USA,2021,"-7,807,664,506.12573719","8,194,241,330.27444935","162,587,382.00000000","67,742.00000000","38,239,355,286.00000000","20,183,558,893.00000000","3,739,461,638.80800056","35,933,512,017.00000000","73,359,535,957.00000000","35,120,180,670.00000000",50.00000000
1658,IDN,USA,2021,"-81,106,348.95574577","502,426,601.98766530","268,989,845.00000000","4,573.00000000","2,582,787,240.00000000","807,463,833.00000000","252,436,569.25200003","4,017,837,203.00000000","3,296,862,710.00000000","714,075,470.00000000",11.00000000
1750,IND,USA,2021,"-782,129,665.89467418","30,330,391,978.85036087","-331,745,994.00000000","584,497.00000000","43,251,114,389.00000000","25,160,717,354.00000000","32,265,125,173.42800522","36,245,763,120.00000000","98,162,899,613.00000000","54,911,785,225.00000000",4.00000000
1850,ITA,USA,2021,"-1,036,767,327.85335445","4,799,257,744.71001053","3,521,381,888.00000000","66,451.00000000","38,410,342,400.00000000","25,715,773,440.00000000","3,668,196,471.32399988","56,180,838,400.00000000","44,698,591,232.00000000","6,289,369,600.00000000",40.00000000
1984,JPN,USA,2021,0.00000000,"40,508,057,520.81279755","43,932,684,793.00000000","939,003.00000000","755,000,000,000.00000000","321,000,000,000.00000000","51,834,396,640.57200623","412,000,000,000.00000000","996,000,000,000.00000000","241,000,000,000.00000000",332.00000000
2095,LUX,USA,2021,"-8,093,033,667.75142574","15,789,709,806.91709518","4,473,429,202.00000000","1,121,870.00000000","169,000,000,000.00000000","33,506,463,047.00000000","61,928,933,729.88000488","63,189,786,791.00000000","210,000,000,000.00000000","41,633,694,079.00000000",53.00000000
2195,MEX,USA,2021,"-1,010,758,730.75460935","9,711,156,446.34226608","5,016,010,454.00000000","83,674.00000000","41,306,870,980.00000000","19,464,236,857.00000000","4,618,932,319.17600060","22,696,891,231.00000000","46,821,542,963.00000000","5,514,671,983.00000000",12.00000000
2229,MYS,USA,2021,"-493,298,887.01552653","933,657,836.72440434","-474,789,258.00000000","6,708.00000000","1,717,498,924.00000000","6,786,997,652.00000000","370,291,822.99199998","5,757,646,533.00000000","1,858,412,897.00000000","140,913,973.00000000",4.00000000
2295,NOR,USA,2021,"-2,105,464.06278693","2,964,144,967.61032629","2,920,130,000.00000000","16,570.00000000","22,473,752,000.00000000","13,334,348,000.00000000","914,689,252.67999995","97,712,537,000.00000000","32,237,860,000.00000000","9,764,108,000.00000000",3.00000000
2330,PER,USA,2021,"-7,674,484.35775719","8,943,425.35775719","1,268,941.00000000",42.00000000,"3,663,071.00000000","28,918,750.00000000","2,318,464.00800000","1,191,917.00000000","35,339,373.00000000","31,676,302.00000000",0.00000000
2376,PRT,USA,2021,0.00000000,"103,312,312.56636617","590,203,601.00000000","1,714.00000000","2,393,887,094.00000000","9,326,699,236.00000000","94,615,412.13600001","19,586,573,404.00000000","2,630,610,509.00000000","236,723,416.00000000",1.00000000
2516,ROU,USA,2021,"-7,799,937.90482194","101,265,126.92087756","28,381,338.00000000",294.00000000,"30,338,521.00000000","26,767,822.00000000","16,229,248.05600000","13,096,423.00000000","223,956,163.00000000","193,617,643.00000000",0.00000000
2627,SAU,USA,2021,"-86,335,875.43999305","53,185,708,424.37676239","22,846,301,764.00000000","58,288.00000000","132,000,000,000.00000000","46,670,751,675.00000000","3,217,586,430.91200066","186,000,000,000.00000000","159,000,000,000.00000000","26,167,020,621.00000000",3.00000000
2663,SGP,USA,2021,"-959,288,414.55556309","1,333,469,717.48492289","-562,409,531.00000000","18,849.00000000","40,401,573,647.00000000","16,384,908,659.00000000","1,040,493,525.87600017","18,428,670,984.00000000","62,215,984,112.00000000","21,814,410,466.00000000",8.00000000
2698,TUR,USA,2021,"-14,257,365.59723319","386,816,437.41480798","93,134,196.00000000","3,299.00000000","2,760,109,917.00000000","1,862,989,215.00000000","182,109,827.67600000","5,668,969,140.00000000","3,539,054,769.00000000","778,944,852.00000000",1.00000000
2828,USA,USA,2021,0.00000000,"1,776,148,896,070.53979492","1,850,000,000,000.00000000","23,963,059.00000000","13,300,000,000,000.00000000","7,670,000,000,000.00000000","1,322,797,376,501.91601562","17,800,000,000,000.00000000","17,700,000,000,000.00000000","4,370,000,000,000.00000000",NaN
2868,ZAF,USA,2021,"-708,316,723.69053781","783,643,876.08581722","-80,276,898.00000000","7,486.00000000","5,356,980,538.00000000","8,847,092,554.00000000","413,238,608.66399997","12,208,042,858.00000000","5,741,637,926.00000000","384,657,388.00000000",2.00000000

## Step 4. Generate the dataset for the "bad reporters"

For the "bad" reporters, we are going to assume that their MNEs behave like the "average" MNE in the countries that report correctly. To do that we need to:

1. First aggregate the variables reported by the CBCR by partner countries. For instance, we see that on aggregate, there are 80m employees reported.
2. Then we look at the share corresponding by partners. For instance, 18m employees are reported in the USA. how many does the USA have. In short, roughly 24% of all employees reported are in the USA.
3. We then assume that 24% of the toal employees reported by the "bad" reporters are assigned to the US. And we repeat with all of them



### Step 4.1. Generate the Total Sums of Variables, and the Total Sums by Partners.

- The first bloc of lines calculates the total of the variables, and generates a new variable (e.g. total_n_employees) in the dataset.
- The second bloc of lines groups by iso_partner and calculates the total sums by partners. (e.g. how many employees are reported by the CBCR countries, say, in the USA)
- The third bloc of lines merges the total sums by partners to the dataset

In [9]:
# Calculate the total sum of profit_loss_before_income_tax_corrected, 'n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",'stated_capital', 'total_revenues', 'related_party_revenues', and 'holding_or_managing_ip'
total_profit_loss_before_income_tax_corrected = misalignment_2021['profit_loss_before_income_tax_corrected'].sum()
total_n_employees = misalignment_2021['n_employees'].sum()
total_unrelated_party_revenues = misalignment_2021['unrelated_party_revenues'].sum()
total_tangible_assets_except_cash = misalignment_2021['tangible_assets_except_cash'].sum()
total_payroll = misalignment_2021['payroll'].sum()
total_stated_capital = misalignment_2021['stated_capital'].sum()
total_total_revenues = misalignment_2021['total_revenues'].sum()
total_related_party_revenues = misalignment_2021['related_party_revenues'].sum()
total_holding_or_managing_ip = misalignment_2021['holding_or_managing_ip'].sum()

misalignment_2021['total_profit_loss_before_income_tax_corrected'] = total_profit_loss_before_income_tax_corrected
misalignment_2021['total_n_employees'] = total_n_employees
misalignment_2021['total_unrelated_party_revenues'] = total_unrelated_party_revenues
misalignment_2021['total_tangible_assets_except_cash'] = total_tangible_assets_except_cash
misalignment_2021['total_payroll'] = total_payroll
misalignment_2021['total_stated_capital'] = total_stated_capital
misalignment_2021['total_total_revenues'] = total_total_revenues
misalignment_2021['total_related_party_revenues'] = total_related_party_revenues
misalignment_2021['total_holding_or_managing_ip'] = total_holding_or_managing_ip

# Group by iso_partner and calculate the total sum of profit_loss_before_income_tax_corrected, 'n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",'stated_capital', 'total_revenues', 'related_party_revenues', and 'holding_or_managing_ip'
total_profit_loss_by_partner = misalignment_2021.groupby('iso_partner')['profit_loss_before_income_tax_corrected'].sum().reset_index()
total_profit_loss_by_partner = total_profit_loss_by_partner.rename(columns={'profit_loss_before_income_tax_corrected': 'total_profit_loss_by_partner'})

total_n_employees_by_partner = misalignment_2021.groupby('iso_partner')['n_employees'].sum().reset_index()
total_n_employees_by_partner = total_n_employees_by_partner.rename(columns={'n_employees': 'total_n_employees_by_partner'})

total_unrelated_party_revenues_by_partner = misalignment_2021.groupby('iso_partner')['unrelated_party_revenues'].sum().reset_index()
total_unrelated_party_revenues_by_partner = total_unrelated_party_revenues_by_partner.rename(columns={'unrelated_party_revenues': 'total_unrelated_party_revenues_by_partner'})

total_tangible_assets_except_cash_by_partner = misalignment_2021.groupby('iso_partner')['tangible_assets_except_cash'].sum().reset_index()
total_tangible_assets_except_cash_by_partner = total_tangible_assets_except_cash_by_partner.rename(columns={'tangible_assets_except_cash': 'total_tangible_assets_except_cash_by_partner'})

total_payroll_by_partner = misalignment_2021.groupby('iso_partner')['payroll'].sum().reset_index()
total_payroll_by_partner = total_payroll_by_partner.rename(columns={'payroll': 'total_payroll_by_partner'})

total_stated_capital_by_partner = misalignment_2021.groupby('iso_partner')['stated_capital'].sum().reset_index()
total_stated_capital_by_partner = total_stated_capital_by_partner.rename(columns={'stated_capital': 'total_stated_capital_by_partner'})

total_total_revenues_by_partner = misalignment_2021.groupby('iso_partner')['total_revenues'].sum().reset_index()
total_total_revenues_by_partner = total_total_revenues_by_partner.rename(columns={'total_revenues': 'total_total_revenues_by_partner'})

total_related_party_revenues_by_partner = misalignment_2021.groupby('iso_partner')['related_party_revenues'].sum().reset_index()
total_related_party_revenues_by_partner = total_related_party_revenues_by_partner.rename(columns={'related_party_revenues': 'total_related_party_revenues_by_partner'})

total_holding_or_managing_ip_by_partner = misalignment_2021.groupby('iso_partner')['holding_or_managing_ip'].sum().reset_index()
total_holding_or_managing_ip_by_partner = total_holding_or_managing_ip_by_partner.rename(columns={'holding_or_managing_ip': 'total_holding_or_managing_ip_by_partner'})

# Merge the total profit loss by partner back into the misalignment_2021 dataframe
misalignment_2021 = misalignment_2021.merge(total_profit_loss_by_partner, on='iso_partner', how='left')
misalignment_2021 = misalignment_2021.merge(total_n_employees_by_partner, on='iso_partner', how='left')
misalignment_2021 = misalignment_2021.merge(total_unrelated_party_revenues_by_partner, on='iso_partner', how='left')
misalignment_2021 = misalignment_2021.merge(total_tangible_assets_except_cash_by_partner, on='iso_partner', how='left')
misalignment_2021 = misalignment_2021.merge(total_payroll_by_partner, on='iso_partner', how='left')
misalignment_2021 = misalignment_2021.merge(total_stated_capital_by_partner, on='iso_partner', how='left')
misalignment_2021 = misalignment_2021.merge(total_total_revenues_by_partner, on='iso_partner', how='left')
misalignment_2021 = misalignment_2021.merge(total_related_party_revenues_by_partner, on='iso_partner', how='left')
misalignment_2021 = misalignment_2021.merge(total_holding_or_managing_ip_by_partner, on='iso_partner', how='left')

misalignment_2021[misalignment_2021['iso_partner'] == 'USA']

,iso_parent,iso_partner,year,misaligned_profit,theoretical_profit,profit_loss_before_income_tax_corrected,n_employees,unrelated_party_revenues,tangible_assets_except_cash,payroll,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip,total_profit_loss_before_income_tax_corrected,total_n_employees,total_unrelated_party_revenues,total_tangible_assets_except_cash,total_payroll,total_stated_capital,total_total_revenues,total_related_party_revenues,total_holding_or_managing_ip,total_profit_loss_by_partner,total_n_employees_by_partner,total_unrelated_party_revenues_by_partner,total_tangible_assets_except_cash_by_partner,total_payroll_by_partner,total_stated_capital_by_partner,total_total_revenues_by_partner,total_related_party_revenues_by_partner,total_holding_or_managing_ip_by_partner
140,ARE,USA,2021,"-1,211,834,974.55800104","1,676,278,193.97889853","-566,015,448.00000000","28,384.00000000","22,510,101,353.00000000","11,019,650,222.00000000","1,566,840,057.21600008","33,844,332,143.00000000","25,838,686,878.00000000","3,328,585,524.00000000",19.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
165,ARG,USA,2021,0.00000000,"9,480,880.09163740","67,155,125.00000000",114.00000000,"113,406,031.00000000","103,940,740.00000000","6,292,973.73600000","1,762,118,722.00000000","132,596,801.00000000","19,190,770.00000000",2.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
245,AUS,USA,2021,0.00000000,"7,200,422,731.80306339","8,095,396,499.00000000","89,401.00000000","57,209,834,217.00000000","37,039,556,556.00000000","4,935,071,447.12400055","174,000,000,000.00000000","73,738,510,494.00000000","16,528,676,277.00000000",27.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
285,AZE,USA,2021,"-8,636,245.39224626","10,751,113.69069204","-5,934,134.00000000",21.00000000,"748,376,581.00000000","7,712,734.00000000","1,159,232.00400000","20,001,000.00000000","751,937,979.00000000","3,561,398.00000000",NaN,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
314,BEL,USA,2021,"-553,930,903.10677862","3,029,537,331.16806984","2,376,700,000.00000000","58,400.00000000","43,812,500,000.00000000","14,989,500,000.00000000","3,223,769,001.60000038","380,000,000,000.00000000","54,828,300,000.00000000","11,015,800,000.00000000",25.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
353,BHR,USA,2021,0.00000000,"5,748,649.02508260","28,628,903.00000000",46.00000000,"31,352,002.00000000","494,407.00000000","2,539,270.10400000","1,253,597.00000000","491,165,142.00000000","459,813,140.00000000",NaN,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
441,BMU,USA,2021,"-2,631,136,978.25879192","11,377,613,393.12938690","8,368,805,189.00000000","95,211.00000000","87,810,248,119.00000000","43,717,634,640.00000000","5,255,792,301.56400108","75,203,353,654.00000000","109,000,000,000.00000000","21,625,977,894.00000000",16.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
480,BRA,USA,2021,"-1,561,921,714.71748805","12,227,561,481.76749611","10,586,870,772.00000000","121,286.00000000","68,461,937,528.00000000","17,087,060,697.00000000","6,695,172,039.86400032","47,722,813,871.00000000","79,304,813,607.00000000","10,842,876,078.00000000",20.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
493,CAN,USA,2021,"-62,835,521,174.61859131","120,748,616,174.61856079","57,913,095,000.00000000","867,200.00000000","448,000,000,000.00000000","440,000,000,000.00000000","47,870,761,612.80000305","1,150,000,000,000.00000000","561,000,000,000.00000000","112,000,000,000.00000000",NaN,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
623,CHE,USA,2021,"-2,611,278,125.47509575","17,075,485,567.54924774","13,563,295,251.00000000","303,765.00000000","267,000,000,000.00000000","91,543,939,101.00000000","16,768,290,937.86000443","398,000,000,000.00000000","334,000,000,000.00000000","67,308,695,757.00000000",64.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
642,CHL,USA,2021,"-1,632,046,372.57953024","2,362,555,639.68666363","569,080,541.00000000","7,614.00000000","6,316,805,695.00000000","1,863,664,102.00000000","420,304,403.73600000","3,773,832,021.00000000","6,487,770,036.00000000","170,964,341.00000000",0.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
766,CHN,USA,2021,"-12,100,468,568.67882538","13,544,803,307.67666245","-54,418,982.00000000","84,266.00000000","114,000,000,000.00000000","63,306,614,237.00000000","4,651,611,621.38399982","75,432,933,414.00000000","175,000,000,000.00000000","61,042,227,499.00000000",97.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
898,CYM,USA,2021,"-6,323,062,008.73868561","7,798,228,428.64260578","1,392,788,410.00000000","62,243.00000000","38,176,084,571.00000000","9,343,614,768.00000000","3,435,908,458.33199978","19,813,279,525.00000000","47,309,937,896.00000000","9,133,853,328.00000000",39.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
1060,DEU,USA,2021,0.00000000,"22,193,446,156.30993271","24,047,033,000.00000000","719,133.00000000","553,000,000,000.00000000","293,000,000,000.00000000","39,697,237,558.69200134","595,000,000,000.00000000","704,000,000,000.00000000","152,000,000,000.00000000",273.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
1169,DNK,USA,2021,"-2,841,852,928.11992311","6,103,813,014.13747501","3,243,137,161.00000000","73,241.00000000","45,485,959,763.00000000","25,104,263,012.00000000","4,043,014,819.28399992","51,448,797,455.00000000","60,390,018,377.00000000","14,904,058,614.00000000",27.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
1274,ESP,USA,2021,0.00000000,"6,524,975,192.74174595","10,527,379,930.00000000","109,801.00000000","79,067,644,471.00000000","88,909,492,659.00000000","6,061,182,536.72400093","74,509,895,692.00000000","91,002,422,172.00000000","11,934,777,701.00000000",43.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
1366,FRA,USA,2021,0.00000000,"18,561,919,378.97323608","18,794,938,537.00000000","524,681.00000000","294,000,000,000.00000000","90,590,541,274.00000000","28,963,190,813.84400177","264,000,000,000.00000000","376,000,000,000.00000000","82,591,027,820.00000000",327.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
1436,GRC,USA,2021,"-83,522,653.98860347","-789,661.45939972","-120,699,170.00000000",21.00000000,"3,393,241.00000000","5,308,687.00000000","1,159,232.00400000","164,536,615.00000000","3,393,241.00000000",0.00000000,0.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
1575,HKG,USA,2021,"-7,807,664,506.12573719","8,194,241,330.27444935","162,587,382.00000000","67,742.00000000","38,239,355,286.00000000","20,183,558,893.00000000","3,739,461,638.80800056","35,933,512,017.00000000","73,359,535,957.00000000","35,120,180,670.00000000",50.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
1658,IDN,USA,2021,"-81,106,348.95574577","502,426,601.98766530","268,989,845.00000000","4,573.00000000","2,582,787,240.00000000","807,463,833.00000000","252,436,569.25200003","4,017,837,203.00000000","3,296,862,710.00000000","714,075,470.00000000",11.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
1750,IND,USA,2021,"-782,129,665.89467418","30,330,391,978.85036087","-331,745,994.00000000","584,497.00000000","43,251,114,389.00000000","25,160,717,354.00000000","32,265,125,173.42800522","36,245,763,120.00000000","98,162,899,613.00000000","54,911,785,225.00000000",4.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
1850,ITA,USA,2021,"-1,036,767,327.85335445","4,799,257,744.71001053","3,521,381,888.00000000","66,451.00000000","38,410,342,400.00000000","25,715,773,440.00000000","3,668,196,471.32399988","56,180,838,400.00000000","44,698,591,232.00000000","6,289,369,600.00000000",40.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
1984,JPN,USA,2021,0.00000000,"40,508,057,520.81279755","43,932,684,793.00000000","939,003.00000000","755,000,000,000.00000000","321,000,000,000.00000000","51,834,396,640.57200623","412,000,000,000.00000000","996,000,000,000.00000000","241,000,000,000.00000000",332.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
2095,LUX,USA,2021,"-8,093,033,667.75142574","15,789,709,806.91709518","4,473,429,202.00000000","1,121,870.00000000","169,000,000,000.00000000","33,506,463,047.00000000","61,928,933,729.88000488","63,189,786,791.00000000","210,000,000,000.00000000","41,633,694,079.00000000",53.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"
2195,MEX,USA,2021,"-1,010,758,730.75460935","9,711,156,446.34226608","5,016,010,454.00000000","83,674.00000000","41,306,870,980.00000000","19,464,236,857.00000000","4,618,932,319.17600060","22,696,891,231.00000000","46,821,542,963.00000000","5,514,671,983.00000000",12.00000000,"7,762,091,416,141.00000000","157,545,260.00000000","61,215,345,239,302.00000000","42,955,732,312,253.00000000","4,519,767,206,421.00683594","107,533,344,406,981.00000000","86,567,376,841,818.00000000","25,321,553,863,775.00000000","22,468.00000000","2,091,232,518,307.00000000","30,088,947.00000000","16,720,675,917,579.00000000","9,446,740,674,823.00000000","1,660,955,729,955.22802734","22,120,338,504,730.00000000","22,139,101,840,847.00000000","5,389,605,935,829.00000000","1,503.00000000"

### Step 4.2. Calculate the shares for all the variables

In [10]:
# Final Misalignment
final_misalignment_2021 = misalignment_2021

# Calculate the shares for all variables
final_misalignment_2021['share_reported_total_profit_loss_by_partner'] = misalignment_2021['total_profit_loss_by_partner'] / misalignment_2021['total_profit_loss_before_income_tax_corrected']
final_misalignment_2021['share_reported_total_n_employees_by_partner'] = misalignment_2021['total_n_employees_by_partner'] / misalignment_2021['total_n_employees']
final_misalignment_2021['share_reported_total_unrelated_party_revenues_by_partner'] = misalignment_2021['total_unrelated_party_revenues_by_partner'] / misalignment_2021['total_unrelated_party_revenues']
final_misalignment_2021['share_reported_total_tangible_assets_except_cash_by_partner'] = misalignment_2021['total_tangible_assets_except_cash_by_partner'] / misalignment_2021['total_tangible_assets_except_cash']
final_misalignment_2021['share_reported_total_payroll_by_partner'] = misalignment_2021['total_payroll_by_partner'] / misalignment_2021['total_payroll']
final_misalignment_2021['share_reported_total_stated_capital_by_partner'] = misalignment_2021['total_stated_capital_by_partner'] / misalignment_2021['total_stated_capital']
final_misalignment_2021['share_reported_total_total_revenues_by_partner'] = misalignment_2021['total_total_revenues_by_partner'] / misalignment_2021['total_total_revenues']
final_misalignment_2021['share_reported_total_related_party_revenues_by_partner'] = misalignment_2021['total_related_party_revenues_by_partner'] / misalignment_2021['total_related_party_revenues']
final_misalignment_2021['share_reported_total_holding_or_managing_ip_by_partner'] = misalignment_2021['total_holding_or_managing_ip_by_partner'] / misalignment_2021['total_holding_or_managing_ip']

# Give me column 'share reported' with 2 decimals
pd.options.display.float_format = '{:,.2f}'.format

final_misalignment_2021[final_misalignment_2021['iso_partner'] == 'USA']

,iso_parent,iso_partner,year,misaligned_profit,theoretical_profit,profit_loss_before_income_tax_corrected,n_employees,unrelated_party_revenues,tangible_assets_except_cash,payroll,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip,total_profit_loss_before_income_tax_corrected,total_n_employees,total_unrelated_party_revenues,total_tangible_assets_except_cash,total_payroll,total_stated_capital,total_total_revenues,total_related_party_revenues,total_holding_or_managing_ip,total_profit_loss_by_partner,total_n_employees_by_partner,total_unrelated_party_revenues_by_partner,total_tangible_assets_except_cash_by_partner,total_payroll_by_partner,total_stated_capital_by_partner,total_total_revenues_by_partner,total_related_party_revenues_by_partner,total_holding_or_managing_ip_by_partner,share_reported_total_profit_loss_by_partner,share_reported_total_n_employees_by_partner,share_reported_total_unrelated_party_revenues_by_partner,share_reported_total_tangible_assets_except_cash_by_partner,share_reported_total_payroll_by_partner,share_reported_total_stated_capital_by_partner,share_reported_total_total_revenues_by_partner,share_reported_total_related_party_revenues_by_partner,share_reported_total_holding_or_managing_ip_by_partner
140,ARE,USA,2021,"-1,211,834,974.56","1,676,278,193.98","-566,015,448.00","28,384.00","22,510,101,353.00","11,019,650,222.00","1,566,840,057.22","33,844,332,143.00","25,838,686,878.00","3,328,585,524.00",19.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
165,ARG,USA,2021,0.00,"9,480,880.09","67,155,125.00",114.00,"113,406,031.00","103,940,740.00","6,292,973.74","1,762,118,722.00","132,596,801.00","19,190,770.00",2.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
245,AUS,USA,2021,0.00,"7,200,422,731.80","8,095,396,499.00","89,401.00","57,209,834,217.00","37,039,556,556.00","4,935,071,447.12","174,000,000,000.00","73,738,510,494.00","16,528,676,277.00",27.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
285,AZE,USA,2021,"-8,636,245.39","10,751,113.69","-5,934,134.00",21.00,"748,376,581.00","7,712,734.00","1,159,232.00","20,001,000.00","751,937,979.00","3,561,398.00",NaN,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
314,BEL,USA,2021,"-553,930,903.11","3,029,537,331.17","2,376,700,000.00","58,400.00","43,812,500,000.00","14,989,500,000.00","3,223,769,001.60","380,000,000,000.00","54,828,300,000.00","11,015,800,000.00",25.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
353,BHR,USA,2021,0.00,"5,748,649.03","28,628,903.00",46.00,"31,352,002.00","494,407.00","2,539,270.10","1,253,597.00","491,165,142.00","459,813,140.00",NaN,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
441,BMU,USA,2021,"-2,631,136,978.26","11,377,613,393.13","8,368,805,189.00","95,211.00","87,810,248,119.00","43,717,634,640.00","5,255,792,301.56","75,203,353,654.00","109,000,000,000.00","21,625,977,894.00",16.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
480,BRA,USA,2021,"-1,561,921,714.72","12,227,561,481.77","10,586,870,772.00","121,286.00","68,461,937,528.00","17,087,060,697.00","6,695,172,039.86","47,722,813,871.00","79,304,813,607.00","10,842,876,078.00",20.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
493,CAN,USA,2021,"-62,835,521,174.62","120,748,616,174.62","57,913,095,000.00","867,200.00","448,000,000,000.00","440,000,000,000.00","47,870,761,612.80","1,150,000,000,000.00","561,000,000,000.00","112,000,000,000.00",NaN,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
623,CHE,USA,2021,"-2,611,278,125.48","17,075,485,567.55","13,563,295,251.00","303,765.00","267,000,000,000.00","91,543,939,101.00","16,768,290,937.86","398,000,000,000.00","334,000,000,000.00","67,308,695,757.00",64.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
642,CHL,USA,2021,"-1,632,046,372.58","2,362,555,639.69","569,080,541.00","7,614.00","6,316,805,695.00","1,863,664,102.00","420,304,403.74","3,773,832,021.00","6,487,770,036.00","170,964,341.00",0.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
766,CHN,USA,2021,"-12,100,468,568.68","13,544,803,307.68","-54,418,982.00","84,266.00","114,000,000,000.00","63,306,614,237.00","4,651,611,621.38","75,432,933,414.00","175,000,000,000.00","61,042,227,499.00",97.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
898,CYM,USA,2021,"-6,323,062,008.74","7,798,228,428.64","1,392,788,410.00","62,243.00","38,176,084,571.00","9,343,614,768.00","3,435,908,458.33","19,813,279,525.00","47,309,937,896.00","9,133,853,328.00",39.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1060,DEU,USA,2021,0.00,"22,193,446,156.31","24,047,033,000.00","719,133.00","553,000,000,000.00","293,000,000,000.00","39,697,237,558.69","595,000,000,000.00","704,000,000,000.00","152,000,000,000.00",273.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1169,DNK,USA,2021,"-2,841,852,928.12","6,103,813,014.14","3,243,137,161.00","73,241.00","45,485,959,763.00","25,104,263,012.00","4,043,014,819.28","51,448,797,455.00","60,390,018,377.00","14,904,058,614.00",27.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1274,ESP,USA,2021,0.00,"6,524,975,192.74","10,527,379,930.00","109,801.00","79,067,644,471.00","88,909,492,659.00","6,061,182,536.72","74,509,895,692.00","91,002,422,172.00","11,934,777,701.00",43.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1366,FRA,USA,2021,0.00,"18,561,919,378.97","18,794,938,537.00","524,681.00","294,000,000,000.00","90,590,541,274.00","28,963,190,813.84","264,000,000,000.00","376,000,000,000.00","82,591,027,820.00",327.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1436,GRC,USA,2021,"-83,522,653.99","-789,661.46","-120,699,170.00",21.00,"3,393,241.00","5,308,687.00","1,159,232.00","164,536,615.00","3,393,241.00",0.00,0.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1575,HKG,USA,2021,"-7,807,664,506.13","8,194,241,330.27","162,587,382.00","67,742.00","38,239,355,286.00","20,183,558,893.00","3,739,461,638.81","35,933,512,017.00","73,359,535,957.00","35,120,180,670.00",50.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1658,IDN,USA,2021,"-81,106,348.96","502,426,601.99","268,989,845.00","4,573.00","2,582,787,240.00","807,463,833.00","252,436,569.25","4,017,837,203.00","3,296,862,710.00","714,075,470.00",11.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1750,IND,USA,2021,"-782,129,665.89","30,330,391,978.85","-331,745,994.00","584,497.00","43,251,114,389.00","25,160,717,354.00","32,265,125,173.43","36,245,763,120.00","98,162,899,613.00","54,911,785,225.00",4.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1850,ITA,USA,2021,"-1,036,767,327.85","4,799,257,744.71","3,521,381,888.00","66,451.00","38,410,342,400.00","25,715,773,440.00","3,668,196,471.32","56,180,838,400.00","44,698,591,232.00","6,289,369,600.00",40.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1984,JPN,USA,2021,0.00,"40,508,057,520.81","43,932,684,793.00","939,003.00","755,000,000,000.00","321,000,000,000.00","51,834,396,640.57","412,000,000,000.00","996,000,000,000.00","241,000,000,000.00",332.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
2095,LUX,USA,2021,"-8,093,033,667.75","15,789,709,806.92","4,473,429,202.00","1,121,870.00","169,000,000,000.00","33,506,463,047.00","61,928,933,729.88","63,189,786,791.00","210,000,000,000.00","41,633,694,079.00",53.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
2195,MEX,USA,2021,"-1,010,758,730.75","9,711,156,446.34","5,016,010,454.00","83,674.00","41,306,870,980.00","19,464,236,857.00","4,618,932,319.18","22,696,891,231.00","46,821,542,963.00","5,514,671,983.00",12.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
2229,MYS,USA,2021,"-493,298,887.02","933,657,836.72","-474,789,258.00","6,708.00","1,717,498,924.00","6,786,997,652.00","370,291,822.99","5,757,646,533.00","1,858,412,897.00","140,913,973.00",4.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
2295,NOR,USA,2021,"-2,105,464.06","2,964,144,967.61","2,920,130,000.00","16,570.00","22,473,752,000.00","13,334,348,000.00","914,689,252.68","97,712,537,000.00","32,237,860,000.00","9,764,108,000.00",3.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
2330,PER,USA,2021,"-7,674,484.36","8,943,425.36","1,268,941.00",42.00,"3,663,071.00","28,918,750.00","2,318,464.01","1,191,917.00","35,339,373.00","31,676,302.00",0.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
2376,PRT,USA,2021,0.00,"103,312,312.57","590,203,601.00","1,714.00","2,393,887,094.00","9,326,699,236.00","94,615,412.14","19,586,573,404.00","2,630,610,509.00","236,723,416.00",1.00,"7,762,091,416,141.00","157,545,260.00","61,215,345,239,302.00","42,955,732,312,253.00","4,519,767,206,421.01","107,533,344,406,981.00","86,567,376,841,818.00","25,321,553,863,775.00","22,468.00","2,091,232,518,307.00","30,088,947.00","16,720,675,917,579.00","9,446,740,674,823.00","1,660,955,729,955.23","22,120,338,504,730.00","22,139,101,840,847.00","5,389,605,935,829.00","1,503.00",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07

### Step 4.3. Keep only the shares for the partners, and drop duplicates (effectively only keep one value for each iso_partner)

In [11]:
# Keep iso_partner and share_reported_total_profit_loss_by_partner	share_reported_total_n_employees_by_partner	share_reported_total_unrelated_party_revenues_by_partner	share_reported_total_tangible_assets_except_cash_by_partner	share_reported_total_payroll_by_partner	share_reported_total_stated_capital_by_partner	share_reported_total_total_revenues_by_partner	share_reported_total_related_party_revenues_by_partner	share_reported_total_holding_or_managing_ip_by_partner
shares_reported_2021 = final_misalignment_2021[['iso_partner', 'share_reported_total_profit_loss_by_partner', 'share_reported_total_n_employees_by_partner', 'share_reported_total_unrelated_party_revenues_by_partner', 'share_reported_total_tangible_assets_except_cash_by_partner', 'share_reported_total_payroll_by_partner', 'share_reported_total_stated_capital_by_partner', 'share_reported_total_total_revenues_by_partner', 'share_reported_total_related_party_revenues_by_partner', 'share_reported_total_holding_or_managing_ip_by_partner']]

# Drop duplicates
shares_reported_2021 = shares_reported_2021.drop_duplicates()

shares_reported_2021[shares_reported_2021['iso_partner'] == 'USA']

,iso_partner,share_reported_total_profit_loss_by_partner,share_reported_total_n_employees_by_partner,share_reported_total_unrelated_party_revenues_by_partner,share_reported_total_tangible_assets_except_cash_by_partner,share_reported_total_payroll_by_partner,share_reported_total_stated_capital_by_partner,share_reported_total_total_revenues_by_partner,share_reported_total_related_party_revenues_by_partner,share_reported_total_holding_or_managing_ip_by_partner
140,USA,0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07

### Step 4.4. Bring back the excluded countries

- The key here is the third command, where we sum by iso_parent. We basically assume that all countries report for the rest of the world, without caring about continents. **This could be improved and changed**. 
- Once that sum is done, we combine all potential iso_combinations for 2016 (created in Step 1), and we keep all combinations for the "excluded countries".
- Note in the test view, that no matter who is the iso_partner, the number in the variables will be the same because we have aggregated them. The next cells will now create the right shares.

In [12]:
excluded_2021 = pd.read_csv(f'{data_final}/cbcr_main_no_imputation_allsubgroupsonly.csv')

# Keep if year == 2021 and iso_parent == 'AUT', 'FIN', 'IRL0', 'KOR', 'NLD', 'NOR' 'SWE'
excluded_2021 = excluded_2021[excluded_2021['year'] == 2021]
excluded_2021 = excluded_2021[excluded_2021['iso_parent'].isin(['AUT', 'CZE', 'FIN', 'HUN', 'IRL', 'KOR', 'MAC', 'MUS', 'MAR' 'NZL', 'POL', 'SWE', 'GBR'])]

# Sum by iso_parent: 'n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",'stated_capital', 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip' and 'profit_loss_before_income_tax_corrected'
excluded_2021 = excluded_2021.groupby('iso_parent').agg({'n_employees': 'sum', 'unrelated_party_revenues': 'sum', 'tangible_assets_except_cash': 'sum', 'payroll': 'sum', 'stated_capital': 'sum', 'total_revenues': 'sum', 'related_party_revenues': 'sum', 'holding_or_managing_ip': 'sum', 'profit_loss_before_income_tax_corrected': 'sum'}).reset_index()

# Merge iso_combinations_2021 with excluded_2021. 
excluded_jurisdictions_2021 = pd.merge(iso_combinations_2021, excluded_2021, on='iso_parent', how='left')

# Drop year_y
excluded_jurisdictions_2021 = excluded_jurisdictions_2021.drop(columns=['year_y'])
# Rename year_x to year
excluded_jurisdictions_2021 = excluded_jurisdictions_2021.rename(columns={'year_x': 'year'})

# Keep if iso_parent == 'AUT', 'FIN', 'IRL0', 'KOR', 'NLD', 'NOR' 'SWE'
excluded_jurisdictions_2021 = excluded_jurisdictions_2021[excluded_jurisdictions_2021['iso_parent'].isin(['AUT', 'CZE', 'FIN', 'HUN', 'IRL', 'KOR', 'MAC', 'MUS', 'MAR' 'NZL', 'POL', 'SWE', 'GBR'])]

excluded_jurisdictions_2021[excluded_jurisdictions_2021['iso_partner'] == 'USA']

,iso_parent,year,iso_partner,n_employees,unrelated_party_revenues,tangible_assets_except_cash,payroll,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip,profit_loss_before_income_tax_corrected
830,AUT,2021,USA,"2,069,263.00","726,297,147,483.00","401,888,660,314.00","22,529,811,546.62","270,964,405,217.00","951,640,549,767.00","224,852,493,775.00",580.00,"63,174,139,580.00"
3362,CZE,2021,USA,"444,663.00","238,000,000,000.00","53,690,818,054.00","2,606,664,163.22","30,586,349,491.00","365,000,000,000.00","125,750,238,269.00",0.00,"5,814,794,701.00"
4206,FIN,2021,USA,"985,297.00","817,761,022,659.00","184,844,536,829.00","10,156,173,245.81","612,898,954,550.00","1,130,883,735,340.00","311,960,968,624.00",217.00,"42,314,748,301.00"
4628,GBR,2021,USA,"10,746,171.00","4,880,906,637,939.00","3,615,569,195,881.00","112,780,002,636.05","13,839,749,415,401.00","7,180,000,000,000.00","2,297,536,542,295.00","3,590.00","604,216,148,740.00"
5261,HUN,2021,USA,"134,329.00","58,109,599,064.00","19,550,252,423.00","959,278,134.14","15,860,548,301.00","74,640,793,509.00","16,531,194,445.00",0.00,"6,868,840,612.00"
5894,IRL,2021,USA,"1,915,063.00","427,571,530,900.00","217,000,000,000.00","7,126,386,684.12","2,369,000,000,000.00","697,000,000,000.00","269,410,895,368.00",376.00,"36,519,731,063.00"
6527,KOR,2021,USA,"6,345,530.00","3,019,577,465,309.00","2,541,934,539,062.00","77,256,150,290.88","1,089,902,961,198.00","4,316,949,217,844.00","1,298,930,513,223.00","1,516.00","276,597,253,936.00"
7793,MUS,2021,USA,"101,419.00","170,242,775,061.00","52,766,072,303.00","136,773,695.63","62,329,244,580.00","187,866,781,453.00","17,624,006,392.00",75.00,"7,439,064,276.00"
10325,SWE,2021,USA,"2,924,649.00","868,921,664,525.00","409,722,741,330.00","22,514,030,335.37","336,932,617,882.00","1,252,041,349,614.00","382,298,181,710.00","1,274.00","129,576,740,443.00"

### Step 4.5. Merge with the shares reported, and multiply the number

In [13]:
# Merge with share_reported_2021
excluded_jurisdictions_share_reported_2021 = pd.merge(excluded_jurisdictions_2021, shares_reported_2021, on='iso_partner', how='left')

# Multiply 'n_employees', "unrelated_party_revenues", "tangible_assets_except_cash", "payroll",'stated_capital', 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip' and 'profit_loss_before_income_tax_corrected' by share_reported
excluded_jurisdictions_share_reported_2021['n_employees'] = excluded_jurisdictions_share_reported_2021['n_employees'] * excluded_jurisdictions_share_reported_2021['share_reported_total_n_employees_by_partner']
excluded_jurisdictions_share_reported_2021['unrelated_party_revenues'] = excluded_jurisdictions_share_reported_2021['unrelated_party_revenues'] * excluded_jurisdictions_share_reported_2021['share_reported_total_unrelated_party_revenues_by_partner']
excluded_jurisdictions_share_reported_2021['tangible_assets_except_cash'] = excluded_jurisdictions_share_reported_2021['tangible_assets_except_cash'] * excluded_jurisdictions_share_reported_2021['share_reported_total_tangible_assets_except_cash_by_partner']
excluded_jurisdictions_share_reported_2021['payroll'] = excluded_jurisdictions_share_reported_2021['payroll'] * excluded_jurisdictions_share_reported_2021['share_reported_total_payroll_by_partner']
excluded_jurisdictions_share_reported_2021['stated_capital'] = excluded_jurisdictions_share_reported_2021['stated_capital'] * excluded_jurisdictions_share_reported_2021['share_reported_total_stated_capital_by_partner']
excluded_jurisdictions_share_reported_2021['total_revenues'] = excluded_jurisdictions_share_reported_2021['total_revenues'] * excluded_jurisdictions_share_reported_2021['share_reported_total_total_revenues_by_partner']
excluded_jurisdictions_share_reported_2021['related_party_revenues'] = excluded_jurisdictions_share_reported_2021['related_party_revenues'] * excluded_jurisdictions_share_reported_2021['share_reported_total_related_party_revenues_by_partner']
excluded_jurisdictions_share_reported_2021['holding_or_managing_ip'] = excluded_jurisdictions_share_reported_2021['holding_or_managing_ip'] * excluded_jurisdictions_share_reported_2021['share_reported_total_holding_or_managing_ip_by_partner']
excluded_jurisdictions_share_reported_2021['profit_loss_before_income_tax_corrected'] = excluded_jurisdictions_share_reported_2021['profit_loss_before_income_tax_corrected'] * excluded_jurisdictions_share_reported_2021['share_reported_total_profit_loss_by_partner']

# Drop share_reported columns
excluded_jurisdictions_dataset_2021 = excluded_jurisdictions_share_reported_2021.drop(columns=[
    'share_reported_total_profit_loss_by_partner',
    'share_reported_total_n_employees_by_partner',
    'share_reported_total_unrelated_party_revenues_by_partner',
    'share_reported_total_tangible_assets_except_cash_by_partner',
    'share_reported_total_payroll_by_partner',
    'share_reported_total_stated_capital_by_partner',
    'share_reported_total_total_revenues_by_partner',
    'share_reported_total_related_party_revenues_by_partner',
    'share_reported_total_holding_or_managing_ip_by_partner'
])

excluded_jurisdictions_share_reported_2021[excluded_jurisdictions_share_reported_2021['iso_partner'] == 'USA']

,iso_parent,year,iso_partner,n_employees,unrelated_party_revenues,tangible_assets_except_cash,payroll,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip,profit_loss_before_income_tax_corrected,share_reported_total_profit_loss_by_partner,share_reported_total_n_employees_by_partner,share_reported_total_unrelated_party_revenues_by_partner,share_reported_total_tangible_assets_except_cash_by_partner,share_reported_total_payroll_by_partner,share_reported_total_stated_capital_by_partner,share_reported_total_total_revenues_by_partner,share_reported_total_related_party_revenues_by_partner,share_reported_total_holding_or_managing_ip_by_partner
197,AUT,2021,USA,"395,200.37","198,384,558,241.92","88,382,568,513.57","8,279,413,048.09","55,739,216,511.75","243,376,521,454.14","47,859,082,489.78",38.80,"17,020,131,292.33",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
408,CZE,2021,USA,"84,924.43","65,008,550,598.34","11,807,579,744.85","957,915,215.59","6,291,819,603.45","93,346,621,634.09","26,765,507,134.86",0.00,"1,566,599,401.38",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
619,FIN,2021,USA,"188,177.98","223,367,474,028.89","40,650,649,182.00","3,732,261,724.25","126,077,473,165.25","289,216,920,972.42","66,399,822,747.38",14.52,"11,400,275,120.06",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
830,GBR,2021,USA,"2,052,368.76","1,333,196,076,210.98","795,128,909,387.10","41,445,185,791.12","2,846,930,350,558.64","1,836,243,132,418.60","489,022,776,909.91",240.15,"162,785,567,779.30",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1041,HUN,2021,USA,"25,654.97","15,872,356,348.74","4,299,453,293.56","352,522,251.87","3,262,622,391.44","19,088,947,699.05","3,518,608,067.52",0.00,"1,850,576,356.39",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1252,IRL,2021,USA,"365,750.32","116,789,098,743.36","47,722,215,781.01","2,618,854,524.20","487,319,372,485.76","178,253,685,695.79","57,343,185,519.50",25.15,"9,839,004,085.93",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1463,KOR,2021,USA,"1,211,907.71","824,783,001,845.11","559,017,274,536.02","28,390,631,561.21","224,200,433,567.49","1,104,034,589,730.63","276,472,906,913.95",101.41,"74,519,757,742.42",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1674,MUS,2021,USA,"19,369.61","46,500,991,834.26","11,604,211,467.10","50,262,556.25","12,821,548,483.00","48,045,833,879.20","3,751,209,344.20",5.02,"2,004,203,800.98",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07
1885,SWE,2021,USA,"558,567.16","237,341,756,278.42","90,105,424,295.56","8,273,613,657.98","69,309,325,418.42","320,202,274,336.05","81,370,857,431.80",85.22,"34,910,062,082.90",0.27,0.19,0.27,0.22,0.37,0.21,0.26,0.21,0.07

## Step 5. Calculate Misalignment with all countries reporting in the CBCR

### Step 5.1. Concatenate the two samples

- Concatenate the cbcr_sample (without the "bad reporters") and the sample with the bad reporters.
- Ensure all required columns are included: 'iso_parent', 'year', 'iso_partner', 'n_employees', 'unrelated_party_revenues', 'tangible_assets_except_cash', 'payroll', 'stated_capital', 'total_revenues', 'related_party_revenues', 'holding_or_managing_ip', 'profit_loss_before_income_tax_corrected'.

In [14]:
final_misalignment_2021 = cbcr_sample[cbcr_sample['year'] == 2021].copy()

# Concatenate excluded_jurisdictions_dataset_2021
final_misalignment_2021 = pd.concat([final_misalignment_2021, excluded_jurisdictions_dataset_2021])


final_misalignment_2021[final_misalignment_2021['iso_partner'] == 'USA']

,iso_parent,parent_jurisdiction,iso_partner,partner_jurisdiction,year,unrelated_party_revenues,profit_loss_before_income_tax,adjusted_profit_loss_before_income_tax,income_tax_paid_on_cash_basis,income_tax_accrued_current_year,n_employees,tangible_assets_except_cash,stated_capital,total_revenues,related_party_revenues,holding_or_managing_ip,n_cbcr,n_cbcr_groups,n_entities,profit_loss_before_income_tax_corrected,ln_profit_loss_before_income_tax_corrected,ln_unrelated_party_revenues,ln_n_employees,ln_tangible_assets_except_cash,ln_stated_capital,ln_total_revenues,ln_related_party_revenues,ln_holding_or_managing_ip,etr_domestic,etr_domestic_corrected,etr_foreign,etr_foreign_corrected,etr_average,etr_average_corrected,cit,gdp_current_usd,population,gdp,wage_monthly,payroll,ln_wage_monthly,ln_gdp_current_usd,ln_population,gvt_health_expenditure,ln_gvt_health_expenditure,tax_revenue_pct_gdp,tax_revenue_current_usd,cthi_2021_share,cthi_2021_score,region_tjn,ukt,gbr_oct,nld_oct,oecd_oct,oecd,eu
140,ARE,United Arab Emirates,USA,United States,2021,"22,510,101,353.00","-566,015,448.00",NaN,"33,594,827.00","41,196,000.00","28,384.00","11,019,650,222.00","33,844,332,143.00","25,838,686,878.00","3,328,585,524.00",19.00,28.00,28.00,438.00,"-566,015,448.00",0.00,23.84,10.25,23.12,24.25,23.98,21.93,3.00,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","1,566,840,057.22",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
248,ARG,Argentina,USA,United States,2021,"113,406,031.00","67,155,125.00",NaN,"940,629.00","1,346,224.00",114.00,"103,940,740.00","1,762,118,722.00","132,596,801.00","19,190,770.00",2.00,16.00,16.00,38.00,"67,155,125.00",18.02,18.55,4.74,18.46,21.29,18.70,16.77,1.10,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","6,292,973.74",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
720,AUS,Australia,USA,United States,2021,"57,209,834,217.00","8,095,396,499.00",NaN,"379,083,911.00","995,838,351.00","89,401.00","37,039,556,556.00","174,000,000,000.00","73,738,510,494.00","16,528,676,277.00",27.00,83.00,83.00,"1,198.00","8,095,396,499.00",22.81,24.77,11.40,24.34,25.88,25.02,23.53,3.33,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","4,935,071,447.12",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
830,AZE,Azerbaijan,USA,United States,2021,"748,376,581.00","-5,934,134.00",NaN,"8,850.00","4,774.00",21.00,"7,712,734.00","20,001,000.00","751,937,979.00","3,561,398.00",NaN,2.00,2.00,3.00,"-5,934,134.00",0.00,20.43,3.09,15.86,16.81,20.44,15.09,NaN,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","1,159,232.00",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
997,BEL,Belgium,USA,United States,2021,"43,812,500,000.00","2,376,700,000.00",NaN,"559,700,000.00","807,700,000.00","58,400.00","14,989,500,000.00","380,000,000,000.00","54,828,300,000.00","11,015,800,000.00",25.00,48.00,48.00,340.00,"2,376,700,000.00",21.59,24.50,10.98,23.43,26.66,24.73,23.12,3.26,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","3,223,769,001.60",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
1060,BHR,Bahrain,USA,United States,2021,"31,352,002.00","28,628,903.00",NaN,"1,933,590.00","-7,006,209.00",46.00,"494,407.00","1,253,597.00","491,165,142.00","459,813,140.00",NaN,2.00,2.00,2.00,"28,628,903.00",17.17,17.26,3.85,13.11,14.04,20.01,19.95,NaN,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","2,539,270.10",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
1605,BMU,Bermuda,USA,United States,2021,"87,810,248,119.00","8,368,805,189.00",NaN,"1,268,961,458.00","1,607,241,662.00","95,211.00","43,717,634,640.00","75,203,353,654.00","109,000,000,000.00","21,625,977,894.00",16.00,63.00,63.00,"1,233.00","8,368,805,189.00",22.85,25.20,11.46,24.50,25.04,25.41,23.80,2.83,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","5,255,792,301.56",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
1867,BRA,Brazil,USA,United States,2021,"68,461,937,528.00","10,586,870,772.00",NaN,"2,076,296,193.00","2,304,419,095.00","121,286.00","17,087,060,697.00","47,722,813,871.00","79,304,813,607.00","10,842,876,078.00",20.00,48.00,48.00,406.00,"10,586,870,772.00",23.08,24.95,11.71,23.56,24.59,25.10,23.11,3.04,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","6,695,172,039.86",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
1975,CAN,Canada,USA,United States,2021,"448,000,000,000.00","57,913,095,000.00",NaN,"7,532,740,000.00","7,264,577,000.00","867,200.00","440,000,000,000.00","1,150,000,000,000.00","561,000,000,000.00","112,000,000,000.00",NaN,210.00,210.00,"8,590.00","57,913,095,000.00",24.78,26.83,13.67,26.81,27.77,27.05,25.44,NaN,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","47,870,761,612.80",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
2685,CHE,Switzerland,USA,United States,2021,"267,000,000,000.00","13,563,295,251.00",NaN,"4,738,478,631.00","4,850,438,187.00","303,765.00","91,543,939,101.00","398,000,000,000.00","334,000,000,000.00","67,308,695,757.00",64.00,109.00,109.00,"3,063.00","13,563,295,251.00",23.33,26.31,12.62,25.24,26.71,26.53,24.93,4.17,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","16,768,290,937.86",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
2806,CHL,Chile,USA,United States,2021,"6,316,805,695.00","569,080,541.00",NaN,"189,369,332.00","88,979,044.00","7,614.00","1,863,664,102.00","3,773,832,021.00","6,487,770,036.00","170,964,341.00",0.00,18.00,18.00,68.00,"569,080,541.00",20.16,22.57,8.94,21.35,22.05,22.59,18.96,0.00,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","420,304,403.74",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
3524,CHN,China (People’s Republic of),USA,United States,2021,"114,000,000,000.00","-54,418,982.00",NaN,"670,071,457.00","971,258,544.00","84,266.00","63,306,614,237.00","75,432,933,414.00","175,000,000,000.00","61,042,227,499.00",97.00,306.00,306.00,"1,316.00","-54,418,982.00",0.00,25.46,11.34,24.87,25.05,25.89,24.83,4.58,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","4,651,611,621.38",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
4099,CYM,Cayman Islands,USA,United States,2021,"38,176,084,571.00","1,392,788,410.00",NaN,"560,883,918.00","576,412,782.00","62,243.00","9,343,614,768.00","19,813,279,525.00","47,309,937,896.00","9,133,853,328.00",39.00,102.00,102.00,885.00,"1,392,788,410.00",21.05,24.37,11.04,22.96,23.71,24.58,22.94,3.69,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","3,435,908,458.33",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
4917,DEU,Germany,USA,United States,2021,"553,000,000,000.00","24,047,033,000.00",NaN,"9,444,737,000.00","8,076,549,000.00","719,133.00","293,000,000,000.00","595,000,000,000.00","704,000,000,000.00","152,000,000,000.00",273.00,293.00,293.00,"5,067.00","24,047,033,000.00",23.90,27.04,13.49,26.40,27.11,27.28,25.75,5.61,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","39,697,237,558.69",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
5581,DNK,Denmark,USA,United States,2021,"45,485,959,763.00","3,243,137,161.00",NaN,"645,634,191.00","645,032,234.00","73,241.00","25,104,263,012.00","51,448,797,455.00","60,390,018,377.00","14,904,058,614.00",27.00,60.00,60.00,710.00,"3,243,137,161.00",21.90,24.54,11.20,23.95,24.66,24.82,23.42,3.33,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","4,043,014,819.28",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
6170,ESP,Spain,USA,United States,2021,"79,067,644,471.00","10,527,379,930.00",NaN,"1,094,972,272.00","1,153,327,400.00","109,801.00","88,909,492,659.00","74,509,895,692.00","91,002,422,172.00","11,934,777,701.00",43.00,88.00,88.00,"1,194.00","10,527,379,930.00",23.08,25.09,11.61,25.21,25.03,25.23,23.20,3.78,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","6,061,182,536.72",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
6754,FRA,France,USA,United States,2021,"294,000,000,000.00","18,794,938,537.00",NaN,"5,946,191,225.00","5,488,193,921.00","524,681.00","90,590,541,274.00","264,000,000,000.00","376,000,000,000.00","82,591,027,820.00",327.00,163.00,163.00,"3,723.00","18,794,938,537.00",23.66,26.41,13.17,25.23,26.30,26.65,25.14,5.79,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","28,963,190,813.84",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
7025,GRC,Greece,USA,United States,2021,"3,393,241.00","-120,699,170.00",NaN,0.00,0.00,21.00,"5,308,687.00","164,536,615.00","3,393,241.00",0.00,0.00,5.00,5.00,6.00,"-120,699,170.00",0.00,15.04,3.09,15.48,18.92,15.04,0.00,0.00,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","1,159,232.00",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
7550,HKG,Hong Kong (China),USA,United States,2021,"38,239,355,286.00","162,587,382.00",NaN,"207,139,225.00","278,691,317.00","67,742.00","20,183,558,893.00","35,933,512,017.00","73,359,535,957.00","35,120,180,670.00",50.00,92.00,92.00,774.00,"162,587,382.00",18.91,24.37,11.12,23.73,24.30,25.02,24.28,3.93,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","3,739,461,638.81",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
7901,IDN,Indonesia,USA,United States,2021,"2,582,787,240.00","268,989,845.00",NaN,"41,150,124.00","37,662,748.00","4,573.00","807,463,833.00","4,017,837,203.00","3,296,862,710.00","714,075,470.00",11.00,18.00,18.00,136.00,"268,989,845.00",19.41,21.67,8.43,20.51,22.11,21.92,20.39,2.48,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","252,436,569.25",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
8464,IND,India,USA,United States,2021,"43,251,114,389.00","-331,745,994.00",NaN,"1,335,353,631.00","1,524,662,856.00","584,497.00","25,160,717,354.00","36,245,763,120.00","98,162,899,613.00","54,911,785,225.00",4.00,74.00,74.00,415.00,"-331,745,994.00",0.00,24.49,13.28,23.95,24.31,25.31,24.73,1.61,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","32,265,125,173.43",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
9128,ITA,Italy,USA,United States,2021,"38,410,342,400.00","3,521,381,888.00",NaN,"618,845,696.00","665,684,992.00","66,451.00","25,715,773,440.00","56,180,838,400.00","44,698,591,232.00","6,289,369,600.00",40.00,92.00,92.00,"1,206.00","3,521,381,888.00",21.98,24.37,11.10,23.97,24.75,24.52,22.56,3.71,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","3,668,196,471.32",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
9905,JPN,Japan,USA,United States,2021,"755,000,000,000.00","43,932,684,793.00",NaN,"9,511,570,564.00","8,585,655,731.00","939,003.00","321,000,000,000.00","412,000,000,000.00","996,000,000,000.00","241,000,000,000.00",332.00,692.00,692.00,"8,467.00","43,932,684,793.00",24.51,27.35,13.75,26.49,26.74,27.63,26.21,5.81,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","51,834,396,640.57",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
10554,LUX,Luxembourg,USA,United States,2021,"169,000,000,000.00","4,473,429,202.00",NaN,"307,095,030.00","747,736,030.00","1,121,870.00","33,506,463,047.00","63,189,786,791.00","210,000,000,000.00","41,633,694,079.00",53.00,89.00,89.00,"1,149.00","4,473,429,202.00",22.22,25.85,13.93,24.24,24.87,26.07,24.45,3.99,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","61,928,933,729.88",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
11180,MEX,Mexico,USA,United States,2021,"41,306,870,980.00","5,016,010,454.00",NaN,"440,257,442.00","552,294,136.00","83,674.00","19,464,236,857.00","22,696,891,231.00","46,821,542,963.00","5,514,671,983.00",12.00,58.00,58.00,554.00,"5,016,010,454.00",22.34,24.44,11.33,23.69,23.85,24.57,22.43,2.56,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","4,618,932,319.18",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
11377,MYS,Malaysia,USA,United States,2021,"1,717,498,924.00","-474,789,258.00",NaN,"6,423,690.00","8,895,925.00","6,708.00","6,786,997,652.00","5,757,646,533.00","1,858,412,897.00","140,913,973.00",4.00,22.00,22.00,136.00,"-474,789,258.00",0.00,21.26,8.81,22.64,22.47,21.34,18.76,1.61,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","370,291,822.99",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
11682,NOR,Norway,USA,United States,2021,"22,473,752,000.00","2,920,130,000.00",NaN,"149,998,000.00","142,198,000.00","16,570.00","13,334,348,000.00","97,712,537,000.00","32,237,860,000.00","9,764,108,000.00",3.00,29.00,29.00,198.00,"2,920,130,000.00",21.79,23.84,9.72,23.31,25.31,24.20,23.00,1.39,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","914,689,252.68",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
12048,PER,Peru,USA,United States,2021,"3,663,071.00","1,268,941.00",NaN,"85,109.00","55,171.00",42.00,"28,918,750.00","1,191,917.00","35,339,373.00","31,676,302.00",0.00,3.00,3.00,6.00,"1,268,941.00",14.05,15.11,3.76,17.18,13.99,17.38,17.27,0.00,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","2,318,464.01",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
12221,PRT,Portugal,USA,United States,2021,"2,393,887,094.00","590,203,601.00",NaN,"5,749,260.00","21,841,377.00","1,714.00","9,326,699,236.00","19,586,573,404.00","2,630,610,509.00","236,723,416.00",1.00,8.00,8.00,349.00,"590,203,601.00",20.20,21.60,7.45,22.96,23.70,21.69,19.28,0.69,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","94,615,412.14",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
12788,ROU,Romania,USA,United States,2021,"30,338,521.00","28,381,338.00",NaN,"-4,009,579.00","219,259.00",294.00,"26,767,822.00","13,096,423.00","223,956,163.00","193,617,643.00",0.00,1.00,1.00,3.00,"28,381,338.00",17.16,17.23,5.69,17.10,16.39,19.23,19.08,0.00,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","16,229,248.06",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
13165,SAU,Saudi Arabia,USA,United States,2021,"132,000,000,000.00","22,846,301,764.00",NaN,"4,196,692,696.00","3,755,295,949.00","58,288.00","46,670,751,675.00","186,000,000,000.00","159,000,000,000.00","26,167,020,621.00",3.00,17.00,17.00,895.00,"22,846,301,764.00",23.85,25.61,10.97,24.57,25.95,25.79,23.99,1.39,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","3,217,586,430.91",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
13357,SGP,Singapore,USA,United States,2021,"40,401,573,647.00","-562,409,531.00",NaN,"234,297,107.00","201,593,665.00","18,849.00","16,384,908,659.00","18,428,670,984.00","62,215,984,112.00","21,814,410,466.00",8.00,37.00,37.00,488.00,"-562,409,531.00",0.00,24.42,9.84,23.52,23.64,24.85,23.81,2.20,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","1,040,493,525.88",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
13587,TUR,Türkiye,USA,United States,2021,"2,760,109,917.00","93,134,196.00",NaN,"139,003,818.00","37,917,007.00","3,299.00","1,862,989,215.00","5,668,969,140.00","3,539,054,769.00","778,944,852.00",1.00,26.00,26.00,82.00,"93,134,196.00",18.35,21.74,8.10,21.35,22.46,21.99,20.47,0.69,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","182,109,827.68",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
14413,USA,United States,USA,United States,2021,"13,300,000,000,000.00","1,850,000,000,000.00",NaN,"302,000,000,000.00","295,000,000,000.00","23,963,059.00","7,670,000,000,000.00","17,800,000,000,000.00","17,700,000,000,000.00","4,370,000,000,000.00",NaN,"1,721.00",NaN,"97,727.00","1,850,000,000,000.00",28.25,30.22,16.99,29.67,30.51,30.50,29.11,NaN,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","1,322,797,376,501.92",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00
14849,ZAF,South Africa,USA,United States,2021,"5,356,980,538.00","-80,276,898.00",NaN,"-214,613,502.00","-626,152,342.00","7,486.00","8,847,092,554.00","12,208,042,858.00","5,741,637,926.00","384,657,388.00",2.00,28.00,28.00,73.00,"-80,276,898.00",0.00,22.40,8.92,22.90,23.23,22.47,19.77,1.10,0.14,0.18,0.16,0.16,0.14,0.18,0.27,"23,594,031,000,000.00","332,048,977.00",NaN,"4,600.13","413,238,608.66",8.43,30.79,19.62,"2,242,777,276,178.77",28.44,11.30,"2,666,221,799,678.12",0.01,46.90,Northern America,0.00,0.00,0.00,0.00,1.00,0.00

### Step 5.2. Perform the misalignment estimates, and all the remaining calculations needed

In [15]:
# Initialize a list to store the aggregate results
results_sample = []

# Start the estimates
misalignment_final_estimates_2021 = final_misalignment_2021[final_misalignment_2021['year'] == 2021].copy()
misalignment_final_estimates_2021 = calculate_misalignment(misalignment_final_estimates_2021, etr_max=0.15, weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0])


# Perform the groupby operation on 'iso_partner'
country_results_2021 = misalignment_final_estimates_2021.groupby(['iso_partner']).agg(
    negative_misalignment=('misaligned_profit', lambda x: x[x < 0].sum()),
    positive_misalignment=('misaligned_profit', lambda x: x[x > 0].sum()),
    theoretical_profit=('theoretical_profit', 'sum'),
    reported_profit=('profit_loss_before_income_tax_corrected', 'sum')
).reset_index()

# Convert results to millions
country_results_2021['negative_misalignment'] = -country_results_2021['negative_misalignment'] / 1e6
country_results_2021['positive_misalignment'] = country_results_2021['positive_misalignment'] / 1e6
country_results_2021['theoretical_profit'] = country_results_2021['theoretical_profit'] / 1e6
country_results_2021['reported_profit'] = country_results_2021['reported_profit'] / 1e6

# Merge the unique columns back into the result
country_results_2021 = country_results_2021.merge(unique_columns, on='iso_partner', how='left')

# Calculate other relevant variables
country_results_2021['tax_revenue_loss'] = country_results_2021['negative_misalignment'] * country_results_2021['cit']
country_results_2021['tax_revenue_gain'] = country_results_2021['positive_misalignment'] * country_results_2021['etr_average_corrected']

country_results_2021['tax_revenue_loss_pct_of_gvt_health_expenditure'] = np.where(
    country_results_2021['gvt_health_expenditure'] == 0, 
    np.nan, 
    country_results_2021['tax_revenue_loss'] / (country_results_2021['gvt_health_expenditure'] / 1e6)
)
    
country_results_2021['tax_revenue_loss_pct_of_total_tax_revenues'] = np.where(
    country_results_2021['tax_revenue_current_usd'] == 0, 
    np.nan, 
    country_results_2021['tax_revenue_loss'] / (country_results_2021['tax_revenue_current_usd'] / 1e6)
)

# Calculate totals
total_positive_misalignment = country_results_2021['positive_misalignment'].sum()
total_negative_misalignment = country_results_2021['negative_misalignment'].sum()
total_profits = country_results_2021['reported_profit'].sum()
misaligned_of_total_profits = total_positive_misalignment / total_profits
total_tax_revenue_loss = country_results_2021['tax_revenue_loss'].sum()
total_tax_revenue_gain = country_results_2021['tax_revenue_gain'].sum()
average_tax_revenue_loss_pct_of_gvt_health_expenditure = country_results_2021['tax_revenue_loss_pct_of_gvt_health_expenditure'].mean()
average_tax_revenue_loss_pct_of_total_tax_revenues = country_results_2021['tax_revenue_loss_pct_of_total_tax_revenues'].mean()

print(f"Year {2021}: Positive Misalignment: {total_positive_misalignment}, Negative Misalignment: {total_negative_misalignment}, Shifted of total profits: {misaligned_of_total_profits}, "
        f"Total tax revenue loss: {total_tax_revenue_loss}, Total tax revenue gain: {total_tax_revenue_gain}")

# Calculate countries' fractions of totals
country_results_2021['tax_revenue_loss_caused_pct_of_total'] = country_results_2021['positive_misalignment'] / total_positive_misalignment
country_results_2021['tax_revenue_loss_caused_usd'] = country_results_2021['tax_revenue_loss_caused_pct_of_total'] * total_tax_revenue_loss
country_results_2021['tax_revenue_loss_suffered_pct_of_total'] = country_results_2021['tax_revenue_loss'] / total_tax_revenue_loss

country_results_2021 = country_results_2021.sort_values(by='iso_partner')
country_results_2021.to_csv(f'{output_tables}/Final_Full_CBCR_Datasets/SOTJ_sample_countries_2021.csv', index=False) # CHANGE FILE NAME HERE, DEPENDING ON FORMULA USE
    
# Append aggregate results to the list
results_sample.append({
    'year': 2021,
    'total_positive_misalignment': total_positive_misalignment,
    'total_negative_misalignment': total_negative_misalignment,
    'total_profits': total_profits,
    'misaligned_of_total_profits': misaligned_of_total_profits,
    'total_tax_revenue_loss': total_tax_revenue_loss,
    'total_tax_revenue_gain': total_tax_revenue_gain,
    'average_tax_revenue_loss_pct_of_gvt_health_expenditure': average_tax_revenue_loss_pct_of_gvt_health_expenditure,
    'average_tax_revenue_loss_pct_of_total_tax_revenues': average_tax_revenue_loss_pct_of_total_tax_revenues
})

# Convert aggregate results to a DataFrame
results_sample_df = pd.DataFrame(results_sample)

# Save the aggregated results to a CSV or Excel file
results_sample_df.to_csv(f'{output_tables}/Final_Full_CBCR_Datasets/SOTJ_sample_aggregate_results_2021.csv', index=False)  # CHANGE FILE NAME HERE, DEPENDING ON FORMULA USE

Year 2021: Positive Misalignment: 1420180.0438085557, Negative Misalignment: 1420180.0438085552, Shifted of total profits: 0.15895261084432838, Total tax revenue loss: 347578.9136467748, Total tax revenue gain: 118593.46762131003

/var/folders/pm/bp4z4lln39xcwn73chrtp3n00000gn/T/ipykernel_12769/421381151.py:51: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

## Step 6. Checking the datasets

### Step 6.1. Checking the countries

In [16]:
# Open the CSV file f'{output_tables}/Scaling_Mario/SOTJ_sample_2016.csv'
sotj_2021_countries = pd.read_csv(f'{output_tables}/Final_Full_CBCR_Datasets/SOTJ_sample_countries_2021.csv')

sotj_2021_countries[sotj_2021_countries['iso_partner'] == 'FRA']

,iso_partner,negative_misalignment,positive_misalignment,theoretical_profit,reported_profit,partner_jurisdiction,etr_average_corrected,cit,tax_revenue_current_usd,gvt_health_expenditure,region_tjn,ukt,oecd,oecd_oct,nld_oct,tax_revenue_loss,tax_revenue_gain,tax_revenue_loss_pct_of_gvt_health_expenditure,tax_revenue_loss_pct_of_total_tax_revenues,tax_revenue_loss_caused_pct_of_total,tax_revenue_loss_caused_usd,tax_revenue_loss_suffered_pct_of_total
63,FRA,"70,272.44",0.00,"264,502.72","180,570.81",France,0.19,0.28,"709,159,262,410.30","275,291,141,343.09",Europe,0.00,1.00,0.00,0.00,"19,962.64",0.00,0.07,0.03,0.00,0.00,0.06

### Step 6.2. Checking the aggregate results

In [17]:
sotj_2021_aggregate = pd.read_csv(f'{output_tables}/Final_Full_CBCR_Datasets/SOTJ_sample_aggregate_results_2021.csv')
sotj_2021_aggregate

,year,total_positive_misalignment,total_negative_misalignment,total_profits,misaligned_of_total_profits,total_tax_revenue_loss,total_tax_revenue_gain,average_tax_revenue_loss_pct_of_gvt_health_expenditure,average_tax_revenue_loss_pct_of_total_tax_revenues
0,2021,"1,420,180.04","1,420,180.04","8,934,612.88",0.16,"347,578.91","118,593.47",0.41,0.06

In [19]:


# Initialize a list to store the aggregate results
results_sample_1 = []

# Start the estimates
misalignment_final_estimates_spain_2021 = final_misalignment_2021[final_misalignment_2021['year'] == 2021].copy()
misalignment_final_estimates_spain_2021 = calculate_misalignment(misalignment_final_estimates_spain_2021, etr_max=0.15, weights=[1/2, 0, 0, 1/2, 0, 0, 0, 0])

# Generate a new column called negative_misalignment equal to misaligned_profit if misaligned_profit < 0 and a new column called positive_misalignment equal to misaligned_profit if misaligned_profit > 0
misalignment_final_estimates_spain_2021['negative_misalignment'] = misalignment_final_estimates_spain_2021['misaligned_profit'].apply(lambda x: x if x < 0 else 0)
misalignment_final_estimates_spain_2021['positive_misalignment'] = misalignment_final_estimates_spain_2021['misaligned_profit'].apply(lambda x: x if x > 0 else 0)

# Rename profit_loss_before_income_tax_corrected to reported_profit
misalignment_final_estimates_spain_2021 = misalignment_final_estimates_spain_2021.rename(columns={'profit_loss_before_income_tax_corrected': 'reported_profit'})

# Convert results to millions
misalignment_final_estimates_spain_2021['negative_misalignment'] = -misalignment_final_estimates_spain_2021['negative_misalignment'] / 1e6
misalignment_final_estimates_spain_2021['positive_misalignment'] = misalignment_final_estimates_spain_2021['positive_misalignment'] / 1e6
misalignment_final_estimates_spain_2021['theoretical_profit'] = misalignment_final_estimates_spain_2021['theoretical_profit'] / 1e6
misalignment_final_estimates_spain_2021['reported_profit'] = misalignment_final_estimates_spain_2021['reported_profit'] / 1e6

# Calculate other relevant variables
misalignment_final_estimates_spain_2021['tax_revenue_loss'] = misalignment_final_estimates_spain_2021['negative_misalignment'] * misalignment_final_estimates_spain_2021['cit']
misalignment_final_estimates_spain_2021['tax_revenue_gain'] = misalignment_final_estimates_spain_2021['positive_misalignment'] * misalignment_final_estimates_spain_2021['etr_average_corrected']

#misalignment_final_estimates_spain_2021['tax_revenue_loss_pct_of_gvt_health_expenditure'] = np.where(
#    misalignment_final_estimates_spain_2021['gvt_health_expenditure'] == 0, 
#    np.nan, 
#    misalignment_final_estimates_spain_2021['tax_revenue_loss'] / (misalignment_final_estimates_spain_2021['gvt_health_expenditure'] / 1e6)
#)
    
#misalignment_final_estimates_spain_2021['tax_revenue_loss_pct_of_total_tax_revenues'] = np.where(
#    misalignment_final_estimates_spain_2021['tax_revenue_current_usd'] == 0, 
#    np.nan, 
 #   misalignment_final_estimates_spain_2021['tax_revenue_loss'] / (misalignment_final_estimates_spain_2021['tax_revenue_current_usd'] / 1e6)
#)

# Keep iso_partner, iso_parent, year, negative_misalignment, positive_misalignment, tax_revenue_loss, tax_revenue gain
misalignment_final_estimates_spain_2021 = misalignment_final_estimates_spain_2021[['iso_parent', 'iso_partner', 'year', 'cit', 'theoretical_profit', 'reported_profit', 'negative_misalignment', 'positive_misalignment', 'tax_revenue_loss', 'tax_revenue_gain']]

# Calculate totals
#total_positive_misalignment = misalignment_final_estimates_spain_2021['positive_misalignment'].sum()
#total_negative_misalignment = misalignment_final_estimates_spain_2021['negative_misalignment'].sum()
#total_profits = misalignment_final_estimates_spain_2021['reported_profit'].sum()
#misaligned_of_total_profits = total_positive_misalignment / total_profits
#total_tax_revenue_loss = misalignment_final_estimates_spain_2021['tax_revenue_loss'].sum()
#total_tax_revenue_gain = misalignment_final_estimates_spain_2021['tax_revenue_gain'].sum()
#average_tax_revenue_loss_pct_of_gvt_health_expenditure = misalignment_final_estimates_spain_2021['tax_revenue_loss_pct_of_gvt_health_expenditure'].mean()
#average_tax_revenue_loss_pct_of_total_tax_revenues = misalignment_final_estimates_spain_2021['tax_revenue_loss_pct_of_total_tax_revenues'].mean()

#print(f"Year {2021}: Positive Misalignment: {total_positive_misalignment}, Negative Misalignment: {total_negative_misalignment}, Shifted of total profits: {misaligned_of_total_profits}, "
#        f"Total tax revenue loss: {total_tax_revenue_loss}, Total tax revenue gain: {total_tax_revenue_gain}")

#misalignment_final_estimates_spain_2021 = misalignment_final_estimates_spain_2021.sort_values(by='iso_partner')
#misalignment_final_estimates_spain_2021.to_csv(f'{output_tables}/Final_Full_CBCR_Datasets/SOTJ_spain_2021.csv', index=False) # CHANGE FILE NAME HERE, DEPENDING ON FORMULA USE

# Sort by iso_partner and then iso_parent
misalignment_final_estimates_spain_2021 = misalignment_final_estimates_spain_2021.sort_values(by=['iso_parent', 'iso_partner'])   

# Display 8 decimals
pd.options.display.float_format = '{:,.8f}'.format
pd.set_option('display.max_rows', None)
misalignment_final_estimates_spain_2021[(misalignment_final_estimates_spain_2021['iso_parent'] == 'ESP') | (misalignment_final_estimates_spain_2021['iso_partner'] == 'ESP')]

/var/folders/pm/bp4z4lln39xcwn73chrtp3n00000gn/T/ipykernel_12769/421381151.py:51: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cbcr_data = cbcr_data.groupby('iso_parent', group_keys=False).apply(lambda x: adjust_misalignment(x)).reset_index(drop=True)

,iso_parent,iso_partner,year,cit,theoretical_profit,reported_profit,negative_misalignment,positive_misalignment,tax_revenue_loss,tax_revenue_gain
84,ARE,ESP,2021,0.25000000,89.20950884,466.99609000,-0.00000000,377.78658116,-0.00000000,45.75008356
316,ARG,ESP,2021,0.25000000,4.14703067,25.46038400,-0.00000000,21.31335333,-0.00000000,2.58105434
380,AUS,ESP,2021,0.25000000,122.91634007,52.68373000,21.53690691,0.00000000,5.38422673,0.00000000
115,AUT,ESP,2021,NaN,"1,163.40571134",628.39862830,535.00708304,0.00000000,NaN,NaN
592,BEL,ESP,2021,0.25000000,574.77579017,145.80000000,363.98492475,0.00000000,90.99623119,0.00000000
762,BMU,ESP,2021,0.25000000,342.89179705,157.16593700,162.41320318,0.00000000,40.60330080,0.00000000
926,BRA,ESP,2021,0.25000000,180.78685266,932.64429800,-0.00000000,751.85744534,-0.00000000,91.05019253
972,CAN,ESP,2021,0.25000000,"1,237.04389737",0.00000000,"1,237.04389737",0.00000000,309.26097434,0.00000000
1018,CHE,ESP,2021,0.25000000,"2,452.99612749","2,623.69085300",-0.00000000,170.69472551,-0.00000000,20.67118936
1164,CHN,ESP,2021,0.25000000,"1,530.11408413",197.95274900,"1,185.34545732",0.00000000,296.33636433,0.00000000
1295,CYM,ESP,2021,0.25000000,221.87011553,96.97488300,123.28900085,0.00000000,30.82225021,0.00000000
3457,CZE,ESP,2021,NaN,107.08440844,57.84026563,49.24414281,0.00000000,NaN,NaN
1438,DEU,ESP,2021,0.25000000,"5,468.80361987","3,005.32500000",997.18155830,0.00000000,249.29538957,0.00000000
1582,DNK,ESP,2021,0.25000000,"2,509.13136896",183.84142000,"2,309.98980291",0.00000000,577.49745073,0.00000000
1658,ESP,AGO,2021,0.25000000,37.85127999,24.22478200,4.83798245,0.00000000,1.20949561,0.00000000
1659,ESP,AND,2021,0.00000000,7.67621666,-0.15675200,2.78103478,0.00000000,0.00000000,-0.00000000
1660,ESP,ARE,2021,0.00000000,107.38154579,412.06079900,-0.00000000,0.00000000,-0.00000000,0.00000000
1661,ESP,ARG,2021,0.30000000,"1,972.00590644","1,715.35493800",91.12193616,0.00000000,27.33658085,0.00000000
1662,ESP,AUS,2021,0.30000000,"1,291.93027252",506.18125100,278.97409705,0.00000000,83.69222912,0.00000000
1663,ESP,AUT,2021,0.25000000,184.45753650,89.35284200,33.76618430,0.00000000,8.44154608,0.00000000
1664,ESP,AZE,2021,0.20000000,4.98307756,-1.61002500,2.34082994,0.00000000,0.46816599,0.00000000
1665,ESP,BEL,2021,0.25000000,370.92042134,258.08061300,40.06289894,0.00000000,10.01572474,0.00000000
1666,ESP,BGR,2021,0.10000000,159.96825226,17.18060600,50.69564657,0.00000000,5.06956466,0.00000000
1667,ESP,BHR,2021,0.00000000,4.97213562,-6.74824100,4.16122884,0.00000000,0.00000000,0.00000000
1668,ESP,BHS,2021,0.00000000,15.47654123,-36.85036300,18.57826158,0.00000000,0.00000000,-0.00000000
1669,ESP,BIH,2021,0.10000000,9.90611855,8.73545100,0.41563644,0.00000000,0.04156364,0.00000000
1670,ESP,BOL,2021,0.25000000,40.18550217,32.46450400,2.74128053,0.00000000,0.68532013,-0.00000000
1671,ESP,BRA,2021,0.34000000,"4,767.62253233","7,332.51594800",-0.00000000,"2,564.89341567",-0.00000000,355.90525279
1672,ESP,BRB,2021,0.05500000,0.18701102,74.73772400,-0.00000000,74.55071298,-0.00000000,1.34073632
1673,ESP,CAN,2021,0.26170000,456.21429564,294.85122700,57.29070624,0.00000000,14.99297782,0.00000000
1674,ESP,CHE,2021,0.19698516,270.51539276,"1,163.93048500",-0.00000000,893.41509224,-0.00000000,61.70650925
1675,ESP,CHL,2021,0.27000000,"1,757.63490767","3,645.55130300",-0.00000000,0.00000000,-0.00000000,0.00000000
1676,ESP,CHN,2021,0.25000000,580.80230225,516.00874300,23.00445077,0.00000000,5.75111269,0.00000000
1677,ESP,CIV,2021,0.25000000,10.02032071,48.72036600,-0.00000000,0.00000000,-0.00000000,0.00000000
1678,ESP,CMR,2021,0.33000000,10.06298567,1.81473200,2.92847850,0.00000000,0.96639791,0.00000000
1679,ESP,COL,2021,0.31000000,"1,884.71866764",954.01085000,330.44059354,0.00000000,102.43658400,0.00000000
1680,ESP,CPV,2021,0.22440000,15.49058318,-18.07688800,11.91787035,0.00000000,2.67437011,0.00000000
1681,ESP,CRI,2021,0.30000000,157.85322816,128.29083300,10.49589916,0.00000000,3.14876975,0.00000000
1682,ESP,CUB,2021,0.35000000,0.60298320,-0.83933800,0.51208496,0.00000000,0.17922973,0.00000000
1683,ESP,CYM,2021,0.00000000,0.68649784,480.49281200,-0.00000000,479.80631416,-0.00000000,2.95434828
1684,ESP,CYP,2021,0.12500000,4.79436103,29.11648500,-0.00000000,24.32212397,-0.00000000,0.50767484
1685,ESP,CZE,2021,0.19000000,388.75570243,100.75899300,102.25099843,0.00000000,19.42768970,0.00000000
1686,ESP,DEU,2021,0.29941208,"2,975.17738686","1,543.70423400",508.23344266,0.00000000,152.17123219,0.00000000
1687,ESP,DNK,2021,0.22000000,92.60726923,151.99480600,-0.00000000,59.38753677,-0.00000000,5.80539140
1688,ESP,DOM,2021,0.27000000,312.44345540,46.69357300,94.35243500,0.00000000,25.47515745,0.00000000
1689,ESP,DZA,2021,0.26000000,43.51754585,623.59647900,-0.00000000,0.00000000,-0.00000000,0.00000000
1690,ESP,ECU,2021,0.25000000,336.72071330,205.55253800,46.57024350,0.00000000,11.64256088,0.00000000
1691,ESP,EGY,2021,0.22500000,35.07290015,9.26130700,9.16420599,0.00000000,2.06194635,0.00000000
1692,ESP,ESP,2021,0.25000000,"53,652.86622966","44,382.57430300","3,291.34526270",0.00000000,822.83631567,0.00000000
1693,ESP,FIN,2021,0.20000000,62.28009918,71.82071900,-0.00000000,9.54061982,-0.00000000,1.13043617
1694,ESP,FRA,2021,0.28407500,"2,045.33957684",447.69056600,567.23289244,0.00000000,161.13668392,0.00000000
1695,ESP,GAB,2021,0.30000000,0.15788277,-2.49153800,0.94065630,0.00000000,0.28219689,0.00000000
1696,ESP,GBR,2021,0.19000000,"5,561.36945221","7,574.68370600",-0.00000000,"2,013.31425379",-0.00000000,202.63716966
1697,ESP,GHA,2021,0.25000000,19.13184732,-5.43739000,8.72311719,0.00000000,2.18077930,0.00000000
1698,ESP,GIB,2021,0.00000000,2.56204127,1.02728800,0.54490225,0.00000000,0.00000000,0.00000000
1699,ESP,GIN,2021,0.35000000,3.02631631,-2.63478300,2.00992941,0.00000000,0.70347529,0.00000000
1700,ESP,GRC,2021,0.22000000,206.75539356,83.39014500,43.79987487,0.00000000,9.63597247,0.00000000
1701,ESP,GTM,2021,0.25000000,453.49510694,87.05459800,130.10186116,0.00000000,32.52546529,0.00000000
1702,ESP,HKG,2021,0.16500000,100.48530771,179.55877400,-0.00000000,79.07346629,-0.00000000,5.19822934
1703,ESP,HND,2021,0.30000000,119.98400255,46.04125900,26.25279771,0.00000000,7.87583931,0.00000000
1704,ESP,HRV,2021,0.18000000,54.69349984,11.27825300,15.41424673,0.00000000,2.77456441,0.00000000
1705,ESP,HUN,2021,0.09000000,65.21490844,37.61756200,9.79822385,0.00000000,0.88184015,0.00000000
1706,ESP,IDN,2021,0.22000000,140.52220661,275.32100000,-0.00000000,0.00000000,-0.00000000,0.00000000
1707,ESP,IND,2021,0.25170000,699.57459459,178.88567400,184.86656361,0.00000000,46.53091406,0.00000000
1708,ESP,IRL,2021,0.12500000,419.39085437,181.40156300,84.49625243,0.00000000,10.56203155,0.00000000
1709,ESP,ISR,2021,0.23000000,5.52302627,1.97068900,1.26122980,0.00000000,0.29008285,0.00000000
1710,ESP,ITA,2021,0.27810000,"1,022.57368398","1,010.29334200",4.36004019,0.00000000,1.21252718,0.00000000
1711,ESP,JAM,2021,0.25000000,54.60906485,-0.56437200,19.58890092,0.00000000,4.89722523,0.00000000
1712,ESP,JOR,2021,0.20000000,1.56205624,-4.43818800,2.13034019,0.00000000,0.42606804,0.00000000
1713,ESP,JPN,2021,0.29740000,158.83751331,49.86631800,38.68937789,0.00000000,11.50622098,0.00000000
1714,ESP,KAZ,2021,0.20000000,31.80182980,38.39798600,-0.00000000,6.59615620,-0.00000000,0.28492337
1715,ESP,KEN,2021,0.30000000,2.05558848,-0.52615700,0.91662871,0.00000000,0.27498861,0.00000000
1716,ESP,KOR,2021,0.27500000,84.78808520,51.05110000,11.97805499,0.00000000,3.29396512,0.00000000
1717,ESP,KWT,2021,0.15000000,5.46104295,-78.27458300,29.72968467,0.00000000,4.45945270,0.00000000
1718,ESP,LTU,2021,0.15000000,11.17192635,25.43288900,-0.00000000,14.26096265,-0.00000000,1.31344426
1719,ESP,LUX,2021,0.24940000,58.04690497,471.20151500,-0.00000000,413.15461003,-0.00000000,15.38203009
1720,ESP,LVA,2021,0.20000000,6.17279647,2.43509600,1.32704157,0.00000000,0.26540831,0.00000000
1721,ESP,MAR,2021,0.31000000,109.05661866,218.15052300,-0.00000000,0.00000000,-0.00000000,0.00000000
1722,ESP,MEX,2021,0.30000000,"3,338.31523879","6,901.25269300",-0.00000000,0.00000000,-0.00000000,0.00000000
1723,ESP,MLT,2021,0.05000000,18.28683417,66.51564000,-0.00000000,48.22880583,-0.00000000,3.19005844
1724,ESP,MOZ,2021,0.32000000,17.02800402,17.63524600,-0.00000000,0.00000000,-0.00000000,0.00000000
1725,ESP,MRT,2021,0.25000000,1.58352529,2.78075000,-0.00000000,0.00000000,-0.00000000,0.00000000
1726,ESP,MUS,2021,0.15000000,6.74553639,-3.37571100,3.59347040,0.00000000,0.53902056,0.00000000
1727,ESP,MYS,2021,0.24000000,40.41386927,40.78953800,-0.00000000,0.00000000,-0.00000000,0.00000000
1728,ESP,NGA,2021,0.30000000,8.25184366,-6.41393900,5.20697241,0.00000000,1.56209172,0.00000000
1729,ESP,NIC,2021,0.30000000,77.42182350,-9.63567500,30.90908976,0.00000000,9.27272693,0.00000000
1730,ESP,NLD,2021,0.25000000,382.03189393,-713.93309100,389.11386931,0.00000000,97.27846733,0.00000000
1731,ESP,NOR,2021,0.22000000,186.84762636,596.62687600,-0.00000000,0.00000000,-0.00000000,0.00000000
1732,ESP,NZL,2021,0.28000000,46.34011945,-136.56139500,64.93776441,0.00000000,18.18257403,0.00000000
1733,ESP,OMN,2021,0.15000000,44.80573577,-12.41457900,20.31562905,0.00000000,3.04734436,0.00000000
1734,ESP,PAN,2021,0.25000000,100.82864029,83.80934100,6.04257024,0.00000000,1.51064256,0.00000000
1735,ESP,PER,2021,0.29500000,"1,349.72997495",584.03747000,271.85318637,0.00000000,80.19668998,0.00000000
1736,ESP,PHL,2021,0.30000000,945.20748340,"1,473.09807100",-0.00000000,0.00000000,-0.00000000,0.00000000
1737,ESP,POL,2021,0.19000000,"1,104.20103621",929.34028000,62.08295555,0.00000000,11.79576155,0.00000000
1738,ESP,PRI,2021,0.37500000,64.33898823,219.08839600,-0.00000000,154.74940777,-0.00000000,3.17717788
1739,ESP,PRT,2021,0.31500000,"1,649.80387677","1,560.80176200",31.59951069,0.00000000,9.95384587,0.00000000
1740,ESP,PRY,2021,0.10000000,73.33416017,29.28189000,15.64041692,0.00000000,1.56404169,0.00000000
1741,ESP,QAT,2021,0.10000000,139.24180719,5.80647400,47.37518033,0.00000000,4.73751803,0.00000000
1742,ESP,ROU,2021,0.16000000,187.67298198,179.73346000,2.81886571,0.00000000,0.45101851,0.00000000
1743,ESP,RUS,2021,0.20000000,400.90362217,349.35851400,18.30069095,0.00000000,3.66013819,0.00000000
1744,ESP,SAU,2021,0.20000000,176.06673941,-75.07699100,89.16663400,0.00000000,17.83332680,0.00000000
1745,ESP,SEN,2021,0.30000000,3.85132007,-0.46026800,1.53079591,0.00000000,0.45923877,0.00000000
1746,ESP,SGP,2021,0.17000000,146.15566113,11.92223800,47.65853598,0.00000000,8.10195112,0.00000000
1747,ESP,SLV,2021,0.30000000,228.54100081,13.83230600,76.23065715,0.00000000,22.86919714,0.00000000
1748,ESP,SRB,2021,0.15000000,41.78508201,37.22306900,1.61970734,0.00000000,0.24295610,0.00000000
1749,ESP,SVK,2021,0.21000000,94.59332164,48.41473900,16.39534768,0.00000000,3.44302301,0.00000000
1750,ESP,SVN,2021,0.19000000,15.16346199,1.71272200,4.77558093,0.00000000,0.90736038,0.00000000
1751,ESP,SWE,2021,0.20600000,212.05327418,232.01415200,-0.00000000,19.96087782,-0.00000000,1.83351444
1752,ESP,THA,2021,0.20000000,46.50502758,25.28067300,7.53554251,0.00000000,1.50710850,0.00000000
1753,ESP,TUN,2021,0.15000000,1.82595245,-1.07470500,1.02985594,0.00000000,0.15447839,0.00000000
1754,ESP,TUR,2021,0.25000000,864.80507475,"2,636.48041100",-0.00000000,0.00000000,-0.00000000,0.00000000
1755,ESP,TWN,2021,0.20000000,143.93972041,550.75070500,-0.00000000,406.81098459,-0.00000000,58.23121382
1756,ESP,TZA,2021,0.30000000,6.79300711,5.99712100,0.28257319,0.00000000,0.08477196,0.00000000
1757,ESP,UKR,2021,0.18000000,34.59029028,88.11200800,-0.00000000,0.00000000,-0.00000000,0.00000000
1758,ESP,URY,2021,0.25000000,252.05650186,389.99335000,-0.00000000,137.93684814,-0.00000000,14.91692024
1759,ESP,USA,2021,0.27000000,"6,524.97519274","10,527.37993000",-0.00000000,0.00000000,-0.00000000,0.00000000
1760,ESP,VEN,2021,0.34000000,346.21439221,463.35899600,-0.00000000,0.00000000,-0.00000000,0.00000000
1761,ESP,VNM,2021,0.20000000,5.76223327,-33.62408600,13.98380724,0.00000000,2.79676145,0.00000000
1762,ESP,ZAF,2021,0.28000000,95.75602348,128.89935100,-0.00000000,33.14332752,-0.00000000,4.51720472
3634,FIN,ESP,2021,NaN,779.26221354,420.90845979,358.35375374,0.00000000,NaN,NaN
1788,FRA,ESP,2021,0.25000000,"9,655.65844324","3,921.75464000","2,928.50021782",0.00000000,732.12505445,0.00000000
3806,GBR,ESP,2021,NaN,"11,127.15619083","6,010.19027074","5,116.96592009",0.00000000,NaN,NaN
1876,GRC,ESP,2021,0.25000000,-1.60356247,4.17713400,-0.00000000,5.78069647,-0.00000000,0.70004431
1965,HKG,ESP,2021,0.25000000,69.83495759,77.68700100,-0.00000000,7.85204341,-0.00000000,0.95088513
595,HUN,ESP,2021,NaN,126.49556371,68.32495143,58.17061228,0.00000000,NaN,NaN
2088,IDN,ESP,2021,0.25000000,18.19010815,0.37615500,6.18936246,0.00000000,1.54734061,0.00000000
2176,IND,ESP,2021,0.25000000,176.55389066,103.42277500,1.86542814,0.00000000,0.46635704,0.00000000
4108,IRL,ESP,2021,NaN,672.54202396,363.26492230,309.27710166,0.00000000,NaN,NaN
2269,ITA,ESP,2021,0.25000000,"3,032.43838538","14,464.86220800",-0.00000000,"11,432.42382262",-0.00000000,"1,384.47041606"
2375,JPN,ESP,2021,0.25000000,"2,076.27865111",-178.44166300,"1,761.72908017",0.00000000,440.43227004,0.00000000
787,KOR,ESP,2021,NaN,"5,093.77455885","2,751.33679890","2,342.43775995",0.00000000,NaN,NaN
2515,LUX,ESP,2021,0.25000000,"3,105.32970245",927.60268900,"1,557.43911399",0.00000000,389.35977850,0.00000000
2624,MEX,ESP,2021,0.25000000,"7,505.14285527","1,207.74408100","1,355.68751270",0.00000000,338.92187818,0.00000000
861,MUS,ESP,2021,NaN,136.99671928,73.99701552,62.99970376,0.00000000,NaN,NaN
2693,MYS,ESP,2021,0.25000000,16.06773221,-0.67640000,5.86451690,0.00000000,1.46612922,0.00000000
2738,NOR,ESP,2021,0.25000000,700.73297156,-0.26800000,33.53251027,0.00000000,8.38312757,0.00000000
2793,PAN,ESP,2021,0.25000000,6.22003062,24.72200600,-0.00000000,18.50197538,-0.00000000,2.24059552
2808,PER,ESP,2021,0.25000000,0.14835675,-99.19967900,99.34803575,0.00000000,24.83700894,0.00000000
2833,PRT,ESP,2021,0.25000000,469.43127344,47.98325000,289.78558438,0.00000000,72.44639610,0.00000000
2903,ROU,ESP,2021,0.25000000,"1,242.15072946",45.26268400,128.08955972,0.00000000,32.02238993,0.00000000
3040,SAU,ESP,2021,0.25000000,"1,161.60072329",115.32217400,2.97736128,0.00000000,0.74434032,0.00000000
4639,SWE,ESP,2021,NaN,"2,386.26629330","1,288.91104011","1,097.35525319",0.00000000,NaN,NaN
3164,TUR,ESP,2021,0.25000000,29.17825737,-3.32732500,1.57804561,0.00000000,0.39451140,0.00000000
3224,USA,ESP,2021,0.25000000,"13,308.90836392","4,324.37925500","7,359.38756277",0.00000000,"1,839.84689069",0.00000000
3330,ZAF,ESP,2021,0.25000000,386.07956198,-44.29822200,352.86080743,0.00000000,88.21520186,0.00000000